{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soland.fullname" . }}
  labels:
    {{- include "soland.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $value := .Values.secretEnv }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
