-- Squashed initial migration (soland).
-- Final schema as of 2026-06-10, consolidated from the previous migration chain
-- (generated by applying all historical migrations and dumping the resulting schema).

CREATE TABLE public.account_datas (
    id uuid NOT NULL,
    actor_id text NOT NULL,
    data_type text NOT NULL,
    payload jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.accounts (
    id uuid NOT NULL,
    principal_id text NOT NULL,
    localpart text NOT NULL,
    display_name text,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    disabled_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.account_lifecycle (
    principal_id text NOT NULL,
    state text NOT NULL,
    reason text,
    changed_by text,
    changed_at timestamp with time zone NOT NULL,
    CONSTRAINT account_lifecycle_state_check CHECK ((state = ANY (ARRAY['active'::text, 'locked'::text, 'suspended'::text, 'deactivated'::text, 'erasure_pending'::text])))
);

CREATE TABLE public.handle_releases (
    localpart text NOT NULL,
    released_at timestamp with time zone NOT NULL
);

CREATE TABLE public.agent_grants (
    id text NOT NULL,
    agent_principal_id text NOT NULL,
    grant_kind text NOT NULL,
    scope jsonb NOT NULL,
    state text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    detached_at timestamp with time zone,
    expires_at timestamp with time zone,
    CONSTRAINT agent_grants_id_check CHECK (((id ~~ 'ck:accountability_grant:%'::text) OR (id ~~ 'ck:grant:%'::text))),
    CONSTRAINT agent_grants_state_check CHECK ((state = ANY (ARRAY['active'::text, 'detached'::text, 'revoked'::text, 'expired'::text])))
);

CREATE TABLE public.agent_keys (
    id uuid NOT NULL,
    agent_principal_id text NOT NULL,
    verification_method text NOT NULL,
    state text DEFAULT 'authorized'::text NOT NULL,
    authorized_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    revocation_reason text,
    CONSTRAINT agent_keys_state_check CHECK ((state = ANY (ARRAY['authorized'::text, 'revoked'::text])))
);

CREATE TABLE public.agent_participation (
    id uuid NOT NULL,
    agent_principal_id text NOT NULL,
    scope_kind text NOT NULL,
    scope_key text NOT NULL,
    realm_id uuid NOT NULL,
    scope jsonb NOT NULL,
    reply boolean DEFAULT false NOT NULL,
    accept_third_party_mention boolean DEFAULT false NOT NULL,
    act_on_behalf boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT agent_participation_scope_kind_check CHECK ((scope_kind = ANY (ARRAY['realm'::text, 'circle'::text, 'strand'::text])))
);

CREATE TABLE public.agent_participation_ceiling (
    scope_kind text NOT NULL,
    id text NOT NULL,
    realm_id uuid NOT NULL,
    reply boolean DEFAULT false NOT NULL,
    accept_third_party_mention boolean DEFAULT false NOT NULL,
    act_on_behalf boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT agent_participation_ceiling_scope_kind_check CHECK ((scope_kind = ANY (ARRAY['realm'::text, 'circle'::text, 'strand'::text])))
);

CREATE TABLE public.agent_principals (
    id text NOT NULL,
    controller_id text NOT NULL,
    agent_id text NOT NULL,
    display_name text NOT NULL,
    agent_slug text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT agent_principals_id_check CHECK (((id ~~ 'did:%'::text) AND (id !~ '[[:space:]#?]'::text))),
    CONSTRAINT agent_principals_agent_slug_check CHECK ((agent_slug IS NULL) OR (agent_slug ~ '^[a-z0-9]([a-z0-9_-]{0,62}[a-z0-9])?$'::text)),
    CONSTRAINT agent_principals_state_check CHECK ((state = ANY (ARRAY['pending_runtime_key'::text, 'active'::text, 'paused'::text, 'deactivated'::text, 'pairing_expired'::text])))
);

CREATE TABLE public.agent_sessions (
    id uuid NOT NULL,
    agent_principal_id text NOT NULL,
    verification_method text NOT NULL,
    runtime_attestation jsonb,
    state text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone,
    revoked_at timestamp with time zone,
    CONSTRAINT agent_sessions_state_check CHECK ((state = ANY (ARRAY['active'::text, 'revoked'::text, 'expired'::text])))
);

CREATE TABLE public.applet_registrations (
    id text NOT NULL,
    namespace text NOT NULL,
    owner_actor_id text NOT NULL,
    registry_did text NOT NULL,
    bot_actor_id text NOT NULL,
    portal_realm_id text NOT NULL,
    capabilities jsonb DEFAULT '[]'::jsonb NOT NULL,
    manifest jsonb NOT NULL,
    package jsonb,
    namespaces jsonb,
    allow_ghost_actors boolean DEFAULT false NOT NULL,
    status text NOT NULL,
    registered_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    idempotency_key text,
    install_body_digest text,
    install_id text,
    install_response jsonb,
    ghosts jsonb DEFAULT '[]'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT applet_registrations_status_check CHECK ((status = ANY (ARRAY['registered'::text, 'installed'::text, 'partially_installed'::text, 'rejected'::text, 'revoked'::text])))
);

CREATE TABLE public.audit_logs (
    id uuid NOT NULL,
    actor_id text,
    request_id uuid,
    action text NOT NULL,
    outcome text NOT NULL,
    realm_id uuid,
    operation_id uuid,
    device_id text,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.backup_series (
    id uuid NOT NULL,
    actor_id text NOT NULL,
    backup_class text NOT NULL,
    head_backup_id uuid,
    head_seq bigint DEFAULT 0 NOT NULL,
    frontier_ref text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    retired_at timestamp with time zone,
    CONSTRAINT backup_series_backup_class_check CHECK ((backup_class = ANY (ARRAY['did_recovery'::text, 'secret_storage'::text, 'mls_history'::text, 'external'::text]))),
    CONSTRAINT backup_series_head_seq_check CHECK ((head_seq >= 0))
);

CREATE TABLE public.blobs (
    id text NOT NULL,
    sha256 text NOT NULL,
    media_type text NOT NULL,
    filename text,
    uploaded_by_id text NOT NULL,
    realm_id uuid,
    size_bytes bigint NOT NULL,
    storage_backend text NOT NULL,
    storage_key text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    retention_expires_at timestamp with time zone,
    legal_hold boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Realm-broadcast relay for `ck.call.signal` ephemeral envelopes
-- (`webrtc-signaling.md` §5). One row per relayed signed envelope, retained
-- until `expires_at`; receivers pick it up off the subscribe
-- `ephemeral.call_signals` segment and verify the carried `proof`. `position`
-- is a monotonic per-Realm deliver-once cursor sourced from
-- `call_signal_relay_position`.
CREATE TABLE public.call_signal_relay (
    id uuid NOT NULL,
    realm_id text NOT NULL,
    position bigint NOT NULL,
    sender_actor text NOT NULL,
    sender_device text NOT NULL,
    call_id text NOT NULL,
    envelope jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

-- Per-Realm monotonic position counter for `call_signal_relay`. Held in a
-- dedicated table (not `MAX(position)` of live rows) so positions keep
-- increasing even after the relay log is pruned, and a deliver-once watermark
-- can never be re-crossed by a recycled position.
CREATE TABLE public.call_signal_relay_position (
    realm_id text NOT NULL,
    next_position bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Per-subscriber-device deliver-once watermark for `call_signal_relay`
-- (`webrtc-signaling.md` §5). Records the highest per-Realm `position` already
-- delivered to a `(actor, device, realm)` triple so an incremental
-- re-subscribe inside the TTL window does not re-emit a signal the device
-- already saw, while a full sync still recovers all non-expired pending
-- signals. Durable so a restart / replica failover preserves the cursor.
CREATE TABLE public.call_signal_relay_watermark (
    actor_id text NOT NULL,
    device_id text NOT NULL,
    realm_id text NOT NULL,
    delivered_through bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Realm-scoped relay for `ck.receipt.read` ephemeral receipt objects. The
-- normalized `receipt` follows `ck.schema.read_receipt.v1`; relay metadata
-- (`position`, `visibility`, `target_actor`, `expires_at`) gates short-TTL
-- fanout through account sync and is not durable Event history.
CREATE TABLE public.read_receipt_relay (
    id uuid NOT NULL,
    realm_id text NOT NULL,
    position bigint NOT NULL,
    actor_id text NOT NULL,
    sender_device text,
    event_id text NOT NULL,
    read_scope jsonb NOT NULL,
    target_actor text,
    visibility text NOT NULL,
    receipt jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

-- Per-Realm monotonic position counter for `read_receipt_relay`. Kept
-- separate from live rows so pruned positions are never recycled across a
-- deliver-once watermark.
CREATE TABLE public.read_receipt_relay_position (
    realm_id text NOT NULL,
    next_position bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Per-subscriber-device deliver-once watermark for read receipt relay rows.
CREATE TABLE public.read_receipt_relay_watermark (
    actor_id text NOT NULL,
    device_id text NOT NULL,
    realm_id text NOT NULL,
    delivered_through bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.canonical_events (
    id uuid NOT NULL,
    actor_id text NOT NULL,
    actor_seq bigint NOT NULL,
    realm_id uuid,
    kind text NOT NULL,
    schema_id text NOT NULL,
    canonical_digest text NOT NULL,
    canonical_bytes bytea NOT NULL,
    envelope jsonb NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.state_moves (
    id text NOT NULL,
    realm_id text NOT NULL,
    move_json jsonb NOT NULL,
    sealed_by text,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    sealed_at timestamp with time zone
);

CREATE TABLE public.state_seals (
    id text NOT NULL,
    realm_id text NOT NULL,
    seal_json jsonb NOT NULL,
    predecessor_refs jsonb DEFAULT '[]'::jsonb NOT NULL,
    is_genesis boolean DEFAULT false NOT NULL,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.state_cell_ops (
    seq bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    realm_id text NOT NULL,
    seal_id text NOT NULL,
    op_index bigint NOT NULL,
    cell_id text NOT NULL,
    move_id text NOT NULL,
    op_json jsonb NOT NULL,
    appended_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.state_cell_cache (
    realm_id text NOT NULL,
    cell_id text NOT NULL,
    view_hash text NOT NULL,
    state_json jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.consent_cells (
    id uuid NOT NULL,
    holder_id text NOT NULL,
    peer_id text NOT NULL,
    scope text NOT NULL,
    cell_id text NOT NULL,
    requested_at timestamp with time zone,
    grant_dots jsonb DEFAULT '{}'::jsonb NOT NULL,
    revoked_dots jsonb DEFAULT '[]'::jsonb NOT NULL,
    revoked_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.contacts (
    id uuid NOT NULL,
    requester_id text NOT NULL,
    target_id text NOT NULL,
    scope text NOT NULL,
    status text NOT NULL,
    message text,
    peer_service_id text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.devices (
    id uuid NOT NULL,
    actor_id text NOT NULL,
    device_id text NOT NULL,
    device_key text,
    verification_state text DEFAULT 'unverified'::text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.device_messages (
    id uuid NOT NULL,
    idempotency_key text NOT NULL,
    sender text NOT NULL,
    recipient text NOT NULL,
    device_id text NOT NULL,
    position bigint NOT NULL,
    content jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.device_message_txns (
    key text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.device_message_ack_tokens (
    ack_token text NOT NULL,
    recipient text NOT NULL,
    device_id text NOT NULL,
    queue_position bigint NOT NULL,
    issued_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone
);

CREATE TABLE public.device_message_lost_watermarks (
    recipient text NOT NULL,
    device_id text NOT NULL,
    lost_through bigint NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (recipient, device_id)
);

CREATE TABLE public.direct_conversation_bindings (
    participants_key text NOT NULL,
    participants_unordered text[] NOT NULL,
    realm_id uuid NOT NULL,
    main_strand_id uuid NOT NULL,
    binding_event_ref text NOT NULL,
    state text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.events (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    event_type text NOT NULL,
    sender_id text,
    thread_id text,
    operation_id uuid,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.federation_operations (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    object_type text NOT NULL,
    object_id text,
    operation_type text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.federation_outbox (
    id text NOT NULL,
    peer_id text NOT NULL,
    peer_url text NOT NULL,
    endpoint text NOT NULL,
    idempotency_key text NOT NULL,
    payload_json text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    next_attempt_at bigint NOT NULL,
    last_status integer,
    last_response_excerpt text,
    created_at bigint NOT NULL,
    delivered_at bigint
);

CREATE TABLE public.federation_outbox_dead_letter (
    id text NOT NULL,
    outbox_id text NOT NULL,
    peer_id text NOT NULL,
    endpoint text NOT NULL,
    idempotency_key text NOT NULL,
    terminal_status integer NOT NULL,
    attempts integer NOT NULL,
    response_excerpt text,
    failed_at bigint NOT NULL,
    reason text NOT NULL
);

CREATE TABLE public.federation_transactions (
    id uuid NOT NULL,
    source_service text NOT NULL,
    txn_id text NOT NULL,
    destination_service text NOT NULL,
    realm_id uuid,
    status text NOT NULL,
    content_digest text NOT NULL,
    payload jsonb NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    processed_at timestamp with time zone
);

CREATE TABLE public.invite_receive_policies (
    id text NOT NULL,
    policy_payload jsonb NOT NULL,
    blocked_subjects text[] DEFAULT '{}'::text[] NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.key_backups (
    id uuid NOT NULL,
    actor_id text,
    device_id text,
    backup_class text,
    backup_version text,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_accessed_at timestamp with time zone,
    account_id text,
    scheme text,
    version integer DEFAULT 0 NOT NULL,
    key_material_encrypted bytea,
    -- SOL-02-004: identity of the backup series this envelope belongs to,
    -- projected out of the JSONB payload as stored generated columns. They
    -- back the UNIQUE(series_actor_id, series_id, series_seq) constraint below
    -- which makes the §7.6 series-monotonicity check race-free: two concurrent
    -- successor PUTs that both compute the same series_seq can no longer both
    -- land — the second insert is rejected by the unique violation rather than
    -- relying on a read-then-write (TOCTOU) snapshot check.
    series_actor_id text GENERATED ALWAYS AS ((payload ->> 'actor_id')) STORED,
    series_id text GENERATED ALWAYS AS ((payload ->> 'series_id')) STORED,
    series_seq bigint GENERATED ALWAYS AS (((payload ->> 'series_seq'))::bigint) STORED
);

CREATE TABLE public.mls_commits (
    id uuid NOT NULL,
    effective_scope_kind text NOT NULL,
    realm_id text NOT NULL,
    circle_id text,
    effective_scope jsonb NOT NULL,
    mls_group_id text NOT NULL,
    epoch bigint NOT NULL,
    leader_actor_id text NOT NULL,
    covered_seals jsonb DEFAULT '[]'::jsonb NOT NULL,
    governance_binding jsonb DEFAULT '{}'::jsonb NOT NULL,
    committed_at bigint NOT NULL,
    CONSTRAINT mls_commits_effective_scope_check CHECK ((((effective_scope_kind = 'realm'::text) AND (circle_id IS NULL)) OR ((effective_scope_kind = 'circle'::text) AND (circle_id IS NOT NULL))))
);

CREATE TABLE public.mls_key_packages (
    id text NOT NULL,
    keypackage_ref text NOT NULL,
    keypackage_digest text NOT NULL,
    actor_id text NOT NULL,
    device_id text NOT NULL,
    key_package_bytes bytea NOT NULL,
    capabilities jsonb DEFAULT '[]'::jsonb NOT NULL,
    capabilities_digest text NOT NULL,
    device_signature jsonb DEFAULT '{}'::jsonb NOT NULL,
    lifetime_not_before bigint NOT NULL,
    lifetime_not_after bigint NOT NULL,
    claimed_by_mls_group_id text,
    ssk_generation bigint,
    consumed_at bigint,
    created_at bigint NOT NULL
);

CREATE TABLE public.mls_welcomes (
    id text NOT NULL,
    mls_group_id text NOT NULL,
    recipient_actor_id text NOT NULL,
    recipient_device_id text NOT NULL,
    welcome_bytes bytea NOT NULL,
    key_package_id text NOT NULL,
    enqueued_at bigint NOT NULL,
    delivered_at bigint
);

CREATE TABLE public.moderation_actions (
    id uuid NOT NULL,
    moderator_id text,
    target_actor_id text,
    action_kind text,
    realm_id uuid,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.moderation_reports (
    id uuid NOT NULL,
    reporter_id text,
    target_actor_id text,
    target_event_id uuid,
    realm_id uuid,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.organizations (
    organization_id text NOT NULL,
    organization_did text NOT NULL,
    handle text,
    display_name text NOT NULL,
    verified boolean DEFAULT true NOT NULL,
    members jsonb DEFAULT '[]'::jsonb NOT NULL,
    member_count bigint DEFAULT 0 NOT NULL,
    created_by text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.organization_policies (
    organization_id text NOT NULL,
    policy_id text NOT NULL,
    payload jsonb NOT NULL,
    version bigint NOT NULL,
    updated_by text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT organization_policies_version_check CHECK ((version >= 0))
);

CREATE TABLE public.realm_organizations (
    realm_id text NOT NULL,
    organization_id text NOT NULL,
    linked_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.realm_moderation_policies (
    realm_id text NOT NULL,
    payload jsonb NOT NULL,
    updated_by text NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.retention_policies (
    realm_id text NOT NULL,
    ttl_seconds bigint NOT NULL,
    updated_by text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT retention_policies_ttl_seconds_check CHECK ((ttl_seconds >= 0))
);

CREATE TABLE public.retention_tombstones (
    event_id text NOT NULL,
    realm_id text NOT NULL,
    reason text NOT NULL,
    policy_ttl_seconds bigint NOT NULL,
    expired_at timestamp with time zone NOT NULL,
    tombstoned_at timestamp with time zone NOT NULL,
    sealed boolean DEFAULT false NOT NULL,
    CONSTRAINT retention_tombstones_policy_ttl_seconds_check CHECK ((policy_ttl_seconds >= 0))
);

CREATE TABLE public.multisig_pending (
    id text NOT NULL,
    realm_id uuid NOT NULL,
    threshold_k integer NOT NULL,
    threshold_n integer NOT NULL,
    members text[] NOT NULL,
    canonical_b64 text DEFAULT ''::text NOT NULL,
    partials jsonb DEFAULT '{}'::jsonb NOT NULL,
    claimed_by_node_id text,
    claimed_until timestamp with time zone,
    claim_seq bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone DEFAULT (now() + '01:00:00'::interval) NOT NULL
);

CREATE TABLE public.notifications (
    id uuid NOT NULL,
    recipient_id text NOT NULL,
    realm_id uuid NOT NULL,
    source_event_id text NOT NULL,
    notification_type text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    read_at timestamp with time zone
);

CREATE TABLE public.pending_agent_drafts (
    id uuid NOT NULL,
    agent_principal_id text NOT NULL,
    controller_id text NOT NULL,
    draft_payload jsonb NOT NULL,
    state text DEFAULT 'pending'::text NOT NULL,
    proposed_at timestamp with time zone NOT NULL,
    decided_at timestamp with time zone,
    decided_by_id text,
    CONSTRAINT pending_agent_drafts_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'expired'::text])))
);

CREATE TABLE public.policy_documents (
    id uuid NOT NULL,
    owner_id text NOT NULL,
    scope text NOT NULL,
    subject_ref text NOT NULL,
    policy_type text NOT NULL,
    document jsonb NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    signed_by_id text,
    active boolean DEFAULT true NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.presence (
    id text NOT NULL,
    status text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.projection_circle_members (
    id uuid NOT NULL,
    circle_id uuid NOT NULL,
    actor_id text NOT NULL,
    state text DEFAULT 'active'::text NOT NULL,
    joined_at timestamp with time zone NOT NULL,
    removed_at timestamp with time zone,
    CONSTRAINT projection_circle_members_state_check CHECK ((state = ANY (ARRAY['invited'::text, 'active'::text, 'removed'::text, 'banned'::text, 'left'::text])))
);

CREATE TABLE public.projection_circles (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    title text NOT NULL,
    summary text,
    directory_visibility text DEFAULT 'members'::text NOT NULL,
    join_rule text DEFAULT 'invite'::text NOT NULL,
    history_visibility text DEFAULT 'joined'::text NOT NULL,
    content_encryption_floor text,
    metadata_encryption_floor text,
    encryption_profile text DEFAULT 'mls_rfc9420'::text NOT NULL,
    mls_group_ref text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by_id text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_by_id text,
    updated_at timestamp with time zone,
    CONSTRAINT projection_circles_content_encryption_floor_check CHECK ((content_encryption_floor = ANY (ARRAY['allow_plaintext'::text, 'e2ee_required'::text]))),
    CONSTRAINT projection_circles_directory_visibility_check CHECK ((directory_visibility = ANY (ARRAY['members'::text, 'realm_members'::text]))),
    CONSTRAINT projection_circles_join_rule_check CHECK ((join_rule = ANY (ARRAY['invite'::text, 'request'::text, 'open'::text]))),
    CONSTRAINT projection_circles_metadata_encryption_floor_check CHECK ((metadata_encryption_floor = ANY (ARRAY['allow_plaintext'::text, 'e2ee_required'::text]))),
    CONSTRAINT projection_circles_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'tombstoned'::text])))
);

CREATE TABLE public.projection_events (
    id bigint NOT NULL,
    event_id uuid NOT NULL,
    realm_id uuid NOT NULL,
    event_kind text NOT NULL,
    operation_type text NOT NULL,
    operation_id uuid,
    sender_id text,
    payload jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    effective_scope text
);

CREATE SEQUENCE public.projection_events_ordinal_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.projection_events_ordinal_seq OWNED BY public.projection_events.id;

CREATE TABLE public.projection_strand_watches (
    id uuid NOT NULL,
    strand_id uuid NOT NULL,
    actor_id text NOT NULL,
    level text,
    level_public boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT projection_strand_watches_level_check CHECK (((level IS NULL) OR (level = ANY (ARRAY['mentions_only'::text, 'participating'::text, 'all'::text, 'muted'::text]))))
);

CREATE TABLE public.projection_strands (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    scope_circle_id uuid,
    tracks jsonb DEFAULT '{"synthesis": {}}'::jsonb NOT NULL,
    title text NOT NULL,
    summary text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by_id text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_by_id text,
    updated_at timestamp with time zone,
    CONSTRAINT projection_strands_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'redacted'::text])))
);

CREATE TABLE public.projection_morphs (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    morph_type text NOT NULL,
    title text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by_id text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_by_id text,
    updated_at timestamp with time zone,
    fields jsonb DEFAULT '{}'::jsonb NOT NULL,
    schema_refs jsonb DEFAULT '[]'::jsonb NOT NULL,
    facets jsonb DEFAULT '[]'::jsonb NOT NULL,
    versions jsonb DEFAULT '[]'::jsonb NOT NULL,
    scope_circle_id uuid,
    CONSTRAINT projection_morphs_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'redacted'::text])))
);

CREATE TABLE public.projection_spaces (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    scope_circle_id uuid,
    default_scope_circle_id uuid,
    child_scope_policy text,
    child_scope_policy_scope_circle_id uuid,
    child_scope_policy_metadata_encryption_floor text,
    kind text NOT NULL,
    title text NOT NULL,
    parent_ref uuid,
    rank text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by_id text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_by_id text,
    updated_at timestamp with time zone,
    CONSTRAINT projection_spaces_child_scope_policy_check CHECK ((child_scope_policy = ANY (ARRAY['allow_any'::text, 'require_e2ee'::text, 'require_same_scope'::text, 'require_scope_circle_id'::text]))),
    CONSTRAINT projection_spaces_child_scope_policy_scope_check CHECK (((child_scope_policy <> 'require_scope_circle_id'::text) OR (child_scope_policy_scope_circle_id IS NOT NULL))),
    CONSTRAINT projection_spaces_child_scope_policy_metadata_floor_check CHECK ((child_scope_policy_metadata_encryption_floor = ANY (ARRAY['allow_plaintext'::text, 'e2ee_required'::text]))),
    CONSTRAINT projection_spaces_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'tombstoned'::text])))
);

CREATE TABLE public.push_bridge_cache (
    id text NOT NULL,
    push_gateway_url text NOT NULL,
    service_base_url text NOT NULL,
    bridge_describe_url text NOT NULL,
    fetch_state text NOT NULL,
    cache_state text NOT NULL,
    contract_digest text NOT NULL,
    fetched_at timestamp with time zone NOT NULL,
    remote_contract jsonb NOT NULL,
    trust_level text DEFAULT 'pending'::text NOT NULL,
    freshness_at timestamp with time zone DEFAULT now() NOT NULL,
    etag text DEFAULT ''::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.push_devices (
    id text NOT NULL,
    actor_id text,
    device_id text NOT NULL,
    push_gateway text NOT NULL,
    push_key text NOT NULL,
    platform text,
    app_id text,
    payload jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.realm_invites (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    inviter_id text NOT NULL,
    invitee_id text,
    invite_delivery_target jsonb,
    introduction_evidence_digest text,
    third_party_id jsonb,
    join_rule_snapshot jsonb,
    invite_token text NOT NULL,
    status text NOT NULL,
    claim_nonces jsonb DEFAULT '{}'::jsonb NOT NULL,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone
);

CREATE TABLE public.recovery_policies (
    id uuid NOT NULL,
    principal_id text NOT NULL,
    version integer NOT NULL,
    trust_domain text NOT NULL,
    allowed_proof_kinds text[] NOT NULL,
    supersedes uuid,
    expires_at timestamp with time zone,
    issued_at timestamp with time zone NOT NULL,
    verification_method text NOT NULL,
    raw_payload jsonb NOT NULL,
    accepted_at timestamp with time zone NOT NULL,
    CONSTRAINT recovery_policies_version_check CHECK ((version >= 1))
);

CREATE TABLE public.recovery_receipts (
    id uuid NOT NULL,
    principal_id text NOT NULL,
    recovery_session_id uuid NOT NULL,
    policy_id uuid NOT NULL,
    policy_version integer NOT NULL,
    trust_domain text NOT NULL,
    new_device_id text NOT NULL,
    proof_digest text NOT NULL,
    outcome text NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone NOT NULL,
    verification_method text NOT NULL,
    raw_payload jsonb NOT NULL,
    accepted_at timestamp with time zone NOT NULL,
    CONSTRAINT recovery_receipts_policy_version_check CHECK ((policy_version >= 1))
);

CREATE TABLE public.recovery_sessions (
    id uuid NOT NULL,
    principal_id text NOT NULL,
    requesting_device_id text NOT NULL,
    trust_domain text NOT NULL,
    policy_id uuid NOT NULL,
    policy_version integer NOT NULL,
    ssk_generation integer NOT NULL,
    policy_payload jsonb NOT NULL,
    challenge text NOT NULL,
    state text DEFAULT 'pending'::text NOT NULL,
    proof_payload jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT recovery_sessions_policy_version_check CHECK ((policy_version >= 1)),
    CONSTRAINT recovery_sessions_ssk_generation_check CHECK ((ssk_generation >= 1)),
    CONSTRAINT recovery_sessions_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'verified'::text, 'completed'::text, 'rejected'::text, 'expired'::text])))
);

CREATE TABLE public.sessions (
    id text NOT NULL,
    actor_id text NOT NULL,
    device_id text NOT NULL,
    audience text NOT NULL,
    session_public_key text,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.space_members (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    actor_id text NOT NULL,
    membership text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    joined_at timestamp with time zone,
    left_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.space_state_events (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    event_type text NOT NULL,
    subject text DEFAULT ''::text NOT NULL,
    sender_id text,
    operation_id uuid,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.spaces (
    id uuid NOT NULL,
    title text NOT NULL,
    summary text,
    owner_id text,
    discoverability text DEFAULT 'invite_only'::text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    history_visibility text DEFAULT 'joined'::text NOT NULL,
    history_sharing_policy jsonb,
    history_sharing_policy_digest text,
    preview_policy jsonb,
    preview_policy_digest text,
    encryption_profile text DEFAULT 'mls_rfc9420'::text NOT NULL,
    plaintext_visible_services jsonb DEFAULT '[]'::jsonb NOT NULL,
    CONSTRAINT spaces_encryption_profile_check CHECK ((encryption_profile = ANY (ARRAY['none'::text, 'plaintext'::text, 'mls_rfc9420'::text]))),
    CONSTRAINT spaces_history_visibility_check CHECK ((history_visibility = ANY (ARRAY['world_readable'::text, 'shared'::text, 'invited'::text, 'joined'::text, 'restricted'::text])))
);

CREATE TABLE public.sync_cursor_handles (
    id text NOT NULL,
    principal_id text,
    device_id text,
    service_id text NOT NULL,
    filter_digest text,
    purpose text NOT NULL,
    positions jsonb,
    target jsonb,
    issued_at_ms bigint NOT NULL,
    expires_at_ms bigint NOT NULL,
    CONSTRAINT sync_cursor_handles_purpose_check CHECK ((purpose = ANY (ARRAY['stream'::text, 'barrier'::text])))
);

CREATE TABLE public.sync_cursor_revocations (
    id uuid NOT NULL,
    cursor_digest text NOT NULL,
    principal_id text NOT NULL,
    device_id text,
    scope text NOT NULL,
    reason_code text NOT NULL,
    revoked_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT sync_cursor_revocations_scope_check CHECK ((scope = ANY (ARRAY['this_cursor'::text, 'same_device'::text, 'same_session'::text])))
);

CREATE TABLE public.webrtc_sessions (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    initiator_id text NOT NULL,
    ice_config jsonb DEFAULT '{}'::jsonb NOT NULL,
    signaling_state jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

CREATE TABLE public.webvh_documents (
    id text NOT NULL,
    did_document jsonb NOT NULL,
    key_log_head text,
    seq bigint DEFAULT 0 NOT NULL,
    method_evidence jsonb DEFAULT '{}'::jsonb NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone DEFAULT (now() + '00:15:00'::interval) NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.webvh_log_events (
    id text NOT NULL,
    did text NOT NULL,
    seq bigint NOT NULL,
    operation jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.projection_events ALTER COLUMN id SET DEFAULT nextval('public.projection_events_ordinal_seq'::regclass);

ALTER TABLE ONLY public.account_datas
    ADD CONSTRAINT account_datas_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.account_datas
    ADD CONSTRAINT account_datas_actor_data_type_key UNIQUE (actor_id, data_type);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_principal_id_key UNIQUE (principal_id);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_localpart_key UNIQUE (localpart);

ALTER TABLE ONLY public.account_lifecycle
    ADD CONSTRAINT account_lifecycle_pkey PRIMARY KEY (principal_id);

ALTER TABLE ONLY public.handle_releases
    ADD CONSTRAINT handle_releases_pkey PRIMARY KEY (localpart);

ALTER TABLE ONLY public.agent_grants
    ADD CONSTRAINT agent_grants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.agent_keys
    ADD CONSTRAINT agent_keys_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.agent_participation_ceiling
    ADD CONSTRAINT agent_participation_ceiling_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.agent_participation
    ADD CONSTRAINT agent_participation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.agent_participation
    ADD CONSTRAINT agent_participation_agent_principal_id_scope_key_key UNIQUE (agent_principal_id, scope_key);

ALTER TABLE ONLY public.agent_principals
    ADD CONSTRAINT agent_principals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.agent_sessions
    ADD CONSTRAINT agent_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.applet_registrations
    ADD CONSTRAINT applet_registrations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.backup_series
    ADD CONSTRAINT backup_series_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.blobs
    ADD CONSTRAINT blobs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.call_signal_relay
    ADD CONSTRAINT call_signal_relay_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.call_signal_relay
    ADD CONSTRAINT call_signal_relay_realm_position_key UNIQUE (realm_id, position);

ALTER TABLE ONLY public.call_signal_relay_position
    ADD CONSTRAINT call_signal_relay_position_pkey PRIMARY KEY (realm_id);

ALTER TABLE ONLY public.call_signal_relay_watermark
    ADD CONSTRAINT call_signal_relay_watermark_pkey PRIMARY KEY (actor_id, device_id, realm_id);

ALTER TABLE ONLY public.read_receipt_relay
    ADD CONSTRAINT read_receipt_relay_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.read_receipt_relay
    ADD CONSTRAINT read_receipt_relay_realm_position_key UNIQUE (realm_id, position);

ALTER TABLE ONLY public.read_receipt_relay_position
    ADD CONSTRAINT read_receipt_relay_position_pkey PRIMARY KEY (realm_id);

ALTER TABLE ONLY public.read_receipt_relay_watermark
    ADD CONSTRAINT read_receipt_relay_watermark_pkey PRIMARY KEY (actor_id, device_id, realm_id);

ALTER TABLE ONLY public.canonical_events
    ADD CONSTRAINT canonical_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.state_moves
    ADD CONSTRAINT state_moves_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.state_seals
    ADD CONSTRAINT state_seals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.state_cell_ops
    ADD CONSTRAINT state_cell_ops_pkey PRIMARY KEY (seq);

ALTER TABLE ONLY public.state_cell_ops
    ADD CONSTRAINT state_cell_ops_seal_op_index_key UNIQUE (seal_id, op_index);

ALTER TABLE ONLY public.state_cell_cache
    ADD CONSTRAINT state_cell_cache_pkey PRIMARY KEY (realm_id, cell_id, view_hash);

ALTER TABLE ONLY public.consent_cells
    ADD CONSTRAINT consent_cells_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.consent_cells
    ADD CONSTRAINT consent_cells_holder_peer_scope_key UNIQUE (holder_id, peer_id, scope);

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_requester_target_scope_key UNIQUE (requester_id, target_id, scope);

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_actor_device_id_key UNIQUE (actor_id, device_id);

ALTER TABLE ONLY public.device_messages
    ADD CONSTRAINT device_messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.device_messages
    ADD CONSTRAINT device_messages_recipient_device_position_key UNIQUE (recipient, device_id, position);

ALTER TABLE ONLY public.device_message_txns
    ADD CONSTRAINT device_message_txns_pkey PRIMARY KEY (key);

ALTER TABLE ONLY public.device_message_ack_tokens
    ADD CONSTRAINT device_message_ack_tokens_pkey PRIMARY KEY (ack_token);

ALTER TABLE ONLY public.direct_conversation_bindings
    ADD CONSTRAINT direct_conversation_bindings_pkey PRIMARY KEY (participants_key);

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.federation_operations
    ADD CONSTRAINT federation_operations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.federation_outbox_dead_letter
    ADD CONSTRAINT federation_outbox_dead_letter_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.federation_outbox
    ADD CONSTRAINT federation_outbox_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.federation_transactions
    ADD CONSTRAINT federation_transactions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.federation_transactions
    ADD CONSTRAINT federation_transactions_source_service_txn_id_key UNIQUE (source_service, txn_id);

ALTER TABLE ONLY public.invite_receive_policies
    ADD CONSTRAINT invite_receive_policies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.key_backups
    ADD CONSTRAINT key_backups_pkey PRIMARY KEY (id);

-- SOL-02-004: enforce series_seq monotonicity at the storage layer. A given
-- (actor, series) may hold at most one envelope per sequence number; the
-- receive path depends on this constraint so concurrent successor PUTs cannot
-- double-write the same seq (TOCTOU). NULLs (non-series backups) are exempt
-- because Postgres treats NULL as distinct in a UNIQUE index.
ALTER TABLE ONLY public.key_backups
    ADD CONSTRAINT key_backups_series_seq_key UNIQUE (series_actor_id, series_id, series_seq);

ALTER TABLE ONLY public.mls_commits
    ADD CONSTRAINT mls_commits_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mls_key_packages
    ADD CONSTRAINT mls_key_packages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mls_welcomes
    ADD CONSTRAINT mls_welcomes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.moderation_actions
    ADD CONSTRAINT moderation_actions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.moderation_reports
    ADD CONSTRAINT moderation_reports_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (organization_id);

ALTER TABLE ONLY public.organization_policies
    ADD CONSTRAINT organization_policies_pkey PRIMARY KEY (organization_id);

ALTER TABLE ONLY public.realm_organizations
    ADD CONSTRAINT realm_organizations_pkey PRIMARY KEY (realm_id, organization_id);

ALTER TABLE ONLY public.realm_moderation_policies
    ADD CONSTRAINT realm_moderation_policies_pkey PRIMARY KEY (realm_id);

ALTER TABLE ONLY public.retention_policies
    ADD CONSTRAINT retention_policies_pkey PRIMARY KEY (realm_id);

ALTER TABLE ONLY public.retention_tombstones
    ADD CONSTRAINT retention_tombstones_pkey PRIMARY KEY (event_id);

ALTER TABLE ONLY public.multisig_pending
    ADD CONSTRAINT multisig_pending_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pending_agent_drafts
    ADD CONSTRAINT pending_agent_drafts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.policy_documents
    ADD CONSTRAINT policy_documents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.presence
    ADD CONSTRAINT presence_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projection_circle_members
    ADD CONSTRAINT projection_circle_members_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projection_circle_members
    ADD CONSTRAINT projection_circle_members_circle_id_actor_id_key UNIQUE (circle_id, actor_id);

ALTER TABLE ONLY public.projection_circles
    ADD CONSTRAINT projection_circles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projection_events
    ADD CONSTRAINT projection_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projection_strand_watches
    ADD CONSTRAINT projection_strand_watches_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projection_strand_watches
    ADD CONSTRAINT projection_strand_watches_strand_id_actor_id_key UNIQUE (strand_id, actor_id);

ALTER TABLE ONLY public.projection_strands
    ADD CONSTRAINT projection_strands_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projection_morphs
    ADD CONSTRAINT projection_morphs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projection_spaces
    ADD CONSTRAINT projection_spaces_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.push_bridge_cache
    ADD CONSTRAINT push_bridge_cache_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.push_devices
    ADD CONSTRAINT push_devices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.realm_invites
    ADD CONSTRAINT realm_invites_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.recovery_policies
    ADD CONSTRAINT recovery_policies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.recovery_policies
    ADD CONSTRAINT recovery_policies_principal_id_version_key UNIQUE (principal_id, version);

ALTER TABLE ONLY public.recovery_receipts
    ADD CONSTRAINT recovery_receipts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.recovery_receipts
    ADD CONSTRAINT recovery_receipts_recovery_session_id_key UNIQUE (recovery_session_id);

ALTER TABLE ONLY public.recovery_sessions
    ADD CONSTRAINT recovery_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.space_members
    ADD CONSTRAINT space_members_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.space_members
    ADD CONSTRAINT space_members_realm_id_actor_key UNIQUE (realm_id, actor_id);

ALTER TABLE ONLY public.space_state_events
    ADD CONSTRAINT space_state_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.spaces
    ADD CONSTRAINT spaces_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sync_cursor_handles
    ADD CONSTRAINT sync_cursor_handles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sync_cursor_revocations
    ADD CONSTRAINT sync_cursor_revocations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.webrtc_sessions
    ADD CONSTRAINT webrtc_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.webvh_documents
    ADD CONSTRAINT webvh_documents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.webvh_log_events
    ADD CONSTRAINT webvh_log_events_did_seq_key UNIQUE (did, seq);

ALTER TABLE ONLY public.webvh_log_events
    ADD CONSTRAINT webvh_log_events_pkey PRIMARY KEY (id);

CREATE INDEX agent_grants_principal_idx ON public.agent_grants USING btree (agent_principal_id);

CREATE INDEX account_lifecycle_state_idx ON public.account_lifecycle USING btree (state, changed_at);

CREATE INDEX agent_grants_state_idx ON public.agent_grants USING btree (state);

CREATE INDEX agent_keys_principal_idx ON public.agent_keys USING btree (agent_principal_id);

CREATE INDEX agent_keys_state_idx ON public.agent_keys USING btree (state);

CREATE INDEX agent_participation_ceiling_realm_idx ON public.agent_participation_ceiling USING btree (realm_id);

CREATE INDEX agent_participation_realm_idx ON public.agent_participation USING btree (realm_id);

CREATE INDEX agent_principals_controller_idx ON public.agent_principals USING btree (controller_id);
CREATE INDEX agent_principals_controller_agent_slug_idx ON public.agent_principals USING btree (controller_id, agent_slug) WHERE (agent_slug IS NOT NULL);

CREATE INDEX agent_principals_state_idx ON public.agent_principals USING btree (state);

CREATE INDEX agent_sessions_principal_idx ON public.agent_sessions USING btree (agent_principal_id);

CREATE INDEX agent_sessions_state_idx ON public.agent_sessions USING btree (state);

CREATE UNIQUE INDEX applet_registrations_active_namespace_idx ON public.applet_registrations USING btree (namespace) WHERE (revoked_at IS NULL);

CREATE INDEX applet_registrations_owner_idx ON public.applet_registrations USING btree (owner_actor_id);

CREATE INDEX applet_registrations_status_idx ON public.applet_registrations USING btree (status);

CREATE INDEX audit_logs_action_idx ON public.audit_logs USING btree (action);

CREATE INDEX audit_logs_actor_idx ON public.audit_logs USING btree (actor_id, created_at);

CREATE INDEX audit_logs_space_idx ON public.audit_logs USING btree (realm_id);

CREATE UNIQUE INDEX backup_series_actor_class_uniq ON public.backup_series USING btree (actor_id, backup_class) WHERE (retired_at IS NULL);

CREATE INDEX backup_series_actor_idx ON public.backup_series USING btree (actor_id);

CREATE INDEX backup_series_class_idx ON public.backup_series USING btree (backup_class);

CREATE INDEX blobs_sha256_idx ON public.blobs USING btree (sha256);

CREATE INDEX blobs_space_created_idx ON public.blobs USING btree (realm_id, created_at);

CREATE INDEX call_signal_relay_realm_position_idx ON public.call_signal_relay USING btree (realm_id, position);

CREATE INDEX call_signal_relay_expires_idx ON public.call_signal_relay USING btree (expires_at);

CREATE INDEX read_receipt_relay_realm_position_idx ON public.read_receipt_relay USING btree (realm_id, position);

CREATE INDEX read_receipt_relay_event_idx ON public.read_receipt_relay USING btree (event_id);

CREATE INDEX read_receipt_relay_expires_idx ON public.read_receipt_relay USING btree (expires_at);

CREATE INDEX canonical_events_actor_idx ON public.canonical_events USING btree (actor_id, actor_seq DESC);

CREATE INDEX canonical_events_kind_idx ON public.canonical_events USING btree (kind);

CREATE INDEX canonical_events_space_idx ON public.canonical_events USING btree (realm_id);

CREATE INDEX state_moves_pending_idx ON public.state_moves USING btree (realm_id, inserted_at, id) WHERE (sealed_by IS NULL);

CREATE INDEX state_moves_sealed_idx ON public.state_moves USING btree (realm_id, inserted_at, id) WHERE (sealed_by IS NOT NULL);

CREATE INDEX state_seals_realm_idx ON public.state_seals USING btree (realm_id, inserted_at, id);

CREATE INDEX state_seals_predecessor_refs_idx ON public.state_seals USING gin (predecessor_refs);

CREATE INDEX state_cell_ops_cell_idx ON public.state_cell_ops USING btree (realm_id, cell_id, seq);

CREATE INDEX state_cell_ops_seal_idx ON public.state_cell_ops USING btree (realm_id, seal_id);

CREATE INDEX contacts_target_idx ON public.contacts USING btree (target_id, scope);

CREATE INDEX devices_actor_updated_idx ON public.devices USING btree (actor_id, updated_at DESC);

CREATE INDEX device_message_ack_tokens_device_idx ON public.device_message_ack_tokens USING btree (recipient, device_id, expires_at);

CREATE INDEX device_messages_recipient_device_position_idx ON public.device_messages USING btree (recipient, device_id, position);

CREATE INDEX device_messages_sender_idempotency_idx ON public.device_messages USING btree (sender, idempotency_key);

CREATE INDEX events_space_created_idx ON public.events USING btree (realm_id, created_at, id);

CREATE INDEX events_thread_created_idx ON public.events USING btree (thread_id, created_at, id) WHERE (thread_id IS NOT NULL);

CREATE INDEX federation_operations_object_type_idx ON public.federation_operations USING btree (object_type);

CREATE INDEX federation_operations_space_idx ON public.federation_operations USING btree (realm_id, created_at);

CREATE INDEX federation_outbox_dead_letter_failed_at ON public.federation_outbox_dead_letter USING btree (failed_at, id);

CREATE UNIQUE INDEX federation_outbox_peer_idem ON public.federation_outbox USING btree (peer_id, idempotency_key);

CREATE INDEX federation_outbox_pending ON public.federation_outbox USING btree (delivered_at, next_attempt_at);

CREATE INDEX federation_transactions_destination_received_idx ON public.federation_transactions USING btree (destination_service, received_at);

CREATE INDEX federation_transactions_space_received_idx ON public.federation_transactions USING btree (realm_id, received_at);

CREATE INDEX key_backups_account_idx ON public.key_backups USING btree (account_id);

CREATE INDEX key_backups_actor_idx ON public.key_backups USING btree (actor_id);

CREATE INDEX key_backups_device_idx ON public.key_backups USING btree (device_id);

CREATE UNIQUE INDEX mls_commits_circle_scope_key ON public.mls_commits USING btree (realm_id, circle_id, mls_group_id) WHERE ((effective_scope_kind = 'circle'::text) AND (circle_id IS NOT NULL));

CREATE UNIQUE INDEX mls_commits_realm_scope_key ON public.mls_commits USING btree (realm_id, mls_group_id) WHERE ((effective_scope_kind = 'realm'::text) AND (circle_id IS NULL));

CREATE INDEX mls_key_packages_by_actor_device ON public.mls_key_packages USING btree (actor_id, device_id, claimed_by_mls_group_id);

CREATE INDEX mls_welcomes_recipient_pending ON public.mls_welcomes USING btree (recipient_actor_id, recipient_device_id, delivered_at, enqueued_at);

CREATE INDEX moderation_actions_target_idx ON public.moderation_actions USING btree (target_actor_id);

CREATE INDEX moderation_reports_space_idx ON public.moderation_reports USING btree (realm_id);

CREATE INDEX moderation_reports_target_idx ON public.moderation_reports USING btree (target_actor_id);

CREATE INDEX organizations_handle_idx ON public.organizations USING btree (handle) WHERE (handle IS NOT NULL);

CREATE INDEX organizations_did_idx ON public.organizations USING btree (organization_did);

CREATE INDEX realm_organizations_organization_idx ON public.realm_organizations USING btree (organization_id);

CREATE INDEX retention_tombstones_realm_idx ON public.retention_tombstones USING btree (realm_id);

CREATE INDEX multisig_pending_claim_seq_idx ON public.multisig_pending USING btree (claim_seq);

CREATE INDEX multisig_pending_claimed_idx ON public.multisig_pending USING btree (claimed_until);

CREATE INDEX multisig_pending_expires_idx ON public.multisig_pending USING btree (expires_at);

CREATE INDEX multisig_pending_space_idx ON public.multisig_pending USING btree (realm_id);

CREATE INDEX notifications_recipient_idx ON public.notifications USING btree (recipient_id, created_at DESC);

CREATE INDEX notifications_source_idx ON public.notifications USING btree (source_event_id);

CREATE INDEX pending_agent_drafts_controller_idx ON public.pending_agent_drafts USING btree (controller_id);

CREATE INDEX pending_agent_drafts_principal_idx ON public.pending_agent_drafts USING btree (agent_principal_id);

CREATE INDEX pending_agent_drafts_state_idx ON public.pending_agent_drafts USING btree (state);

CREATE INDEX policy_documents_owner_idx ON public.policy_documents USING btree (owner_id);

CREATE INDEX policy_documents_scope_subject_idx ON public.policy_documents USING btree (scope, subject_ref, policy_type);

CREATE INDEX projection_circle_members_actor_idx ON public.projection_circle_members USING btree (actor_id);

CREATE INDEX projection_circles_realm_idx ON public.projection_circles USING btree (realm_id);

CREATE INDEX projection_circles_state_idx ON public.projection_circles USING btree (state);

CREATE INDEX projection_events_created_at_idx ON public.projection_events USING btree (created_at);

CREATE INDEX projection_events_effective_scope_idx ON public.projection_events USING btree (effective_scope);

CREATE INDEX projection_events_space_idx ON public.projection_events USING btree (realm_id);

CREATE INDEX projection_strand_watches_actor_idx ON public.projection_strand_watches USING btree (actor_id) WHERE ((level IS NOT NULL) AND (level <> 'mentions_only'::text));

CREATE INDEX projection_strand_watches_strand_idx ON public.projection_strand_watches USING btree (strand_id) WHERE ((level IS NOT NULL) AND (level <> 'mentions_only'::text));

CREATE INDEX projection_strands_realm_idx ON public.projection_strands USING btree (realm_id);

CREATE INDEX projection_strands_scope_circle_id_idx ON public.projection_strands USING btree (scope_circle_id);

CREATE INDEX projection_strands_state_idx ON public.projection_strands USING btree (state);

CREATE INDEX projection_morphs_realm_idx ON public.projection_morphs USING btree (realm_id);

CREATE INDEX projection_morphs_scope_circle_id_idx ON public.projection_morphs USING btree (scope_circle_id);

CREATE INDEX projection_morphs_state_idx ON public.projection_morphs USING btree (state);

CREATE INDEX projection_morphs_type_idx ON public.projection_morphs USING btree (morph_type);

CREATE INDEX projection_spaces_parent_idx ON public.projection_spaces USING btree (parent_ref) WHERE (parent_ref IS NOT NULL);

CREATE INDEX projection_spaces_realm_idx ON public.projection_spaces USING btree (realm_id);

CREATE INDEX projection_spaces_scope_circle_id_idx ON public.projection_spaces USING btree (scope_circle_id);

CREATE INDEX projection_spaces_state_idx ON public.projection_spaces USING btree (state);

CREATE INDEX push_bridge_cache_fetched_at_idx ON public.push_bridge_cache USING btree (fetched_at);

CREATE INDEX push_bridge_cache_trust_freshness_idx ON public.push_bridge_cache USING btree (trust_level, freshness_at);

CREATE INDEX realm_invites_invitee_idx ON public.realm_invites USING btree (invitee_id);

CREATE INDEX realm_invites_realm_idx ON public.realm_invites USING btree (realm_id);

CREATE INDEX recovery_policies_principal_active_idx ON public.recovery_policies USING btree (principal_id, version DESC);

CREATE INDEX recovery_receipts_policy_idx ON public.recovery_receipts USING btree (policy_id, policy_version);

CREATE INDEX recovery_receipts_principal_idx ON public.recovery_receipts USING btree (principal_id);

CREATE INDEX recovery_sessions_principal_idx ON public.recovery_sessions USING btree (principal_id);

CREATE INDEX sessions_actor_device_idx ON public.sessions USING btree (actor_id, device_id, expires_at) WHERE (revoked_at IS NULL);

CREATE INDEX space_members_actor_idx ON public.space_members USING btree (actor_id, membership, realm_id);

CREATE INDEX space_state_events_lookup_idx ON public.space_state_events USING btree (realm_id, event_type, subject, created_at);

CREATE INDEX spaces_discoverability_updated_idx ON public.spaces USING btree (discoverability, updated_at, id);

CREATE INDEX spaces_history_sharing_policy_digest_idx ON public.spaces USING btree (history_sharing_policy_digest) WHERE (history_sharing_policy_digest IS NOT NULL);

CREATE INDEX spaces_history_visibility_updated_idx ON public.spaces USING btree (history_visibility, updated_at, id);

CREATE INDEX spaces_preview_policy_digest_idx ON public.spaces USING btree (preview_policy_digest) WHERE (preview_policy_digest IS NOT NULL);

CREATE INDEX sync_cursor_handles_expiry_idx ON public.sync_cursor_handles USING btree (expires_at_ms);

CREATE INDEX sync_cursor_handles_stream_idx ON public.sync_cursor_handles USING btree (principal_id, device_id, filter_digest);

CREATE INDEX sync_cursor_revocations_expiry_idx ON public.sync_cursor_revocations USING btree (expires_at);

CREATE INDEX webrtc_sessions_expires_idx ON public.webrtc_sessions USING btree (expires_at);

CREATE INDEX webrtc_sessions_space_idx ON public.webrtc_sessions USING btree (realm_id);

CREATE INDEX webvh_documents_expires_at_idx ON public.webvh_documents USING btree (expires_at);

CREATE INDEX webvh_log_events_did_seq_idx ON public.webvh_log_events USING btree (did, seq);

ALTER TABLE ONLY public.agent_grants
    ADD CONSTRAINT agent_grants_agent_principal_id_fkey FOREIGN KEY (agent_principal_id) REFERENCES public.agent_principals(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.agent_keys
    ADD CONSTRAINT agent_keys_agent_principal_id_fkey FOREIGN KEY (agent_principal_id) REFERENCES public.agent_principals(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.agent_participation
    ADD CONSTRAINT agent_participation_agent_principal_id_fkey FOREIGN KEY (agent_principal_id) REFERENCES public.agent_principals(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.agent_sessions
    ADD CONSTRAINT agent_sessions_agent_principal_id_fkey FOREIGN KEY (agent_principal_id) REFERENCES public.agent_principals(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.federation_outbox_dead_letter
    ADD CONSTRAINT federation_outbox_dead_letter_outbox_id_fkey FOREIGN KEY (outbox_id) REFERENCES public.federation_outbox(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.pending_agent_drafts
    ADD CONSTRAINT pending_agent_drafts_agent_principal_id_fkey FOREIGN KEY (agent_principal_id) REFERENCES public.agent_principals(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.projection_circle_members
    ADD CONSTRAINT projection_circle_members_circle_id_fkey FOREIGN KEY (circle_id) REFERENCES public.projection_circles(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.recovery_policies
    ADD CONSTRAINT recovery_policies_supersedes_fkey FOREIGN KEY (supersedes) REFERENCES public.recovery_policies(id);

ALTER TABLE ONLY public.recovery_receipts
    ADD CONSTRAINT recovery_receipts_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.recovery_policies(id);
