-- Squashed initial migration (soland).
-- Final schema as of 2026-06-10, consolidated from the previous migration chain
-- (generated by applying all historical migrations and dumping the resulting schema).

CREATE TABLE public.account_datas (
    actor text NOT NULL,
    data_type text NOT NULL,
    payload jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.accounts (
    id uuid NOT NULL,
    actor_id text NOT NULL,
    localpart text NOT NULL,
    display_name text,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    disabled_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.agent_grant (
    grant_id text NOT NULL,
    agent_principal_id text NOT NULL,
    grant_kind text NOT NULL,
    scope jsonb NOT NULL,
    state text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    detached_at timestamp with time zone,
    expires_at timestamp with time zone,
    CONSTRAINT agent_grant_grant_id_check CHECK (((grant_id ~~ 'ck:accountability_grant:%'::text) OR (grant_id ~~ 'ck:grant:%'::text))),
    CONSTRAINT agent_grant_state_check CHECK ((state = ANY (ARRAY['active'::text, 'detached'::text, 'revoked'::text, 'expired'::text])))
);

CREATE TABLE public.agent_key (
    agent_key_id text NOT NULL,
    agent_principal_id text NOT NULL,
    verification_method text NOT NULL,
    state text DEFAULT 'authorized'::text NOT NULL,
    authorized_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    revocation_reason text,
    CONSTRAINT agent_key_agent_key_id_check CHECK ((agent_key_id ~~ 'ck:agent_key:%'::text)),
    CONSTRAINT agent_key_state_check CHECK ((state = ANY (ARRAY['authorized'::text, 'revoked'::text])))
);

CREATE TABLE public.agent_participation (
    agent_principal_id text NOT NULL,
    scope_kind text NOT NULL,
    scope_key text NOT NULL,
    realm_id text NOT NULL,
    scope jsonb NOT NULL,
    reply boolean DEFAULT false NOT NULL,
    accept_third_party_mention boolean DEFAULT false NOT NULL,
    act_on_behalf boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT agent_participation_scope_kind_check CHECK ((scope_kind = ANY (ARRAY['realm'::text, 'circle'::text, 'flow'::text])))
);

CREATE TABLE public.agent_participation_ceiling (
    scope_kind text NOT NULL,
    scope_key text NOT NULL,
    realm_id text NOT NULL,
    reply boolean DEFAULT false NOT NULL,
    accept_third_party_mention boolean DEFAULT false NOT NULL,
    act_on_behalf boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT agent_participation_ceiling_scope_kind_check CHECK ((scope_kind = ANY (ARRAY['realm'::text, 'circle'::text, 'flow'::text])))
);

CREATE TABLE public.agent_principal (
    agent_principal_id text NOT NULL,
    controller_did text NOT NULL,
    agent_id text NOT NULL,
    display_name text NOT NULL,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT agent_principal_agent_principal_id_check CHECK (((agent_principal_id ~~ 'did:%'::text) AND (agent_principal_id !~ '[[:space:]#?]'::text))),
    CONSTRAINT agent_principal_state_check CHECK ((state = ANY (ARRAY['active'::text, 'paused'::text, 'deactivated'::text])))
);

CREATE TABLE public.agent_session (
    agent_session_id text NOT NULL,
    agent_principal_id text NOT NULL,
    verification_method text NOT NULL,
    runtime_attestation jsonb,
    state text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone,
    revoked_at timestamp with time zone,
    CONSTRAINT agent_session_agent_session_id_check CHECK ((agent_session_id ~~ 'ck:agent_session:%'::text)),
    CONSTRAINT agent_session_state_check CHECK ((state = ANY (ARRAY['active'::text, 'revoked'::text, 'expired'::text])))
);

CREATE TABLE public.audit_logs (
    id uuid NOT NULL,
    actor text,
    request_id uuid,
    action text NOT NULL,
    outcome text NOT NULL,
    realm_id uuid,
    operation_id uuid,
    device_id text,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.backup_series (
    series_id text NOT NULL,
    actor_id text NOT NULL,
    backup_class text NOT NULL,
    head_backup_id text,
    head_seq bigint DEFAULT 0 NOT NULL,
    frontier_ref text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    retired_at timestamp with time zone,
    CONSTRAINT backup_series_backup_class_check CHECK ((backup_class = ANY (ARRAY['did_recovery'::text, 'secret_storage'::text, 'mls_history'::text, 'external'::text]))),
    CONSTRAINT backup_series_head_seq_check CHECK ((head_seq >= 0)),
    CONSTRAINT backup_series_series_id_check CHECK ((series_id ~~ 'ck:backup_series:%'::text))
);

CREATE TABLE public.blobs (
    blob_ref text NOT NULL,
    sha256 text NOT NULL,
    media_type text NOT NULL,
    filename text,
    uploaded_by text NOT NULL,
    realm_id uuid,
    size_bytes bigint NOT NULL,
    storage_backend text NOT NULL,
    storage_key text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    retention_expires_at timestamp with time zone,
    legal_hold boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.canonical_events (
    id uuid NOT NULL,
    actor_id text NOT NULL,
    actor_seq bigint NOT NULL,
    realm_id uuid,
    kind text NOT NULL,
    schema_id text NOT NULL,
    canonical_digest text NOT NULL,
    canonical_bytes bytea NOT NULL,
    envelope jsonb NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.consent_cells (
    holder text NOT NULL,
    peer text NOT NULL,
    scope text NOT NULL,
    cell_id text NOT NULL,
    requested_at timestamp with time zone,
    grant_dots jsonb DEFAULT '{}'::jsonb NOT NULL,
    revoked_dots jsonb DEFAULT '[]'::jsonb NOT NULL,
    revoked_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.contacts (
    requester text NOT NULL,
    target text NOT NULL,
    scope text NOT NULL,
    status text NOT NULL,
    message text,
    peer_service_did text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.devices (
    actor text NOT NULL,
    device_id text NOT NULL,
    device_key text,
    verification_state text DEFAULT 'unverified'::text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.direct_conversation_bindings (
    participants_key text NOT NULL,
    participants_unordered text[] NOT NULL,
    realm_id uuid NOT NULL,
    main_flow_id uuid NOT NULL,
    binding_event_ref text NOT NULL,
    state text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.events (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    event_type text NOT NULL,
    sender text,
    thread_id text,
    operation_id uuid,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.federation_operations (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    object_type text NOT NULL,
    object_id text,
    operation_type text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.federation_outbox (
    id text NOT NULL,
    peer_did text NOT NULL,
    peer_url text NOT NULL,
    endpoint text NOT NULL,
    idempotency_key text NOT NULL,
    payload_json text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    next_attempt_at bigint NOT NULL,
    last_status integer,
    last_response_excerpt text,
    created_at bigint NOT NULL,
    delivered_at bigint
);

CREATE TABLE public.federation_outbox_dead_letter (
    id text NOT NULL,
    outbox_id text NOT NULL,
    peer_did text NOT NULL,
    endpoint text NOT NULL,
    idempotency_key text NOT NULL,
    terminal_status integer NOT NULL,
    attempts integer NOT NULL,
    response_excerpt text,
    failed_at bigint NOT NULL,
    reason text NOT NULL
);

CREATE TABLE public.federation_transactions (
    source_service text NOT NULL,
    txn_id text NOT NULL,
    destination_service text NOT NULL,
    realm_id uuid,
    status text NOT NULL,
    content_digest text NOT NULL,
    payload jsonb NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    processed_at timestamp with time zone
);

CREATE TABLE public.invite_receive_policies (
    subject_id text NOT NULL,
    policy_payload jsonb NOT NULL,
    blocked_subjects text[] DEFAULT '{}'::text[] NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.key_backups (
    backup_id text NOT NULL,
    actor_id text,
    device_id text,
    backup_class text,
    backup_version text,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_accessed_at timestamp with time zone,
    account_id text,
    scheme text,
    version integer DEFAULT 0 NOT NULL,
    key_material_encrypted bytea
);

CREATE TABLE public.mls_commits (
    group_id text NOT NULL,
    epoch bigint NOT NULL,
    leader_actor_did text NOT NULL,
    covered_frontier jsonb DEFAULT '[]'::jsonb NOT NULL,
    governance_binding jsonb DEFAULT '{}'::jsonb NOT NULL,
    committed_at bigint NOT NULL
);

CREATE TABLE public.mls_key_packages (
    id text NOT NULL,
    actor_did text NOT NULL,
    device_id text NOT NULL,
    lifetime_not_before bigint NOT NULL,
    lifetime_not_after bigint NOT NULL,
    key_package_bytes bytea NOT NULL,
    claimed_by_group_id text,
    consumed_at bigint,
    created_at bigint NOT NULL
);

CREATE TABLE public.mls_welcomes (
    id text NOT NULL,
    group_id text NOT NULL,
    recipient_actor_did text NOT NULL,
    recipient_device_id text NOT NULL,
    welcome_bytes bytea NOT NULL,
    key_package_id text NOT NULL,
    enqueued_at bigint NOT NULL,
    delivered_at bigint
);

CREATE TABLE public.moderation_actions (
    id uuid NOT NULL,
    moderator text,
    target_actor text,
    action_kind text,
    realm_id uuid,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.moderation_reports (
    id uuid NOT NULL,
    reporter text,
    target_actor text,
    target_event_id uuid,
    realm_id uuid,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.multisig_pending (
    anchor_id text NOT NULL,
    realm_id uuid NOT NULL,
    threshold_k integer NOT NULL,
    threshold_n integer NOT NULL,
    members text[] NOT NULL,
    canonical_b64 text DEFAULT ''::text NOT NULL,
    partials jsonb DEFAULT '{}'::jsonb NOT NULL,
    claimed_by_node_id text,
    claimed_until timestamp with time zone,
    claim_seq bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone DEFAULT (now() + '01:00:00'::interval) NOT NULL
);

CREATE TABLE public.notification (
    notification_id uuid NOT NULL,
    recipient_id text NOT NULL,
    realm_id uuid NOT NULL,
    source_event_id text NOT NULL,
    notification_type text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    read_at timestamp with time zone
);

CREATE TABLE public.pending_agent_drafts (
    draft_id text NOT NULL,
    agent_principal_id text NOT NULL,
    controller_did text NOT NULL,
    draft_payload jsonb NOT NULL,
    state text DEFAULT 'pending'::text NOT NULL,
    proposed_at timestamp with time zone NOT NULL,
    decided_at timestamp with time zone,
    decided_by text,
    CONSTRAINT pending_agent_drafts_draft_id_check CHECK ((draft_id ~~ 'ck:agent_draft:%'::text)),
    CONSTRAINT pending_agent_drafts_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'expired'::text])))
);

CREATE TABLE public.policy_documents (
    policy_id text NOT NULL,
    owner text NOT NULL,
    scope text NOT NULL,
    subject_ref text NOT NULL,
    policy_type text NOT NULL,
    document jsonb NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    signed_by text,
    active boolean DEFAULT true NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.presence (
    actor text NOT NULL,
    status text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.projection_circle_members (
    circle_id uuid NOT NULL,
    actor_did text NOT NULL,
    state text DEFAULT 'active'::text NOT NULL,
    joined_at timestamp with time zone NOT NULL,
    removed_at timestamp with time zone,
    CONSTRAINT projection_circle_members_state_check CHECK ((state = ANY (ARRAY['invited'::text, 'active'::text, 'removed'::text, 'banned'::text, 'left'::text])))
);

CREATE TABLE public.projection_circles (
    circle_id uuid NOT NULL,
    realm_id uuid NOT NULL,
    title text NOT NULL,
    summary text,
    directory_visibility text DEFAULT 'members'::text NOT NULL,
    join_rule text DEFAULT 'invite'::text NOT NULL,
    history_visibility text DEFAULT 'joined'::text NOT NULL,
    content_encryption_floor text,
    metadata_encryption_floor text,
    encryption_profile text DEFAULT 'mls_rfc9420'::text NOT NULL,
    mls_group_ref text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_by text,
    updated_at timestamp with time zone,
    CONSTRAINT projection_circles_content_encryption_floor_check CHECK ((content_encryption_floor = ANY (ARRAY['allow_plaintext'::text, 'e2ee_required'::text]))),
    CONSTRAINT projection_circles_directory_visibility_check CHECK ((directory_visibility = ANY (ARRAY['members'::text, 'realm_members'::text]))),
    CONSTRAINT projection_circles_join_rule_check CHECK ((join_rule = ANY (ARRAY['invite'::text, 'request'::text, 'open'::text]))),
    CONSTRAINT projection_circles_metadata_encryption_floor_check CHECK ((metadata_encryption_floor = ANY (ARRAY['allow_plaintext'::text, 'e2ee_required'::text]))),
    CONSTRAINT projection_circles_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'tombstoned'::text])))
);

CREATE TABLE public.projection_events (
    ordinal bigint NOT NULL,
    event_id uuid NOT NULL,
    realm_id uuid NOT NULL,
    event_kind text NOT NULL,
    operation_type text NOT NULL,
    operation_id uuid,
    sender text,
    payload jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    effective_scope text
);

CREATE SEQUENCE public.projection_events_ordinal_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.projection_events_ordinal_seq OWNED BY public.projection_events.ordinal;

CREATE TABLE public.projection_flow_watches (
    flow_id uuid NOT NULL,
    actor_did text NOT NULL,
    level text,
    level_public boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT projection_flow_watches_level_check CHECK (((level IS NULL) OR (level = ANY (ARRAY['mentions_only'::text, 'participating'::text, 'all'::text, 'muted'::text]))))
);

CREATE TABLE public.projection_flows (
    flow_id uuid NOT NULL,
    realm_id uuid NOT NULL,
    scope_circle_id text,
    title text NOT NULL,
    summary text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_by text,
    updated_at timestamp with time zone,
    CONSTRAINT projection_flows_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'redacted'::text])))
);

CREATE TABLE public.projection_morphs (
    morph_id uuid NOT NULL,
    realm_id uuid NOT NULL,
    morph_type text NOT NULL,
    title text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_by text,
    updated_at timestamp with time zone,
    fields jsonb DEFAULT '{}'::jsonb NOT NULL,
    schema_refs jsonb DEFAULT '[]'::jsonb NOT NULL,
    facets jsonb DEFAULT '[]'::jsonb NOT NULL,
    versions jsonb DEFAULT '[]'::jsonb NOT NULL,
    scope_circle_id text,
    CONSTRAINT projection_morphs_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'redacted'::text])))
);

CREATE TABLE public.projection_space_containers (
    container_space_id uuid NOT NULL,
    realm_id uuid NOT NULL,
    kind text NOT NULL,
    rank text,
    title text NOT NULL,
    parent_ref text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_by text,
    updated_at timestamp with time zone,
    scope_circle_id text,
    default_scope_circle_id text,
    child_scope_policy text,
    CONSTRAINT projection_space_containers_child_scope_policy_check CHECK ((child_scope_policy = ANY (ARRAY['free'::text, 'require_scope_circle_id'::text, 'locked'::text]))),
    CONSTRAINT projection_space_containers_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'tombstoned'::text])))
);

CREATE TABLE public.push_bridge_cache (
    cache_key text NOT NULL,
    push_gateway_url text NOT NULL,
    service_base_url text NOT NULL,
    bridge_describe_url text NOT NULL,
    fetch_state text NOT NULL,
    cache_state text NOT NULL,
    contract_digest text NOT NULL,
    fetched_at timestamp with time zone NOT NULL,
    remote_contract jsonb NOT NULL,
    trust_level text DEFAULT 'pending'::text NOT NULL,
    freshness_at timestamp with time zone DEFAULT now() NOT NULL,
    etag text DEFAULT ''::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.push_devices (
    registration_id text NOT NULL,
    actor text,
    device_id text NOT NULL,
    push_gateway text NOT NULL,
    push_key text NOT NULL,
    platform text,
    app_id text,
    payload jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.realm_invites (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    inviter text NOT NULL,
    invitee text,
    invite_delivery_target jsonb,
    introduction_evidence_digest text,
    invite_token text NOT NULL,
    status text NOT NULL,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.recovery_policies (
    policy_id text NOT NULL,
    principal_id text NOT NULL,
    version integer NOT NULL,
    trust_domain text NOT NULL,
    allowed_proof_kinds text[] NOT NULL,
    supersedes text,
    expires_at timestamp with time zone,
    issued_at timestamp with time zone NOT NULL,
    verification_method text NOT NULL,
    raw_payload jsonb NOT NULL,
    accepted_at timestamp with time zone NOT NULL,
    CONSTRAINT recovery_policies_policy_id_check CHECK ((policy_id ~~ 'ck:policy:%'::text)),
    CONSTRAINT recovery_policies_version_check CHECK ((version >= 1))
);

CREATE TABLE public.recovery_receipts (
    receipt_id text NOT NULL,
    principal_id text NOT NULL,
    recovery_session_id text NOT NULL,
    policy_id text NOT NULL,
    policy_version integer NOT NULL,
    trust_domain text NOT NULL,
    new_device_id text NOT NULL,
    proof_digest text NOT NULL,
    outcome text NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone NOT NULL,
    verification_method text NOT NULL,
    raw_payload jsonb NOT NULL,
    accepted_at timestamp with time zone NOT NULL,
    CONSTRAINT recovery_receipts_policy_version_check CHECK ((policy_version >= 1)),
    CONSTRAINT recovery_receipts_receipt_id_check CHECK ((receipt_id ~~ 'ck:receipt:%'::text)),
    CONSTRAINT recovery_receipts_recovery_session_id_check CHECK ((recovery_session_id ~~ 'ck:recovery_session:%'::text))
);

CREATE TABLE public.recovery_session (
    recovery_session_id text NOT NULL,
    principal_id text NOT NULL,
    requesting_device_id text NOT NULL,
    trust_domain text NOT NULL,
    policy_id text NOT NULL,
    policy_version integer NOT NULL,
    ssk_generation integer NOT NULL,
    policy_payload jsonb NOT NULL,
    challenge text NOT NULL,
    state text DEFAULT 'pending'::text NOT NULL,
    proof_payload jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT recovery_session_policy_version_check CHECK ((policy_version >= 1)),
    CONSTRAINT recovery_session_recovery_session_id_check CHECK ((recovery_session_id ~~ 'ck:recovery_session:%'::text)),
    CONSTRAINT recovery_session_ssk_generation_check CHECK ((ssk_generation >= 1)),
    CONSTRAINT recovery_session_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'verified'::text, 'completed'::text, 'rejected'::text, 'expired'::text])))
);

CREATE TABLE public.sessions (
    token_hash text NOT NULL,
    actor text NOT NULL,
    device_id text NOT NULL,
    audience text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.space_members (
    realm_id uuid NOT NULL,
    actor text NOT NULL,
    membership text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    joined_at timestamp with time zone,
    left_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.space_state_events (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    event_type text NOT NULL,
    subject text DEFAULT ''::text NOT NULL,
    sender text,
    operation_id uuid,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.spaces (
    id uuid NOT NULL,
    title text NOT NULL,
    summary text,
    owner text,
    discoverability text DEFAULT 'invite_only'::text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    history_visibility text DEFAULT 'joined'::text NOT NULL,
    history_sharing_policy jsonb,
    history_sharing_policy_digest text,
    preview_policy jsonb,
    preview_policy_digest text,
    encryption_profile text DEFAULT 'mls_rfc9420'::text NOT NULL,
    plaintext_visible_services jsonb DEFAULT '[]'::jsonb NOT NULL,
    CONSTRAINT spaces_encryption_profile_check CHECK ((encryption_profile = ANY (ARRAY['none'::text, 'plaintext'::text, 'mls_rfc9420'::text]))),
    CONSTRAINT spaces_history_visibility_check CHECK ((history_visibility = ANY (ARRAY['world_readable'::text, 'shared'::text, 'invited'::text, 'joined'::text, 'restricted'::text])))
);

CREATE TABLE public.sync_cursor_handles (
    handle text NOT NULL,
    principal_id text,
    device_id text,
    service_id text NOT NULL,
    filter_digest text,
    purpose text NOT NULL,
    positions jsonb,
    target jsonb,
    issued_at_ms bigint NOT NULL,
    expires_at_ms bigint NOT NULL,
    CONSTRAINT sync_cursor_handles_purpose_check CHECK ((purpose = ANY (ARRAY['stream'::text, 'barrier'::text])))
);

CREATE TABLE public.webrtc_sessions (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    initiator_did text NOT NULL,
    ice_config jsonb DEFAULT '{}'::jsonb NOT NULL,
    signaling_state jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

CREATE TABLE public.webvh_documents (
    did text NOT NULL,
    did_document jsonb NOT NULL,
    key_log_head text,
    seq bigint DEFAULT 0 NOT NULL,
    method_evidence jsonb DEFAULT '{}'::jsonb NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone DEFAULT (now() + '00:15:00'::interval) NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.webvh_log_events (
    event_digest text NOT NULL,
    did text NOT NULL,
    seq bigint NOT NULL,
    operation jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.projection_events ALTER COLUMN ordinal SET DEFAULT nextval('public.projection_events_ordinal_seq'::regclass);

ALTER TABLE ONLY public.account_datas
    ADD CONSTRAINT account_datas_pkey PRIMARY KEY (actor, data_type);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_actor_id_key UNIQUE (actor_id);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_localpart_key UNIQUE (localpart);

ALTER TABLE ONLY public.agent_grant
    ADD CONSTRAINT agent_grant_pkey PRIMARY KEY (grant_id);

ALTER TABLE ONLY public.agent_key
    ADD CONSTRAINT agent_key_pkey PRIMARY KEY (agent_key_id);

ALTER TABLE ONLY public.agent_participation_ceiling
    ADD CONSTRAINT agent_participation_ceiling_pkey PRIMARY KEY (scope_key);

ALTER TABLE ONLY public.agent_participation
    ADD CONSTRAINT agent_participation_pkey PRIMARY KEY (agent_principal_id, scope_key);

ALTER TABLE ONLY public.agent_principal
    ADD CONSTRAINT agent_principal_pkey PRIMARY KEY (agent_principal_id);

ALTER TABLE ONLY public.agent_session
    ADD CONSTRAINT agent_session_pkey PRIMARY KEY (agent_session_id);

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.backup_series
    ADD CONSTRAINT backup_series_pkey PRIMARY KEY (series_id);

ALTER TABLE ONLY public.blobs
    ADD CONSTRAINT blobs_pkey PRIMARY KEY (blob_ref);

ALTER TABLE ONLY public.canonical_events
    ADD CONSTRAINT canonical_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.consent_cells
    ADD CONSTRAINT consent_cells_pkey PRIMARY KEY (holder, peer, scope);

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_pkey PRIMARY KEY (requester, target, scope);

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (actor, device_id);

ALTER TABLE ONLY public.direct_conversation_bindings
    ADD CONSTRAINT direct_conversation_bindings_pkey PRIMARY KEY (participants_key);

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.federation_operations
    ADD CONSTRAINT federation_operations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.federation_outbox_dead_letter
    ADD CONSTRAINT federation_outbox_dead_letter_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.federation_outbox
    ADD CONSTRAINT federation_outbox_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.federation_transactions
    ADD CONSTRAINT federation_transactions_pkey PRIMARY KEY (source_service, txn_id);

ALTER TABLE ONLY public.invite_receive_policies
    ADD CONSTRAINT invite_receive_policies_pkey PRIMARY KEY (subject_id);

ALTER TABLE ONLY public.key_backups
    ADD CONSTRAINT key_backups_pkey PRIMARY KEY (backup_id);

ALTER TABLE ONLY public.mls_commits
    ADD CONSTRAINT mls_commits_pkey PRIMARY KEY (group_id);

ALTER TABLE ONLY public.mls_key_packages
    ADD CONSTRAINT mls_key_packages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mls_welcomes
    ADD CONSTRAINT mls_welcomes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.moderation_actions
    ADD CONSTRAINT moderation_actions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.moderation_reports
    ADD CONSTRAINT moderation_reports_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.multisig_pending
    ADD CONSTRAINT multisig_pending_pkey PRIMARY KEY (anchor_id);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (notification_id);

ALTER TABLE ONLY public.pending_agent_drafts
    ADD CONSTRAINT pending_agent_drafts_pkey PRIMARY KEY (draft_id);

ALTER TABLE ONLY public.policy_documents
    ADD CONSTRAINT policy_documents_pkey PRIMARY KEY (policy_id);

ALTER TABLE ONLY public.presence
    ADD CONSTRAINT presence_pkey PRIMARY KEY (actor);

ALTER TABLE ONLY public.projection_circle_members
    ADD CONSTRAINT projection_circle_members_pkey PRIMARY KEY (circle_id, actor_did);

ALTER TABLE ONLY public.projection_circles
    ADD CONSTRAINT projection_circles_pkey PRIMARY KEY (circle_id);

ALTER TABLE ONLY public.projection_events
    ADD CONSTRAINT projection_events_pkey PRIMARY KEY (ordinal);

ALTER TABLE ONLY public.projection_flow_watches
    ADD CONSTRAINT projection_flow_watches_pkey PRIMARY KEY (flow_id, actor_did);

ALTER TABLE ONLY public.projection_flows
    ADD CONSTRAINT projection_flows_pkey PRIMARY KEY (flow_id);

ALTER TABLE ONLY public.projection_morphs
    ADD CONSTRAINT projection_morphs_pkey PRIMARY KEY (morph_id);

ALTER TABLE ONLY public.projection_space_containers
    ADD CONSTRAINT projection_space_containers_pkey PRIMARY KEY (container_space_id);

ALTER TABLE ONLY public.push_bridge_cache
    ADD CONSTRAINT push_bridge_cache_pkey PRIMARY KEY (cache_key);

ALTER TABLE ONLY public.push_devices
    ADD CONSTRAINT push_devices_pkey PRIMARY KEY (registration_id);

ALTER TABLE ONLY public.realm_invites
    ADD CONSTRAINT realm_invites_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.recovery_policies
    ADD CONSTRAINT recovery_policies_pkey PRIMARY KEY (policy_id);

ALTER TABLE ONLY public.recovery_policies
    ADD CONSTRAINT recovery_policies_principal_id_version_key UNIQUE (principal_id, version);

ALTER TABLE ONLY public.recovery_receipts
    ADD CONSTRAINT recovery_receipts_pkey PRIMARY KEY (receipt_id);

ALTER TABLE ONLY public.recovery_receipts
    ADD CONSTRAINT recovery_receipts_recovery_session_id_key UNIQUE (recovery_session_id);

ALTER TABLE ONLY public.recovery_session
    ADD CONSTRAINT recovery_session_pkey PRIMARY KEY (recovery_session_id);

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (token_hash);

ALTER TABLE ONLY public.space_members
    ADD CONSTRAINT space_members_pkey PRIMARY KEY (realm_id, actor);

ALTER TABLE ONLY public.space_state_events
    ADD CONSTRAINT space_state_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.spaces
    ADD CONSTRAINT spaces_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sync_cursor_handles
    ADD CONSTRAINT sync_cursor_handles_pkey PRIMARY KEY (handle);

ALTER TABLE ONLY public.webrtc_sessions
    ADD CONSTRAINT webrtc_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.webvh_documents
    ADD CONSTRAINT webvh_documents_pkey PRIMARY KEY (did);

ALTER TABLE ONLY public.webvh_log_events
    ADD CONSTRAINT webvh_log_events_did_seq_key UNIQUE (did, seq);

ALTER TABLE ONLY public.webvh_log_events
    ADD CONSTRAINT webvh_log_events_pkey PRIMARY KEY (event_digest);

CREATE INDEX agent_grant_principal_idx ON public.agent_grant USING btree (agent_principal_id);

CREATE INDEX agent_grant_state_idx ON public.agent_grant USING btree (state);

CREATE INDEX agent_key_principal_idx ON public.agent_key USING btree (agent_principal_id);

CREATE INDEX agent_key_state_idx ON public.agent_key USING btree (state);

CREATE INDEX agent_participation_ceiling_realm_idx ON public.agent_participation_ceiling USING btree (realm_id);

CREATE INDEX agent_participation_realm_idx ON public.agent_participation USING btree (realm_id);

CREATE INDEX agent_principal_controller_idx ON public.agent_principal USING btree (controller_did);

CREATE INDEX agent_principal_state_idx ON public.agent_principal USING btree (state);

CREATE INDEX agent_session_principal_idx ON public.agent_session USING btree (agent_principal_id);

CREATE INDEX agent_session_state_idx ON public.agent_session USING btree (state);

CREATE INDEX audit_logs_action_idx ON public.audit_logs USING btree (action);

CREATE INDEX audit_logs_actor_idx ON public.audit_logs USING btree (actor, created_at);

CREATE INDEX audit_logs_space_idx ON public.audit_logs USING btree (realm_id);

CREATE UNIQUE INDEX backup_series_actor_class_uniq ON public.backup_series USING btree (actor_id, backup_class) WHERE (retired_at IS NULL);

CREATE INDEX backup_series_actor_idx ON public.backup_series USING btree (actor_id);

CREATE INDEX backup_series_class_idx ON public.backup_series USING btree (backup_class);

CREATE INDEX blobs_sha256_idx ON public.blobs USING btree (sha256);

CREATE INDEX blobs_space_created_idx ON public.blobs USING btree (realm_id, created_at);

CREATE INDEX canonical_events_actor_idx ON public.canonical_events USING btree (actor_id, actor_seq DESC);

CREATE INDEX canonical_events_kind_idx ON public.canonical_events USING btree (kind);

CREATE INDEX canonical_events_space_idx ON public.canonical_events USING btree (realm_id);

CREATE INDEX contacts_target_idx ON public.contacts USING btree (target, scope);

CREATE INDEX devices_actor_updated_idx ON public.devices USING btree (actor, updated_at DESC);

CREATE INDEX events_space_created_idx ON public.events USING btree (realm_id, created_at, id);

CREATE INDEX events_thread_created_idx ON public.events USING btree (thread_id, created_at, id) WHERE (thread_id IS NOT NULL);

CREATE INDEX federation_operations_object_type_idx ON public.federation_operations USING btree (object_type);

CREATE INDEX federation_operations_space_idx ON public.federation_operations USING btree (realm_id, created_at);

CREATE INDEX federation_outbox_dead_letter_failed_at ON public.federation_outbox_dead_letter USING btree (failed_at, id);

CREATE UNIQUE INDEX federation_outbox_peer_idem ON public.federation_outbox USING btree (peer_did, idempotency_key);

CREATE INDEX federation_outbox_pending ON public.federation_outbox USING btree (delivered_at, next_attempt_at);

CREATE INDEX federation_transactions_destination_received_idx ON public.federation_transactions USING btree (destination_service, received_at);

CREATE INDEX federation_transactions_space_received_idx ON public.federation_transactions USING btree (realm_id, received_at);

CREATE INDEX key_backups_account_idx ON public.key_backups USING btree (account_id);

CREATE INDEX key_backups_actor_idx ON public.key_backups USING btree (actor_id);

CREATE INDEX key_backups_device_idx ON public.key_backups USING btree (device_id);

CREATE INDEX mls_key_packages_by_actor_device ON public.mls_key_packages USING btree (actor_did, device_id, claimed_by_group_id);

CREATE INDEX mls_welcomes_recipient_pending ON public.mls_welcomes USING btree (recipient_actor_did, recipient_device_id, delivered_at, enqueued_at);

CREATE INDEX moderation_actions_target_idx ON public.moderation_actions USING btree (target_actor);

CREATE INDEX moderation_reports_space_idx ON public.moderation_reports USING btree (realm_id);

CREATE INDEX moderation_reports_target_idx ON public.moderation_reports USING btree (target_actor);

CREATE INDEX multisig_pending_claim_seq_idx ON public.multisig_pending USING btree (claim_seq);

CREATE INDEX multisig_pending_claimed_idx ON public.multisig_pending USING btree (claimed_until);

CREATE INDEX multisig_pending_expires_idx ON public.multisig_pending USING btree (expires_at);

CREATE INDEX multisig_pending_space_idx ON public.multisig_pending USING btree (realm_id);

CREATE INDEX notification_recipient_idx ON public.notification USING btree (recipient_id, created_at DESC);

CREATE INDEX notification_source_idx ON public.notification USING btree (source_event_id);

CREATE INDEX pending_agent_drafts_controller_idx ON public.pending_agent_drafts USING btree (controller_did);

CREATE INDEX pending_agent_drafts_principal_idx ON public.pending_agent_drafts USING btree (agent_principal_id);

CREATE INDEX pending_agent_drafts_state_idx ON public.pending_agent_drafts USING btree (state);

CREATE INDEX policy_documents_owner_idx ON public.policy_documents USING btree (owner);

CREATE INDEX policy_documents_scope_subject_idx ON public.policy_documents USING btree (scope, subject_ref, policy_type);

CREATE INDEX projection_circle_members_actor_idx ON public.projection_circle_members USING btree (actor_did);

CREATE INDEX projection_circles_realm_idx ON public.projection_circles USING btree (realm_id);

CREATE INDEX projection_circles_state_idx ON public.projection_circles USING btree (state);

CREATE INDEX projection_events_created_at_idx ON public.projection_events USING btree (created_at);

CREATE INDEX projection_events_effective_scope_idx ON public.projection_events USING btree (effective_scope);

CREATE INDEX projection_events_space_idx ON public.projection_events USING btree (realm_id);

CREATE INDEX projection_flow_watches_actor_idx ON public.projection_flow_watches USING btree (actor_did) WHERE ((level IS NOT NULL) AND (level <> 'mentions_only'::text));

CREATE INDEX projection_flow_watches_flow_idx ON public.projection_flow_watches USING btree (flow_id) WHERE ((level IS NOT NULL) AND (level <> 'mentions_only'::text));

CREATE INDEX projection_flows_realm_idx ON public.projection_flows USING btree (realm_id);

CREATE INDEX projection_flows_scope_circle_id_idx ON public.projection_flows USING btree (scope_circle_id);

CREATE INDEX projection_flows_state_idx ON public.projection_flows USING btree (state);

CREATE INDEX projection_morphs_realm_idx ON public.projection_morphs USING btree (realm_id);

CREATE INDEX projection_morphs_scope_circle_id_idx ON public.projection_morphs USING btree (scope_circle_id);

CREATE INDEX projection_morphs_state_idx ON public.projection_morphs USING btree (state);

CREATE INDEX projection_morphs_type_idx ON public.projection_morphs USING btree (morph_type);

CREATE INDEX projection_space_containers_parent_idx ON public.projection_space_containers USING btree (parent_ref) WHERE (parent_ref IS NOT NULL);

CREATE INDEX projection_space_containers_realm_idx ON public.projection_space_containers USING btree (realm_id);

CREATE INDEX projection_space_containers_scope_circle_id_idx ON public.projection_space_containers USING btree (scope_circle_id);

CREATE INDEX projection_space_containers_state_idx ON public.projection_space_containers USING btree (state);

CREATE INDEX push_bridge_cache_fetched_at_idx ON public.push_bridge_cache USING btree (fetched_at);

CREATE INDEX push_bridge_cache_trust_freshness_idx ON public.push_bridge_cache USING btree (trust_level, freshness_at);

CREATE INDEX realm_invites_invitee_idx ON public.realm_invites USING btree (invitee);

CREATE INDEX realm_invites_realm_idx ON public.realm_invites USING btree (realm_id);

CREATE INDEX recovery_policies_principal_active_idx ON public.recovery_policies USING btree (principal_id, version DESC);

CREATE INDEX recovery_receipts_policy_idx ON public.recovery_receipts USING btree (policy_id, policy_version);

CREATE INDEX recovery_receipts_principal_idx ON public.recovery_receipts USING btree (principal_id);

CREATE INDEX recovery_session_principal_idx ON public.recovery_session USING btree (principal_id);

CREATE INDEX sessions_actor_device_idx ON public.sessions USING btree (actor, device_id, expires_at) WHERE (revoked_at IS NULL);

CREATE INDEX space_members_actor_idx ON public.space_members USING btree (actor, membership, realm_id);

CREATE INDEX space_state_events_lookup_idx ON public.space_state_events USING btree (realm_id, event_type, subject, created_at);

CREATE INDEX spaces_discoverability_updated_idx ON public.spaces USING btree (discoverability, updated_at, id);

CREATE INDEX spaces_history_sharing_policy_digest_idx ON public.spaces USING btree (history_sharing_policy_digest) WHERE (history_sharing_policy_digest IS NOT NULL);

CREATE INDEX spaces_history_visibility_updated_idx ON public.spaces USING btree (history_visibility, updated_at, id);

CREATE INDEX spaces_preview_policy_digest_idx ON public.spaces USING btree (preview_policy_digest) WHERE (preview_policy_digest IS NOT NULL);

CREATE INDEX sync_cursor_handles_expiry_idx ON public.sync_cursor_handles USING btree (expires_at_ms);

CREATE INDEX sync_cursor_handles_stream_idx ON public.sync_cursor_handles USING btree (principal_id, device_id, filter_digest);

CREATE INDEX webrtc_sessions_expires_idx ON public.webrtc_sessions USING btree (expires_at);

CREATE INDEX webrtc_sessions_space_idx ON public.webrtc_sessions USING btree (realm_id);

CREATE INDEX webvh_documents_expires_at_idx ON public.webvh_documents USING btree (expires_at);

CREATE INDEX webvh_log_events_did_seq_idx ON public.webvh_log_events USING btree (did, seq);

ALTER TABLE ONLY public.agent_grant
    ADD CONSTRAINT agent_grant_agent_principal_id_fkey FOREIGN KEY (agent_principal_id) REFERENCES public.agent_principal(agent_principal_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.agent_key
    ADD CONSTRAINT agent_key_agent_principal_id_fkey FOREIGN KEY (agent_principal_id) REFERENCES public.agent_principal(agent_principal_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.agent_participation
    ADD CONSTRAINT agent_participation_agent_principal_id_fkey FOREIGN KEY (agent_principal_id) REFERENCES public.agent_principal(agent_principal_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.agent_session
    ADD CONSTRAINT agent_session_agent_principal_id_fkey FOREIGN KEY (agent_principal_id) REFERENCES public.agent_principal(agent_principal_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.federation_outbox_dead_letter
    ADD CONSTRAINT federation_outbox_dead_letter_outbox_id_fkey FOREIGN KEY (outbox_id) REFERENCES public.federation_outbox(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.pending_agent_drafts
    ADD CONSTRAINT pending_agent_drafts_agent_principal_id_fkey FOREIGN KEY (agent_principal_id) REFERENCES public.agent_principal(agent_principal_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.projection_circle_members
    ADD CONSTRAINT projection_circle_members_circle_id_fkey FOREIGN KEY (circle_id) REFERENCES public.projection_circles(circle_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.recovery_policies
    ADD CONSTRAINT recovery_policies_supersedes_fkey FOREIGN KEY (supersedes) REFERENCES public.recovery_policies(policy_id);

ALTER TABLE ONLY public.recovery_receipts
    ADD CONSTRAINT recovery_receipts_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.recovery_policies(policy_id);

