// Explicit runtime cache slots. Canonical SDK metadata validates these declarations.
// A cache acknowledgment never substitutes for the accepting durable writer.
const EFFECT_MANIFEST: &[EffectRegistration] = &[
    EffectRegistration {
        kind: "ak.account_data.set",
        owner: EventEffectOwnership::PrivateServiceEffect,
        scope: EventWireScope::ActorPrivateEvent,
        reducer_input: false,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.agent.action_approve",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_agent_action_approve_dispatch),
    },
    EffectRegistration {
        kind: "ak.agent.action_reject",
        owner: EventEffectOwnership::PrivateServiceEffect,
        scope: EventWireScope::ActorPrivateEvent,
        reducer_input: false,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.agent.action_request",
        owner: EventEffectOwnership::PrivateServiceEffect,
        scope: EventWireScope::ActorPrivateEvent,
        reducer_input: false,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.agent.draft.propose",
        owner: EventEffectOwnership::PrivateServiceEffect,
        scope: EventWireScope::ActorPrivateEvent,
        reducer_input: false,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.agent.interaction.set",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_durable_fact_dispatch),
    },
    EffectRegistration {
        kind: "ak.agent.key.authorize",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_agent_key_authorize_dispatch),
    },
    EffectRegistration {
        kind: "ak.agent.key.revoke",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_agent_key_revoke_dispatch),
    },
    EffectRegistration {
        kind: "ak.agent.provision",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.agent.sidecar.exchange.control",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_sidecar_exchange_control_dispatch),
    },
    EffectRegistration {
        kind: "ak.applet.bridge_error",
        owner: EventEffectOwnership::DurableFactNoCurrentProjection,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_durable_fact_dispatch),
    },
    EffectRegistration {
        kind: "ak.applet.discovery",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_applet_discovery_dispatch),
    },
    EffectRegistration {
        kind: "ak.applet.managed_actor.provision",
        owner: EventEffectOwnership::DurableFactNoCurrentProjection,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_durable_fact_dispatch),
    },
    EffectRegistration {
        kind: "ak.applet.registration",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_applet_registration_dispatch),
    },
    EffectRegistration {
        kind: "ak.audit.accessed",
        owner: EventEffectOwnership::DurableFactNoCurrentProjection,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_durable_fact_dispatch),
    },
    EffectRegistration {
        kind: "ak.audit.erasure_receipt",
        owner: EventEffectOwnership::DurableFactNoCurrentProjection,
        scope: EventWireScope::DurableEvent,
        reducer_input: false,
        slot: CacheSlot::Service(apply_durable_fact_dispatch),
    },
    EffectRegistration {
        kind: "ak.call.create",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_call_create_dispatch),
    },
    EffectRegistration {
        kind: "ak.call.recording.start",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_call_recording_start_dispatch),
    },
    EffectRegistration {
        kind: "ak.call.state",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_call_state_dispatch),
    },
    EffectRegistration {
        kind: "ak.capability.grant",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.capability.relinquish",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.capability.revoke",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.circle.archive",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_circle_archive_dispatch),
    },
    EffectRegistration {
        kind: "ak.circle.create",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_circle_create_dispatch),
    },
    EffectRegistration {
        kind: "ak.circle.history_access",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_circle_history_access_dispatch),
    },
    EffectRegistration {
        kind: "ak.circle.member.state",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_circle_member_state_dispatch),
    },
    EffectRegistration {
        kind: "ak.circle.restore",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_circle_restore_dispatch),
    },
    EffectRegistration {
        kind: "ak.circle.tombstone",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_circle_tombstone_dispatch),
    },
    EffectRegistration {
        kind: "ak.circle.update",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_circle_update_dispatch),
    },
    EffectRegistration {
        kind: "ak.consent.grant",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.consent.revoke",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.contact.accepted",
        owner: EventEffectOwnership::PrivateServiceEffect,
        scope: EventWireScope::DurableEvent,
        reducer_input: false,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.contact.rejected",
        owner: EventEffectOwnership::PrivateServiceEffect,
        scope: EventWireScope::DurableEvent,
        reducer_input: false,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.contact.requested",
        owner: EventEffectOwnership::PrivateServiceEffect,
        scope: EventWireScope::DurableEvent,
        reducer_input: false,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.contact.scope.update",
        owner: EventEffectOwnership::PrivateServiceEffect,
        scope: EventWireScope::DurableEvent,
        reducer_input: false,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.contact.tombstone",
        owner: EventEffectOwnership::PrivateServiceEffect,
        scope: EventWireScope::DurableEvent,
        reducer_input: false,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.device.authorize",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.device.push_route",
        owner: EventEffectOwnership::PrivateServiceEffect,
        scope: EventWireScope::ActorPrivateEvent,
        reducer_input: false,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.device.reanchor",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.device.revoke",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.direct_conversation.bound",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.identity.accountability_grant",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.identity.resolution.update",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_identity_resolution_update_dispatch),
    },
    EffectRegistration {
        kind: "ak.invite.accept",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.invite.cancel",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.invite.claim",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_invite_claim_dispatch),
    },
    EffectRegistration {
        kind: "ak.invite.create",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.invite.revoke",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.invite.third_party",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_invite_third_party_dispatch),
    },
    EffectRegistration {
        kind: "ak.key_backup.active_series",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.member.identity.update",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_member_identity_update_dispatch),
    },
    EffectRegistration {
        kind: "ak.member.state",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_membership_dispatch),
    },
    EffectRegistration {
        kind: "ak.message.create",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_message_dispatch),
    },
    EffectRegistration {
        kind: "ak.message.redact",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_redaction_dispatch),
    },
    EffectRegistration {
        kind: "ak.message.revise",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_message_revise_dispatch),
    },
    EffectRegistration {
        kind: "ak.mimi.room_binding",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.mls.commit",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_durable_fact_dispatch),
    },
    EffectRegistration {
        kind: "ak.mls.genesis",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_durable_fact_dispatch),
    },
    EffectRegistration {
        kind: "ak.moderation.decision",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_moderation_decision_dispatch),
    },
    EffectRegistration {
        kind: "ak.moderation.decision.lift",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_moderation_decision_lift_dispatch),
    },
    EffectRegistration {
        kind: "ak.moderation.franking_proof",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.morph.archive",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_morph_archive_dispatch),
    },
    EffectRegistration {
        kind: "ak.morph.create",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_morph_create_dispatch),
    },
    EffectRegistration {
        kind: "ak.morph.restore",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_morph_restore_dispatch),
    },
    EffectRegistration {
        kind: "ak.morph.stage.set",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_morph_stage_set_dispatch),
    },
    EffectRegistration {
        kind: "ak.morph.update",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_morph_update_dispatch),
    },
    EffectRegistration {
        kind: "ak.organization.moderation_policy",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.pin.add",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_pin_dispatch),
    },
    EffectRegistration {
        kind: "ak.pin.remove",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_pin_dispatch),
    },
    EffectRegistration {
        kind: "ak.pin.reorder",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_pin_dispatch),
    },
    EffectRegistration {
        kind: "ak.policy.action",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_policy_action_dispatch),
    },
    EffectRegistration {
        kind: "ak.policy.set",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_policy_set_dispatch),
    },
    EffectRegistration {
        kind: "ak.profile.create",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.profile.realm_override",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.profile.update",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.reaction.add",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_reaction_add_dispatch),
    },
    EffectRegistration {
        kind: "ak.reaction.remove",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_reaction_remove_dispatch),
    },
    EffectRegistration {
        kind: "ak.read_cursor.advance",
        owner: EventEffectOwnership::PrivateServiceEffect,
        scope: EventWireScope::ActorPrivateEvent,
        reducer_input: false,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.realm.alias",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_bootstrap_facet_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.archive",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_archive_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.asset_privacy_policy",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.realm.authority.reset",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_authority_reset_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.create",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_create_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.destroy",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_destroy_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.discovery",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_bootstrap_facet_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.freeze",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_freeze_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.governance_station.change",
        owner: EventEffectOwnership::AuthorityCommitEffect,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_governance_station_change_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.history_access",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_history_access_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.join_rule",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_bootstrap_facet_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.link",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_link_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.media_service",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_media_service_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.organization",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_organization_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.owner.transfer",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_owner_transfer_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.plaintext_visible_services",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_bootstrap_facet_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.policy_bundle",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_policy_bundle_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.preview_policy",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_preview_policy_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.profile",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_profile_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.read_receipt_policy",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_read_receipt_policy_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.restore",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_restore_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.schema",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.realm.search_policy",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_search_policy_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.set_default_strand",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_set_default_strand_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.tombstone",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_tombstone_dispatch),
    },
    EffectRegistration {
        kind: "ak.realm.unfreeze",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_realm_unfreeze_dispatch),
    },
    EffectRegistration {
        kind: "ak.redaction",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_redaction_dispatch),
    },
    EffectRegistration {
        kind: "ak.relation.create",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_relation_create_dispatch),
    },
    EffectRegistration {
        kind: "ak.relation.tombstone",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_relation_delete_dispatch),
    },
    EffectRegistration {
        kind: "ak.relation.update",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_relation_update_dispatch),
    },
    EffectRegistration {
        kind: "ak.rsvp.set",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_rsvp_set_dispatch),
    },
    EffectRegistration {
        kind: "ak.schema.define",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.self.agent.deactivate",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_agent_deactivate_dispatch),
    },
    EffectRegistration {
        kind: "ak.self.agent.pause",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_agent_pause_dispatch),
    },
    EffectRegistration {
        kind: "ak.self.agent.resume",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_agent_resume_dispatch),
    },
    EffectRegistration {
        kind: "ak.self.moderation.report",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_durable_fact_dispatch),
    },
    EffectRegistration {
        kind: "ak.sidecar.context.attach",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_sidecar_context_attach_dispatch),
    },
    EffectRegistration {
        kind: "ak.sidecar.create",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_sidecar_create_dispatch),
    },
    EffectRegistration {
        kind: "ak.space.archive",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_space_container_archive_dispatch),
    },
    EffectRegistration {
        kind: "ak.space.create",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_space_container_create_dispatch),
    },
    EffectRegistration {
        kind: "ak.space.parent",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_space_container_parent_dispatch),
    },
    EffectRegistration {
        kind: "ak.space.restore",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_space_container_restore_dispatch),
    },
    EffectRegistration {
        kind: "ak.space.tombstone",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_space_container_tombstone_dispatch),
    },
    EffectRegistration {
        kind: "ak.space.update",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_space_container_update_dispatch),
    },
    EffectRegistration {
        kind: "ak.strand.archive",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_strand_archive_dispatch),
    },
    EffectRegistration {
        kind: "ak.strand.create",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_strand_create_dispatch),
    },
    EffectRegistration {
        kind: "ak.strand.move",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_strand_position_touch_dispatch),
    },
    EffectRegistration {
        kind: "ak.strand.reorder",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_strand_position_touch_dispatch),
    },
    EffectRegistration {
        kind: "ak.strand.restore",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_strand_restore_dispatch),
    },
    EffectRegistration {
        kind: "ak.strand.stage.set",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_strand_stage_set_dispatch),
    },
    EffectRegistration {
        kind: "ak.strand.tracks.update",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_strand_track_touch_dispatch),
    },
    EffectRegistration {
        kind: "ak.strand.update",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_strand_update_dispatch),
    },
    EffectRegistration {
        kind: "ak.strand.watch.set",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::Shared(apply_durable_fact_dispatch),
    },
    EffectRegistration {
        kind: "ak.view.create",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.view.reconcile",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
    EffectRegistration {
        kind: "ak.view.update",
        owner: EventEffectOwnership::TypedResultWriter,
        scope: EventWireScope::DurableEvent,
        reducer_input: true,
        slot: CacheSlot::FailClosed,
    },
];
