-- CKP-0007 (spec b7d35be / floor 2b0d70d) — drop the legacy
-- `discussion_realm_ref` cross-Realm discussion routing column from any
-- projection table that may have carried it on prior deployments. The
-- column was never landed in soland's main-line migration set (Flow
-- projection state lived purely in `ProjectionState::flow_discussion_realms`
-- in-memory and was rehydrated from the canonical Event log), but
-- defensively running `DROP COLUMN IF EXISTS` keeps any
-- ad-hoc / vendor-deployed schema in sync with the post-Circle world.
--
-- The replacement field is `scope_circle_id` on Flow / Space / Morph
-- objects (see the matching `add_scope_circle_id` migration).
ALTER TABLE projection_flows DROP COLUMN IF EXISTS discussion_realm_ref;
