[package]
name = "soland-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "Shared Soland admin and server support types."

[features]
default = []
salvo = ["dep:salvo"]

[dependencies]
cokret-core = {workspace = true,default-features = false}
salvo = {workspace = true,optional = true,features = ["oapi"]}
serde = {workspace = true,features = ["derive"]}
serde_json = {workspace = true}
