name: Typos

on:
  pull_request:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  typos:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout soland
        uses: actions/checkout@v6

      - name: Check spelling
        uses: crate-ci/typos@v1.45.2
