DROP TABLE IF EXISTS mls_welcome_deliveries CASCADE;
DROP TABLE IF EXISTS realm_state_snapshot_window_reservations;
DROP TABLE IF EXISTS realm_commit_event_kinds;
DROP TABLE IF EXISTS realm_state_snapshot_issuances;
DROP TABLE IF EXISTS forwarded_producer_device_evidence;
DROP TABLE IF EXISTS account_device_signer_evidence;
DROP TABLE IF EXISTS realm_state_snapshots CASCADE;
DROP TABLE IF EXISTS realm_authority_handoffs CASCADE;
DROP TABLE IF EXISTS agent_selector_claim_current_results;
DROP TABLE IF EXISTS agent_pcr_genesis_declaration_current_results;
DROP TABLE IF EXISTS agent_provisioning_current_results;
DROP TABLE IF EXISTS identity_accountability_current_results;
DROP TABLE IF EXISTS actor_profile_result_versions;
DROP TABLE IF EXISTS actor_profile_current_results;
DROP TABLE IF EXISTS key_backup_active_series_current_results;
DROP TABLE IF EXISTS pcr_device_revocation_proposals;
DROP TABLE IF EXISTS pcr_device_authorization_current_results;
DROP TABLE IF EXISTS pcr_device_generation_current_results;
DROP TABLE IF EXISTS replica_stream_anchors CASCADE;
DROP TABLE IF EXISTS realm_commits CASCADE;
DROP TABLE IF EXISTS realm_authorities CASCADE;
DROP TABLE IF EXISTS state_seal_signing_positions;
DROP TABLE IF EXISTS realm_join_downloads;
DROP TABLE IF EXISTS key_backup_unlock_attempt_windows;
DROP TRIGGER IF EXISTS preserve_agent_pairing_receipt ON agent_principals;
DROP FUNCTION IF EXISTS preserve_agent_pairing_receipt();
DROP TABLE IF EXISTS agent_pairing_receipts;
DROP TABLE IF EXISTS key_backup_unlock_entries;
DROP TABLE IF EXISTS key_backup_unlock_authorities;
DROP TABLE IF EXISTS governance_current_ready;
DROP TABLE IF EXISTS current_selector_origins;
DROP TABLE IF EXISTS capability_quota_consumptions;
DROP TABLE IF EXISTS capability_quota_buckets;
DROP TABLE IF EXISTS capability_quota_counters;
DROP TABLE IF EXISTS capability_grant_current_results;
DROP TABLE IF EXISTS member_state_current_results;
DROP TABLE IF EXISTS realm_bootstrap_current_results;
DROP TABLE IF EXISTS agent_key_current_results;
DROP TABLE IF EXISTS agent_status_current_results;
DROP TABLE IF EXISTS pcr_genesis_units;
DROP TABLE IF EXISTS ordinary_realm_bootstrap_units;
DROP TABLE IF EXISTS realm_link_current_results;
DROP TABLE IF EXISTS realm_policy_bundle_current_results;
DROP TABLE IF EXISTS realm_authority_root_current_results;
DROP TABLE IF EXISTS relation_current_results;
DROP TABLE IF EXISTS current_result_versions;
DROP TABLE IF EXISTS current_result_heads;
DROP FUNCTION IF EXISTS enforce_canonical_event_immutability() CASCADE;
DROP FUNCTION IF EXISTS record_realm_commit_event_kind() CASCADE;
DROP FUNCTION IF EXISTS invalidate_account_device_create() CASCADE;
DROP FUNCTION IF EXISTS account_data_source_current(TEXT,TEXT) CASCADE;
DROP FUNCTION IF EXISTS bind_device_inventory_station() CASCADE;
DROP FUNCTION IF EXISTS account_device_interest_visible(TEXT,TEXT) CASCADE;
DROP FUNCTION IF EXISTS immutable_device_inventory_station() CASCADE;
DROP FUNCTION IF EXISTS current_device_inventory_station() CASCADE;
DROP FUNCTION IF EXISTS project_account_global_membership() CASCADE;
DROP PROCEDURE IF EXISTS publish_pcr_device_list_change(TEXT) CASCADE;
DROP FUNCTION IF EXISTS refresh_account_device_interest(TEXT,TEXT) CASCADE;
DROP FUNCTION IF EXISTS project_account_global_cas() CASCADE;
DROP FUNCTION IF EXISTS project_account_global_notification() CASCADE;
DROP FUNCTION IF EXISTS project_agent_draft_pending_intent() CASCADE;
DROP FUNCTION IF EXISTS reject_agent_draft_pending_intent_delete() CASCADE;
DROP FUNCTION IF EXISTS project_notification_source_state() CASCADE;
DROP FUNCTION IF EXISTS project_notification_membership_visibility() CASCADE;
DROP FUNCTION IF EXISTS project_account_global_value(TEXT,TEXT,TEXT,JSONB,BOOLEAN) CASCADE;
DROP TABLE IF EXISTS account_global_versions;
DROP TABLE IF EXISTS account_global_channel_clocks;
DROP TABLE IF EXISTS account_sync_cursor_retention;
DROP TABLE IF EXISTS account_sync_snapshot_reservations;
DROP TABLE IF EXISTS account_sync_retention;
DROP TABLE IF EXISTS account_global_clock;
DROP TABLE IF EXISTS account_summary_versions;
DROP TABLE IF EXISTS account_summary_current;
DROP TABLE IF EXISTS account_summary_members;
DROP TABLE IF EXISTS account_summary_clock;
-- Squashed initial migration. This drops all tables. Only use in development.
DROP FUNCTION IF EXISTS project_agent_runtime_approval_notification() CASCADE;
DROP FUNCTION IF EXISTS reject_organization_registration_outcome_mutation() CASCADE;
DROP FUNCTION IF EXISTS reject_state_seal_identity_mutation() CASCADE;
DROP TABLE IF EXISTS server_settings CASCADE;
DROP TABLE IF EXISTS event_notification_relay CASCADE;
DROP TABLE IF EXISTS account_data_changes CASCADE;
DROP TABLE IF EXISTS account_data_change_retention CASCADE;
DROP TABLE IF EXISTS agent_action_rejections CASCADE;
DROP TABLE IF EXISTS agent_action_requests CASCADE;
DROP TABLE IF EXISTS device_push_routes CASCADE;
DROP TABLE IF EXISTS actor_private_events CASCADE;
DROP FUNCTION IF EXISTS public.reject_actor_private_event_mutation() CASCADE;
DROP TABLE IF EXISTS read_cursor_winners CASCADE;
DROP TABLE IF EXISTS agent_draft_pending_intents CASCADE;
DROP TABLE IF EXISTS account_datas CASCADE;
DROP TABLE IF EXISTS account_authoring_continuity CASCADE;
DROP TABLE IF EXISTS account_localparts CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS account_lifecycle CASCADE;
DROP TABLE IF EXISTS account_status_replica_records CASCADE;
DROP TABLE IF EXISTS account_status_propagation_targets CASCADE;
DROP TABLE IF EXISTS account_status_propagations CASCADE;
DROP TABLE IF EXISTS account_status_affected_services CASCADE;
DROP TABLE IF EXISTS handle_releases CASCADE;
DROP TABLE IF EXISTS agent_participation CASCADE;
DROP TABLE IF EXISTS agent_participation_ceiling CASCADE;
DROP TABLE IF EXISTS agent_sidecar_contexts CASCADE;
DROP TABLE IF EXISTS agent_sidecars CASCADE;
DROP TABLE IF EXISTS agent_runtime_messages CASCADE;
DROP TABLE IF EXISTS agent_principals CASCADE;
DROP TABLE IF EXISTS agent_membership_cleanup_intents CASCADE;
DROP TABLE IF EXISTS managed_authority_claims CASCADE;
DROP TABLE IF EXISTS applet_namespace_claims CASCADE;
DROP TABLE IF EXISTS applet_installations CASCADE;
DROP TABLE IF EXISTS applet_managed_identities CASCADE;
DROP TABLE IF EXISTS applet_transactions CASCADE;
DROP TABLE IF EXISTS applet_authoring_previews CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS blobs CASCADE;
DROP TABLE IF EXISTS publication_evidence CASCADE;
DROP TABLE IF EXISTS signal_relay CASCADE;
DROP TABLE IF EXISTS signal_relay_position CASCADE;
DROP TABLE IF EXISTS signal_relay_watermark CASCADE;
DROP TABLE IF EXISTS membership_compensation_evidence CASCADE;
DROP TABLE IF EXISTS authority_forward_attempts CASCADE;
DROP TABLE IF EXISTS canonical_events CASCADE;
DROP TABLE IF EXISTS canonical_realms CASCADE;
DROP TABLE IF EXISTS event_collision_variants CASCADE;
DROP TABLE IF EXISTS identity_anchor_account_slots CASCADE;
DROP TABLE IF EXISTS pending_rhrk_acquisitions CASCADE;
DROP SEQUENCE IF EXISTS history_rhrk_archive_sequence CASCADE;
DROP TABLE IF EXISTS history_traversal_pins CASCADE;
DROP TABLE IF EXISTS history_traversal_retained_objects CASCADE;
DROP TABLE IF EXISTS history_traversal_retentions CASCADE;
DROP TABLE IF EXISTS governance_dependency_edges CASCADE;
DROP TABLE IF EXISTS agent_accepted_seal_signers CASCADE;
DROP TABLE IF EXISTS seal_prepare_signing_fences CASCADE;
DROP TABLE IF EXISTS governance_unscoped_signer_evidence CASCADE;
DROP TABLE IF EXISTS governance_dependency_objects CASCADE;
DROP TABLE IF EXISTS state_seal_control_events CASCADE;
DROP TABLE IF EXISTS state_seal_effective_checkpoints CASCADE;
DROP TABLE IF EXISTS state_seal_quarantine_realms CASCADE;
DROP TABLE IF EXISTS state_seal_collision_variants CASCADE;
DROP TABLE IF EXISTS state_seal_quarantine CASCADE;
DROP TABLE IF EXISTS state_control_seal_repair_cursor CASCADE;
DROP TABLE IF EXISTS state_control_seal_schedule CASCADE;
DROP TABLE IF EXISTS state_control_events CASCADE;
DROP FUNCTION IF EXISTS update_control_event_pending();
DROP FUNCTION IF EXISTS complete_control_event_pending();
DROP TABLE IF EXISTS state_seals CASCADE;
DROP TABLE IF EXISTS state_seal_signing_leases CASCADE;
DROP TABLE IF EXISTS state_cell_ops CASCADE;
DROP TABLE IF EXISTS consent_grants CASCADE;
DROP TABLE IF EXISTS mimi_consent_correlations CASCADE;
DROP TABLE IF EXISTS contact_completion_intents CASCADE;
DROP TABLE IF EXISTS contact_verified_mirrors CASCADE;
DROP TABLE IF EXISTS contacts CASCADE;
DROP TABLE IF EXISTS device_revocation_cleanup_intents CASCADE;
DROP TABLE IF EXISTS device_revocation_gate_receipts CASCADE;
DROP TABLE IF EXISTS device_revocation_targets CASCADE;
DROP TABLE IF EXISTS device_revocation_linearization_heads CASCADE;
DROP TABLE IF EXISTS device_message_ack_tokens CASCADE;
DROP TABLE IF EXISTS agent_recipient_delivery_ack_tokens CASCADE;
DROP TABLE IF EXISTS device_message_lost_watermarks CASCADE;
DROP TABLE IF EXISTS device_message_idempotency CASCADE;
DROP TABLE IF EXISTS device_message_txns CASCADE;
DROP TABLE IF EXISTS device_messages CASCADE;
DROP SEQUENCE IF EXISTS recipient_delivery_position_seq CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP VIEW IF EXISTS committed_events CASCADE;
DROP TABLE IF EXISTS federation_fork_normalization CASCADE;
DROP TABLE IF EXISTS federation_frontier_resolution CASCADE;
DROP TABLE IF EXISTS federation_frontier_reduction_checkpoint CASCADE;
DROP TABLE IF EXISTS federation_frontier_confirmed_evidence CASCADE;
DROP TABLE IF EXISTS federation_frontier_exchange CASCADE;
DROP TABLE IF EXISTS federation_operations CASCADE;
DROP TABLE IF EXISTS federation_outbox CASCADE;
DROP TABLE IF EXISTS event_federation_outbox CASCADE;
DROP TABLE IF EXISTS federation_outbox_dead_letter CASCADE;
DROP TABLE IF EXISTS invite_receive_policies CASCADE;
DROP TABLE IF EXISTS invite_new_source_ledgers CASCADE;
DROP TABLE IF EXISTS invite_locators CASCADE;
DROP TABLE IF EXISTS key_backup_delete_challenges CASCADE;
DROP TABLE IF EXISTS key_backups CASCADE;
DROP FUNCTION IF EXISTS key_backup_list_metadata(jsonb) CASCADE;
DROP TABLE IF EXISTS mls_key_packages CASCADE;
DROP TABLE IF EXISTS keypackage_claim_welcome_bindings CASCADE;
DROP TABLE IF EXISTS peer_keypackage_claims CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;
DROP TABLE IF EXISTS organization_registration_states CASCADE;
DROP TABLE IF EXISTS organization_registration_challenges CASCADE;
DROP TABLE IF EXISTS organization_registration_outcomes CASCADE;
DROP TABLE IF EXISTS realm_organizations CASCADE;
DROP TABLE IF EXISTS soland_schema_contract CASCADE;
DROP TABLE IF EXISTS realm_owning_organizations CASCADE;
DROP TABLE IF EXISTS retention_policies CASCADE;
DROP TABLE IF EXISTS retention_tombstones CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP SEQUENCE IF EXISTS notification_projection_position_seq CASCADE;
DROP TABLE IF EXISTS policy_documents CASCADE;
DROP TABLE IF EXISTS projection_circle_members CASCADE;
DROP TABLE IF EXISTS projection_circles CASCADE;
DROP TABLE IF EXISTS projection_events CASCADE;
DROP TABLE IF EXISTS projection_strand_watches CASCADE;
DROP TABLE IF EXISTS projection_strands CASCADE;
DROP TABLE IF EXISTS strand_current_results CASCADE;
DROP TABLE IF EXISTS mls_group_current_results CASCADE;
DROP TABLE IF EXISTS message_revision_current_results CASCADE;
DROP TABLE IF EXISTS object_redaction_current_results CASCADE;
DROP TABLE IF EXISTS moderation_state_current_results CASCADE;
DROP TABLE IF EXISTS moderation_report_current_results CASCADE;
DROP TABLE IF EXISTS realm_set_default_strand_current_results CASCADE;
DROP TABLE IF EXISTS invite_lifecycle_current_results CASCADE;
DROP TABLE IF EXISTS invite_third_party_create_index CASCADE;
DROP TABLE IF EXISTS invite_live_target_current_results CASCADE;
DROP TABLE IF EXISTS invite_directed_invitee_current_results CASCADE;
DROP TABLE IF EXISTS projection_morphs CASCADE;
DROP TABLE IF EXISTS projection_spaces CASCADE;
DROP TABLE IF EXISTS push_devices CASCADE;
DROP TABLE IF EXISTS push_registration_handoff_intents CASCADE;
DROP TABLE IF EXISTS push_hard_logout_journal CASCADE;
DROP TABLE IF EXISTS recovery_policies CASCADE;
DROP TABLE IF EXISTS security_transaction_step_attempts CASCADE;
DROP TABLE IF EXISTS security_transaction_step_outcomes CASCADE;
DROP TABLE IF EXISTS security_transaction_backup_erase_progress CASCADE;
DROP TABLE IF EXISTS security_transactions CASCADE;
DROP TABLE IF EXISTS recovery_sessions CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS sync_cursor_handles CASCADE;
DROP TABLE IF EXISTS sync_cursor_revocations CASCADE;
DROP TABLE IF EXISTS websocket_auth_challenges CASCADE;
DROP TABLE IF EXISTS websocket_auth_replay_ledger CASCADE;
DROP TABLE IF EXISTS moderation_franking_replay_nonces CASCADE;
DROP INDEX IF EXISTS canonical_events_franking_target_idx;
DROP INDEX IF EXISTS canonical_events_realm_actor_position_idx;
DROP TABLE IF EXISTS idempotency_keys CASCADE;
DROP TABLE IF EXISTS service_identity_registrations CASCADE;
DROP TABLE IF EXISTS service_route_cache CASCADE;
DROP TABLE IF EXISTS service_resolution_fork_quarantine CASCADE;
DROP TABLE IF EXISTS service_method_states CASCADE;
DROP TABLE IF EXISTS principal_resolution_events CASCADE;
DROP TABLE IF EXISTS principal_resolutions CASCADE;
DROP TABLE IF EXISTS service_identity CASCADE;
DROP TABLE IF EXISTS webvh_documents CASCADE;
DROP TABLE IF EXISTS webvh_log_events CASCADE;
DROP TABLE IF EXISTS public.direct_conversation_binding_current_results;
DROP TABLE IF EXISTS public.direct_conversation_group_states;
DROP TABLE IF EXISTS public.direct_conversation_founding_slots;
DROP TABLE IF EXISTS public.realm_meta CASCADE;
DROP TABLE IF EXISTS public.messages CASCADE;
DROP TABLE IF EXISTS public.device_keys CASCADE;
DROP TABLE IF EXISTS public.one_time_keys CASCADE;
DROP TABLE IF EXISTS public.member_identity_events CASCADE;
DROP TABLE IF EXISTS public.member_identity_handle_claims CASCADE;
DROP TABLE IF EXISTS public.history_key_response_tombstones;
DROP TABLE IF EXISTS public.history_key_response_dispositions;
DROP TABLE IF EXISTS public.history_key_response_ack_tokens;
DROP TABLE IF EXISTS public.history_key_responses;
DROP TABLE IF EXISTS public.history_key_response_streams;
DROP TABLE IF EXISTS public.history_key_requests;

DROP TABLE IF EXISTS device_inventory_station CASCADE;
