-- Squashed initial migration (soland).
--
-- Event references in this file appear as `<role>_event_id` and
-- `<role>_event_ref`. That is not drift: the suffix is normative and comes from
-- `arkret-spec zh/models/common-fields.md` 2.1. `_id` names the Event as the
-- artifact the row is about -- an operation target, audit target or selector
-- target (`retention_tombstones.event_id`, `moderation_reports.target_event_id`,
-- `mls_key_packages.device_authorize_event_id`). `_ref` names an Event used as
-- causal, finality or proof material (`contacts.request_event_ref`,
-- `agent_sidecar_contexts.predecessor_event_ref`,
-- `agent_principals.authorized_event_ref`). A column MUST carry the same name
-- as the spec field it materializes.
--
-- The suffix says nothing about storage type: both forms hold the same
-- 33-octet token as `canonical_events.id`, in `bytea`. An Event reference is
-- only an `event_pk` foreign key when the row requires that Event to be
-- admitted here and to stay; otherwise the identity is stored directly, so
-- peer-authored and erased Events remain expressible.
-- Final schema as of 2026-06-10, consolidated from the previous migration chain
-- (generated by applying all historical migrations and dumping the resulting schema).

-- Clean-break fence for the suite-tagged full-digest Event/Realm identity
-- layout.  Startup verifies this singleton after Diesel migrations run, so a
-- database that recorded the old squashed migration version but still has the
-- UUID schema cannot be opened silently.
CREATE TABLE public.soland_schema_contract (
    singleton boolean PRIMARY KEY DEFAULT true,
    contract_version text NOT NULL,
    CONSTRAINT soland_schema_contract_singleton_check CHECK (singleton),
    CONSTRAINT soland_schema_contract_version_check CHECK (
        contract_version = 'event-realm-full-digest-v1'
    )
);

INSERT INTO public.soland_schema_contract (singleton, contract_version)
VALUES (true, 'event-realm-full-digest-v1');

-- Realm wire identities are content/subject-derived protocol values, not
-- database primary keys.  Intern them once and use the monotonic `pk` for
-- physical joins, exactly as canonical Events use `canonical_events.pk`.
CREATE TABLE public.canonical_realms (
    pk bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id bytea NOT NULL,
    derivation_class smallint NOT NULL,
    digest_suite smallint NOT NULL,
    digest bytea NOT NULL,
    wire_id text NOT NULL,
    CONSTRAINT canonical_realms_id_key UNIQUE (id),
    CONSTRAINT canonical_realms_identity_key UNIQUE (derivation_class, digest_suite, digest),
    CONSTRAINT canonical_realms_wire_id_key UNIQUE (wire_id),
    CONSTRAINT canonical_realms_id_length_check CHECK (octet_length(id) = 33),
    CONSTRAINT canonical_realms_digest_length_check CHECK (octet_length(digest) = 32),
    CONSTRAINT canonical_realms_derivation_class_check CHECK (derivation_class IN (0, 1)),
    CONSTRAINT canonical_realms_digest_suite_check CHECK (digest_suite = 1),
    CONSTRAINT canonical_realms_principal_suite_check CHECK (derivation_class <> 1 OR digest_suite = 1),
    CONSTRAINT canonical_realms_id_parts_check CHECK (
        get_byte(id, 0) = ((derivation_class << 4) | digest_suite)
        AND substring(id FROM 2) = digest
    ),
    CONSTRAINT canonical_realms_wire_id_check CHECK (wire_id ~ '^ak:realm:[A-Za-z0-9_-]{44}$')
);

CREATE TABLE public.account_datas (
    id uuid PRIMARY KEY,
    actor_id text NOT NULL,
    account_data_key text NOT NULL,
    payload jsonb NOT NULL,
    revision bigint NOT NULL DEFAULT 1,
    tombstone boolean NOT NULL DEFAULT false,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT account_datas_revision_positive CHECK (revision >= 1)
);

ALTER TABLE ONLY public.account_datas
    ADD CONSTRAINT account_datas_actor_data_type_key UNIQUE (actor_id, account_data_key);

CREATE TABLE public.accounts (
    id uuid PRIMARY KEY,
    principal_id text NOT NULL,
    display_name text,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    disabled_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_principal_id_key UNIQUE (principal_id);

CREATE TABLE public.account_localparts (
    id uuid PRIMARY KEY,
    account_id uuid NOT NULL,
    localpart text NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.account_localparts
    ADD CONSTRAINT account_localparts_localpart_key UNIQUE (localpart);

CREATE INDEX account_localparts_account_idx ON public.account_localparts USING btree (account_id);

CREATE UNIQUE INDEX account_localparts_primary_account_idx ON public.account_localparts USING btree (account_id) WHERE (is_primary);

ALTER TABLE ONLY public.account_localparts
    ADD CONSTRAINT account_localparts_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;

CREATE TABLE public.account_lifecycle (
    principal_id text PRIMARY KEY,
    state text NOT NULL,
    reason text,
    changed_by text,
    changed_at timestamp with time zone NOT NULL,
    CONSTRAINT account_lifecycle_state_check CHECK ((state = ANY (ARRAY['active'::text, 'locked'::text, 'suspended'::text, 'deactivated'::text, 'erasure_pending'::text])))
);

CREATE INDEX account_lifecycle_state_idx ON public.account_lifecycle USING btree (state, changed_at);

CREATE TABLE public.handle_releases (
    localpart text PRIMARY KEY,
    released_at timestamp with time zone NOT NULL
);

CREATE TABLE public.agent_keys (
    id uuid PRIMARY KEY,
    agent_id text NOT NULL,
    verification_method text NOT NULL,
    state text DEFAULT 'authorized'::text NOT NULL,
    authorized_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    revocation_reason text,
    CONSTRAINT agent_keys_state_check CHECK ((state = ANY (ARRAY['authorized'::text, 'revoked'::text])))
);

CREATE INDEX agent_keys_principal_idx ON public.agent_keys USING btree (agent_id);

CREATE INDEX agent_keys_state_idx ON public.agent_keys USING btree (state);

CREATE TABLE public.agent_participation (
    id uuid PRIMARY KEY,
    agent_id text NOT NULL,
    scope_kind text NOT NULL,
    scope_key text NOT NULL,
    realm_id text NOT NULL,
    scope jsonb NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    reply_message boolean DEFAULT false NOT NULL,
    reaction_add boolean DEFAULT false NOT NULL,
    reaction_remove boolean DEFAULT false NOT NULL,
    accept_third_party_mention boolean DEFAULT false NOT NULL,
    act_on_behalf boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT agent_participation_scope_kind_check CHECK ((scope_kind = ANY (ARRAY['realm'::text, 'circle'::text, 'strand'::text])))
);

ALTER TABLE ONLY public.agent_participation
    ADD CONSTRAINT agent_participation_agent_id_scope_key_key UNIQUE (agent_id, scope_key);

CREATE INDEX agent_participation_realm_idx ON public.agent_participation USING btree (realm_id);

CREATE TABLE public.agent_participation_ceiling (
    scope_kind text NOT NULL,
    scope_key text PRIMARY KEY,
    realm_id text NOT NULL,
    reply_message boolean DEFAULT false NOT NULL,
    reaction_add boolean DEFAULT false NOT NULL,
    reaction_remove boolean DEFAULT false NOT NULL,
    accept_third_party_mention boolean DEFAULT false NOT NULL,
    act_on_behalf boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT agent_participation_ceiling_scope_kind_check CHECK ((scope_kind = ANY (ARRAY['realm'::text, 'circle'::text, 'strand'::text])))
);

CREATE INDEX agent_participation_ceiling_realm_idx ON public.agent_participation_ceiling USING btree (realm_id);

CREATE TABLE public.agent_principals (
    id text PRIMARY KEY,
    controller_id text NOT NULL,
    principal_control_realm_id text NOT NULL,
    controller_authorization_ref text NOT NULL,
    display_name text,
    agent_slug text,
    avatar_blob_ref text,
    state text DEFAULT 'active'::text NOT NULL,
    requested_scope jsonb,
    accountability jsonb,
    provision_event_refs jsonb,
    pairing_request_id text,
    paired_pairing_request_id text,
    paired_request_digest text,
    pending_pairing_commit_intent jsonb,
    pairing_code text,
    pairing_expires_at timestamp with time zone,
    approval_request_id text,
    controller_account_id uuid,
    recipient_service_id text,
    runtime_key_binding_digest text,
    runtime_public_key_digest text,
    runtime_attestation_digest text,
    approval_notification_id uuid,
    runtime_key_request jsonb,
    approval_requested_at timestamp with time zone,
    authorized_event_ref text,
    authorized_verification_method text,
    authorized_public_key_digest text,
    authorized_signing_key_binding jsonb,
    state_changed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT agent_principals_id_check CHECK (((id ~~ 'did:%'::text) AND (id !~ '[[:space:]#?]'::text))),
    CONSTRAINT agent_principals_pcr_id_check CHECK ((principal_control_realm_id ~ '^ak:realm:[A-Za-z0-9_-]{44}$'::text)),
    CONSTRAINT agent_principals_controller_authorization_ref_check CHECK ((controller_authorization_ref ~~ (id || '#%'::text))),
    CONSTRAINT agent_principals_agent_slug_check CHECK ((agent_slug IS NULL) OR ((char_length(agent_slug) BETWEEN 1 AND 64) AND (octet_length(agent_slug) <= 256) AND (agent_slug !~ '[[:space:][:cntrl:]]'::text) AND (strpos(agent_slug, ':'::text) = 0) AND (strpos(agent_slug, '@'::text) = 0) AND (strpos(agent_slug, '/'::text) = 0) AND (strpos(agent_slug, '#'::text) = 0) AND (strpos(agent_slug, '?'::text) = 0) AND (strpos(agent_slug, E'\\') = 0))),
    CONSTRAINT agent_principals_state_check CHECK ((state = ANY (ARRAY['active'::text, 'paused'::text, 'deactivated'::text])))
);

CREATE INDEX agent_principals_controller_idx ON public.agent_principals USING btree (controller_id);

CREATE UNIQUE INDEX agent_principals_pcr_idx ON public.agent_principals USING btree (principal_control_realm_id);

CREATE INDEX agent_principals_controller_agent_slug_idx ON public.agent_principals USING btree (controller_id, agent_slug) WHERE (agent_slug IS NOT NULL);

CREATE UNIQUE INDEX agent_principals_pairing_request_idx ON public.agent_principals USING btree (pairing_request_id) WHERE (pairing_request_id IS NOT NULL);

CREATE UNIQUE INDEX agent_principals_approval_request_idx ON public.agent_principals USING btree (approval_request_id) WHERE (approval_request_id IS NOT NULL);

CREATE INDEX agent_principals_state_idx ON public.agent_principals USING btree (state);

ALTER TABLE ONLY public.agent_keys
    ADD CONSTRAINT agent_keys_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent_principals(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.agent_participation
    ADD CONSTRAINT agent_participation_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent_principals(id) ON DELETE CASCADE;

-- `sidecar` is an Event-derived kind, so `id` is the create Event's 33-byte
-- token. It stays a logical unique and the physical primary key is the local
-- sequential `pk`: a content-addressed 33-byte key arrives in random order and
-- would turn every insert into a scattered page write.
CREATE TABLE public.agent_sidecars (
    pk bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id bytea NOT NULL CHECK (octet_length(id) = 33),
    realm_id text NOT NULL,
    controller_id text NOT NULL,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT agent_sidecars_id_key UNIQUE (id),
    CONSTRAINT agent_sidecars_realm_controller_key UNIQUE (realm_id, controller_id),
    CONSTRAINT agent_sidecars_state_check CHECK ((state = ANY (ARRAY['active'::text, 'suspended'::text, 'tombstoned'::text])))
);

CREATE INDEX agent_sidecars_controller_idx ON public.agent_sidecars USING btree (controller_id, created_at, pk);

-- `sidecar_pk` is the local FK; the two Event references keep the protocol
-- 33-byte identity because canonical Event interning belongs to the admission
-- unit of work, and an FK here would invert that write order.
CREATE TABLE public.agent_sidecar_contexts (
    sidecar_pk bigint NOT NULL REFERENCES public.agent_sidecars(pk) ON DELETE CASCADE,
    normalized_context_ref_digest text NOT NULL,
    version bigint NOT NULL CHECK (version >= 1),
    normalized_context_ref jsonb NOT NULL,
    predecessor_event_ref bytea CHECK (octet_length(predecessor_event_ref) = 33),
    attach_event_ref bytea NOT NULL UNIQUE CHECK (octet_length(attach_event_ref) = 33),
    created_at timestamp with time zone NOT NULL,
    PRIMARY KEY (sidecar_pk, normalized_context_ref_digest, version)
);

CREATE TABLE public.agent_sessions (
    id uuid PRIMARY KEY,
    agent_id text NOT NULL,
    verification_method text NOT NULL,
    runtime_attestation jsonb,
    state text DEFAULT 'active'::text NOT NULL,
    expires_at timestamp with time zone,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT agent_sessions_state_check CHECK ((state = ANY (ARRAY['active'::text, 'revoked'::text, 'expired'::text])))
);

CREATE INDEX agent_sessions_principal_idx ON public.agent_sessions USING btree (agent_id);

CREATE INDEX agent_sessions_state_idx ON public.agent_sessions USING btree (state);

ALTER TABLE ONLY public.agent_sessions
    ADD CONSTRAINT agent_sessions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent_principals(id) ON DELETE CASCADE;

CREATE TABLE public.applet_registrations (
    id text PRIMARY KEY,
    namespace text NOT NULL,
    owner_actor_id text NOT NULL,
    registry_did text NOT NULL,
    bot_actor_id text NOT NULL,
    portal_realm_id text NOT NULL,
    capabilities jsonb DEFAULT '[]'::jsonb NOT NULL,
    manifest jsonb NOT NULL,
    package jsonb,
    namespaces jsonb,
    ghost_actors_allowed boolean DEFAULT false NOT NULL,
    status text NOT NULL,
    registered_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    idempotency_key text,
    install_body_digest text,
    install_id text,
    install_response jsonb,
    install_execution jsonb,
    ghosts jsonb DEFAULT '[]'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT applet_registrations_status_check CHECK ((status = ANY (ARRAY['registered'::text, 'installed'::text, 'partially_installed'::text, 'rejected'::text, 'revoked'::text])))
);

CREATE UNIQUE INDEX applet_registrations_active_namespace_idx ON public.applet_registrations USING btree (namespace) WHERE (revoked_at IS NULL);

CREATE INDEX applet_registrations_owner_idx ON public.applet_registrations USING btree (owner_actor_id);

CREATE INDEX applet_registrations_status_idx ON public.applet_registrations USING btree (status);

CREATE TABLE public.applet_transactions (
    source_service_id text NOT NULL,
    idempotency_key text NOT NULL,
    source_signature_anchor text NOT NULL,
    request_digest text NOT NULL,
    outcome jsonb,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    CONSTRAINT applet_transactions_pkey PRIMARY KEY (source_service_id, idempotency_key)
);

CREATE INDEX applet_transactions_received_idx ON public.applet_transactions USING btree (received_at);

CREATE TABLE public.audit_logs (
    id uuid PRIMARY KEY,
    actor_id text,
    request_id uuid,
    action text NOT NULL,
    outcome text NOT NULL,
    realm_id text,
    operation_id uuid,
    device_id text,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX audit_logs_action_idx ON public.audit_logs USING btree (action);

CREATE INDEX audit_logs_actor_idx ON public.audit_logs USING btree (actor_id, created_at);

CREATE INDEX audit_logs_space_idx ON public.audit_logs USING btree (realm_id);

CREATE TABLE public.backup_series (
    id uuid PRIMARY KEY,
    actor_id text NOT NULL,
    backup_kind text NOT NULL,
    head_backup_id uuid,
    head_seq bigint DEFAULT 0 NOT NULL,
    frontier_ref text,
    retired_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT backup_series_backup_class_check CHECK ((backup_kind = ANY (ARRAY['did_recovery'::text, 'secret_storage'::text, 'mls_history'::text, 'external'::text]))),
    CONSTRAINT backup_series_head_seq_check CHECK ((head_seq >= 0))
);

CREATE UNIQUE INDEX backup_series_actor_class_uniq ON public.backup_series USING btree (actor_id, backup_kind) WHERE (retired_at IS NULL);

CREATE INDEX backup_series_actor_idx ON public.backup_series USING btree (actor_id);

CREATE INDEX backup_series_class_idx ON public.backup_series USING btree (backup_kind);

CREATE TABLE public.blobs (
    id text PRIMARY KEY,
    sha256 text NOT NULL,
    media_type text NOT NULL,
    filename text,
    uploaded_by_id text NOT NULL,
    realm_id text,
    size_bytes bigint NOT NULL,
    storage_backend text NOT NULL,
    storage_key text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    retention_expires_at timestamp with time zone,
    legal_hold boolean DEFAULT false NOT NULL,
    redacted boolean DEFAULT false NOT NULL,
    visibility text DEFAULT 'realm_bound'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT blobs_visibility_check CHECK ((visibility = ANY (ARRAY['public'::text, 'realm_bound'::text, 'actor_private'::text, 'device_bound'::text])))
);

CREATE INDEX blobs_sha256_idx ON public.blobs USING btree (sha256);

CREATE INDEX blobs_space_created_idx ON public.blobs USING btree (realm_id, created_at);

-- Live relay for admitted `SignalEnvelope`s (`sync/signal.md` §4). One row per
-- admitted envelope, retained only until `expires_at`. Presence, typing, call
-- signalling and read receipts are all Signals in v1 and share this one table:
-- the exact payload type and target live inside `encrypted_payload`, and §1
-- forbids a service from requiring or inferring a finer classification, so
-- there is deliberately no `signal_kind`, target, sequence or plaintext column.
-- `position` is a monotonic per-Realm deliver-once cursor sourced from
-- Publication evidence per accepted Event canonical digest
-- (`authz/offline-publication.md` 2.1). The client-supplied AuthorizationLease
-- and the IngressReceipt this service signs at ingress are transport evidence
-- ABOUT an Event, not part of it: they never enter the Event digest, so they
-- live here rather than as columns on `canonical_events`. `event_digest` is the
-- primary key so the first receipt for a digest is the one that stands and an
-- idempotent retry cannot re-stamp `received_at`.
CREATE TABLE public.publication_evidence (
    event_digest text PRIMARY KEY,
    realm_id text NOT NULL,
    authorization_lease jsonb NOT NULL,
    ingress_receipt jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX publication_evidence_realm_idx ON public.publication_evidence USING btree (realm_id);

-- `signal_relay_position`.
CREATE TABLE public.signal_relay (
    id uuid PRIMARY KEY,
    realm_id text NOT NULL,
    position bigint NOT NULL,
    scope_ref jsonb NOT NULL,
    sender_actor_id text NOT NULL,
    sender_device_id text NOT NULL,
    signal_class text NOT NULL,
    envelope_digest text NOT NULL,
    envelope jsonb NOT NULL,
    sent_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT signal_relay_class_check CHECK ((signal_class = ANY (ARRAY['setup'::text, 'moderation'::text, 'session'::text])))
);

ALTER TABLE ONLY public.signal_relay
    ADD CONSTRAINT signal_relay_realm_position_key UNIQUE (realm_id, position);

CREATE INDEX signal_relay_realm_position_idx ON public.signal_relay USING btree (realm_id, position);

CREATE INDEX signal_relay_expires_idx ON public.signal_relay USING btree (expires_at);

CREATE INDEX signal_relay_realm_digest_idx ON public.signal_relay USING btree (realm_id, envelope_digest);

-- Per-Realm monotonic position counter for `signal_relay`. Held in a dedicated
-- table (not `MAX(position)` of live rows) so positions keep increasing even
-- after the relay log is pruned, and a deliver-once watermark can never be
-- re-crossed by a recycled position.
CREATE TABLE public.signal_relay_position (
    realm_id text PRIMARY KEY,
    next_position bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Per-subscriber-device deliver-once watermark for `signal_relay`. Records the
-- highest per-Realm `position` already delivered to a `(actor, device, realm)`
-- triple so an incremental re-subscribe inside the TTL window does not re-emit
-- a Signal the device already saw, while a full resubscribe still recovers all
-- non-expired live Signals.
CREATE TABLE public.signal_relay_watermark (
    actor_id text NOT NULL,
    device_id text NOT NULL,
    realm_id text NOT NULL,
    delivered_through bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT signal_relay_watermark_pkey PRIMARY KEY (actor_id, device_id, realm_id)
);

CREATE TABLE public.canonical_events (
    pk bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id bytea NOT NULL,
    digest_suite smallint NOT NULL,
    digest bytea NOT NULL,
    actor_id text NOT NULL,
    actor_seq bigint NOT NULL,
    realm_id text,
    realm_pk bigint REFERENCES public.canonical_realms(pk) ON DELETE RESTRICT,
    kind text NOT NULL,
    schema_id text NOT NULL,
    canonical_bytes bytea NOT NULL,
    envelope jsonb NOT NULL,
    state text DEFAULT 'accepted' NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT canonical_events_state_check CHECK (state IN ('accepted', 'quarantined')),
    CONSTRAINT canonical_events_id_length_check CHECK (octet_length(id) = 33),
    CONSTRAINT canonical_events_reserved_nibble_check CHECK ((get_byte(id, 0) >> 4) = 0),
    CONSTRAINT canonical_events_digest_suite_check CHECK (digest_suite IN (1, 2)),
    CONSTRAINT canonical_events_digest_length_check CHECK (octet_length(digest) = 32),
    CONSTRAINT canonical_events_id_digest_check CHECK (
        id = decode(lpad(to_hex(digest_suite::integer), 2, '0'), 'hex') || digest
    ),
    CONSTRAINT canonical_events_id_key UNIQUE (id),
    CONSTRAINT canonical_events_identity_key UNIQUE (digest_suite, digest)
);

CREATE INDEX canonical_events_realm_pk_idx
    ON public.canonical_events USING btree (realm_pk, received_at, pk);

CREATE INDEX canonical_events_actor_idx ON public.canonical_events USING btree (actor_id, actor_seq DESC);

CREATE INDEX canonical_events_actor_received_idx ON public.canonical_events USING btree (actor_id, received_at, id);

CREATE INDEX canonical_events_kind_idx ON public.canonical_events USING btree (kind);

CREATE INDEX canonical_events_kind_received_idx ON public.canonical_events USING btree (kind, received_at, id);

CREATE INDEX canonical_events_peer_sync_endpoints_idx ON public.canonical_events USING btree (received_at, id) WHERE (((envelope #> '{payload,sync_endpoints}'::text[]) IS NOT NULL) OR ((envelope #> '{payload,object,sync_endpoints}'::text[]) IS NOT NULL) OR ((envelope #> '{payload,patch,sync_endpoints}'::text[]) IS NOT NULL));

CREATE INDEX canonical_events_received_idx ON public.canonical_events USING btree (received_at, id);

CREATE UNIQUE INDEX canonical_events_realm_create_unique_idx ON public.canonical_events USING btree (realm_id) WHERE (kind = 'ak.realm.create'::text AND state = 'accepted'::text);

CREATE INDEX canonical_events_space_idx ON public.canonical_events USING btree (realm_id);

CREATE INDEX canonical_events_space_received_idx ON public.canonical_events USING btree (realm_id, received_at, id);

-- Losing/competing canonical encodings for one Event identity. A collision is
-- by definition "same `(digest_suite, digest)`, different `canonical_bytes`",
-- so the variant's identity IS the parent's: it is reached through `event_pk`
-- and never re-stated here. Copying `event_id`/`digest_suite`/`digest` onto
-- this row would be a second, unconstrained claim about the same identity that
-- no constraint could keep coherent with `canonical_events`. Only the columns
-- that genuinely differ per variant are stored. `UNIQUE (event_pk,
-- canonical_bytes)` makes "one row per distinct encoding" a storage guarantee
-- rather than a read-then-write check.
CREATE TABLE public.event_collision_variants (
    pk bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_pk bigint NOT NULL REFERENCES public.canonical_events(pk) ON DELETE RESTRICT,
    actor_id text NOT NULL,
    actor_seq bigint NOT NULL,
    realm_id text,
    kind text NOT NULL,
    schema_id text NOT NULL,
    canonical_bytes bytea NOT NULL,
    envelope jsonb NOT NULL,
    received_at timestamp with time zone NOT NULL,
    CONSTRAINT event_collision_variants_encoding_key UNIQUE (event_pk, canonical_bytes)
);

CREATE INDEX event_collision_variants_event_pk_idx
    ON public.event_collision_variants USING btree (event_pk);

CREATE TABLE public.event_batch_receipts (
    pk bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    schema text NOT NULL,
    id uuid NOT NULL UNIQUE,
    issuer text NOT NULL,
    scope jsonb NOT NULL,
    frontier jsonb NOT NULL,
    events jsonb NOT NULL,
    proofs jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.event_batch_receipt_events (
    receipt_pk bigint NOT NULL REFERENCES public.event_batch_receipts(pk) ON DELETE CASCADE,
    event_pk bigint NOT NULL REFERENCES public.canonical_events(pk) ON DELETE RESTRICT,
    PRIMARY KEY (receipt_pk, event_pk)
);

CREATE INDEX event_batch_receipt_events_event_pk_idx
    ON public.event_batch_receipt_events USING btree (event_pk);

-- Pending + sealed control-plane Events. v1 has no standalone Move object: a
-- Control Move is an Event carrying `seal_basis`, so the log is keyed by the
-- canonical control-event digest rather than by a Move id.
CREATE TABLE public.state_control_events (
    event_digest text PRIMARY KEY,
    realm_id text NOT NULL,
    event_json jsonb NOT NULL,
    control_proposal_ack jsonb,
    proposal_decisions jsonb DEFAULT '[]'::jsonb NOT NULL,
    decision_overdue boolean DEFAULT false NOT NULL,
    sealed_by text,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    sealed_at timestamp with time zone
);

CREATE INDEX state_control_events_pending_idx ON public.state_control_events USING btree (realm_id, inserted_at, event_digest) WHERE (sealed_by IS NULL);

CREATE INDEX state_control_events_sealed_idx ON public.state_control_events USING btree (realm_id, inserted_at, event_digest) WHERE (sealed_by IS NOT NULL);

CREATE TABLE public.state_seals (
    id text PRIMARY KEY,
    realm_id text NOT NULL,
    seal_json jsonb NOT NULL,
    predecessor_refs jsonb DEFAULT '[]'::jsonb NOT NULL,
    is_genesis boolean DEFAULT false NOT NULL,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX state_seals_realm_idx ON public.state_seals USING btree (realm_id, inserted_at, id);

CREATE INDEX state_seals_predecessor_refs_idx ON public.state_seals USING gin (predecessor_refs);

CREATE TABLE public.state_seal_signing_leases (
    realm_id text NOT NULL,
    signer_slot text NOT NULL,
    holder text NOT NULL,
    lease_until_ms bigint NOT NULL,
    fence bigint NOT NULL,
    CONSTRAINT state_seal_signing_leases_pkey PRIMARY KEY (realm_id, signer_slot)
);

CREATE TABLE public.state_cell_ops (
    seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    realm_id text NOT NULL,
    seal_id text NOT NULL,
    op_index bigint NOT NULL,
    cell_id text NOT NULL,
    move_id text NOT NULL,
    op_json jsonb NOT NULL,
    appended_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.state_cell_ops
    ADD CONSTRAINT state_cell_ops_seal_op_index_key UNIQUE (seal_id, op_index);

CREATE INDEX state_cell_ops_cell_idx ON public.state_cell_ops USING btree (realm_id, cell_id, seq);

CREATE INDEX state_cell_ops_seal_idx ON public.state_cell_ops USING btree (realm_id, seal_id);

CREATE TABLE public.state_cell_cache (
    realm_id text NOT NULL,
    cell_id text NOT NULL,
    view_hash text NOT NULL,
    state_json jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT state_cell_cache_pkey PRIMARY KEY (realm_id, cell_id, view_hash)
);

CREATE TABLE public.consent_cells (
    id uuid PRIMARY KEY,
    holder_id text NOT NULL,
    peer_id text NOT NULL,
    scope text NOT NULL,
    cell_id text NOT NULL,
    requested_at timestamp with time zone,
    grant_dots jsonb DEFAULT '{}'::jsonb NOT NULL,
    revoked_dots jsonb DEFAULT '[]'::jsonb NOT NULL,
    revoked_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.consent_cells
    ADD CONSTRAINT consent_cells_holder_peer_scope_key UNIQUE (holder_id, peer_id, scope);

CREATE TABLE public.contacts (
    id uuid PRIMARY KEY,
    requester_id text NOT NULL,
    target_id text NOT NULL,
    basis_id text,
    version bigint CHECK (version >= 1),
    granted_to_target_scopes text[] DEFAULT '{}'::text[] NOT NULL,
    granted_to_requester_scopes text[] DEFAULT '{}'::text[] NOT NULL,
    status text NOT NULL,
    -- Not `event_pk` keys: a contact request/response can be authored on the
    -- peer's service, so the named Event need not exist in this deployment's
    -- log at all and a foreign key would reject the legitimate federated case.
    -- Stored in the same 33-octet form `canonical_events.id` uses.
    request_event_ref bytea CHECK (octet_length(request_event_ref) = 33),
    response_event_ref bytea CHECK (octet_length(response_event_ref) = 33),
    tombstone_event_ref bytea CHECK (octet_length(tombstone_event_ref) = 33),
    message text,
    peer_service_id text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_requester_target_key UNIQUE (requester_id, target_id);

CREATE INDEX contacts_target_idx ON public.contacts USING btree (target_id);

CREATE TABLE public.devices (
    id uuid PRIMARY KEY,
    actor_id text NOT NULL,
    device_id text NOT NULL,
    device_key text,
    verification_state text DEFAULT 'unverified'::text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_actor_device_id_key UNIQUE (actor_id, device_id);

CREATE INDEX devices_actor_updated_idx ON public.devices USING btree (actor_id, updated_at DESC);

CREATE TABLE public.device_pairings (
    device_pairing_request_id text NOT NULL,
    pairing_code text NOT NULL,
    new_device_pubkey jsonb NOT NULL,
    client_nonce text NOT NULL,
    gate_audience text NOT NULL,
    server_nonce text NOT NULL,
    display_name text,
    device_metadata jsonb,
    state text DEFAULT 'pending_authorization' NOT NULL,
    device_id text,
    authorized_by_actor_id text,
    authorized_event_ref text,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    PRIMARY KEY (device_pairing_request_id),
    CONSTRAINT device_pairings_state_check
        CHECK (state = ANY (ARRAY['pending_authorization', 'authorized', 'expired']))
);

CREATE INDEX device_pairings_expiry_idx
    ON public.device_pairings (expires_at);

CREATE TABLE public.device_messages (
    id uuid PRIMARY KEY,
    idempotency_key text NOT NULL,
    sender text NOT NULL,
    recipient text NOT NULL,
    device_id text NOT NULL,
    position bigint NOT NULL,
    content jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.device_messages
    ADD CONSTRAINT device_messages_recipient_device_position_key UNIQUE (recipient, device_id, position);

CREATE INDEX device_messages_recipient_device_position_idx ON public.device_messages USING btree (recipient, device_id, position);

CREATE INDEX device_messages_sender_idempotency_idx ON public.device_messages USING btree (sender, idempotency_key);

CREATE TABLE public.device_message_txns (
    key text PRIMARY KEY,
    request_digest text NOT NULL,
    outcome jsonb NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.device_message_idempotency (
    message_key text PRIMARY KEY,
    intent_digest text NOT NULL,
    delivered boolean NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.device_message_ack_tokens (
    ack_token text PRIMARY KEY,
    recipient text NOT NULL,
    device_id text NOT NULL,
    queue_position bigint NOT NULL,
    issued_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone
);

CREATE INDEX device_message_ack_tokens_device_idx ON public.device_message_ack_tokens USING btree (recipient, device_id, expires_at);

CREATE TABLE public.device_message_lost_watermarks (
    recipient text NOT NULL,
    device_id text NOT NULL,
    lost_through bigint NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (recipient, device_id)
);

CREATE TABLE public.federation_operations (
    id uuid PRIMARY KEY,
    realm_id text NOT NULL,
    object_kind text NOT NULL,
    object_id text,
    operation_kind text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX federation_operations_object_type_idx ON public.federation_operations USING btree (object_kind);

CREATE INDEX federation_operations_space_idx ON public.federation_operations USING btree (realm_id, created_at);

CREATE TABLE public.federation_outbox (
    id text PRIMARY KEY,
    event_pk bigint REFERENCES public.canonical_events(pk) ON DELETE RESTRICT,
    peer_id text NOT NULL,
    peer_url text NOT NULL,
    endpoint text NOT NULL,
    idempotency_key text NOT NULL,
    payload_json text NOT NULL,
    state text DEFAULT 'pending' NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    semantic_attempts integer DEFAULT 0 NOT NULL,
    next_attempt_at bigint NOT NULL,
    last_http_status integer,
    last_error_code text,
    last_response_excerpt text,
    lease_owner text,
    lease_token text,
    lease_expires_at bigint,
    policy_version text,
    supersedes_outbox_id text,
    completed_at bigint,
    created_at bigint NOT NULL,
    CONSTRAINT federation_outbox_state_check CHECK (state IN ('pending', 'leased', 'delivered', 'policy_suppressed', 'dead_lettered', 'superseded'))
);

CREATE UNIQUE INDEX federation_outbox_peer_idem ON public.federation_outbox USING btree (peer_id, idempotency_key);

-- Claim scan: `state IN ('pending','leased') AND next_attempt_at <= now`,
-- ordered by next_attempt_at. `lease_expires_at` is in the index so an expired
-- lease can be taken over without touching the heap.
CREATE INDEX federation_outbox_claim ON public.federation_outbox USING btree (state, next_attempt_at, lease_expires_at);

-- Policy-suppressed revalidation sweep (`federation.md` §4.4).
CREATE INDEX federation_outbox_policy_suppressed ON public.federation_outbox USING btree (policy_version) WHERE (state = 'policy_suppressed'::text);

CREATE INDEX federation_outbox_state_peer ON public.federation_outbox USING btree (state, peer_id, created_at);

-- `events.rs` suppresses pending deliveries for a quarantined Event by
-- `WHERE event_pk = $1`; without this the collision path sequential-scans the
-- whole outbox.
CREATE INDEX federation_outbox_event_pk_idx ON public.federation_outbox USING btree (event_pk);

CREATE TABLE public.federation_outbox_dead_letter (
    id text PRIMARY KEY,
    outbox_id text NOT NULL,
    peer_id text NOT NULL,
    endpoint text NOT NULL,
    idempotency_key text NOT NULL,
    last_http_status integer,
    attempts integer NOT NULL,
    response_excerpt text,
    reason text NOT NULL,
    failed_at bigint NOT NULL,
    requeued_outbox_id text,
    requeued_by text,
    requeue_reason text,
    requeue_request_digest text,
    requeued_at bigint
);

CREATE INDEX federation_outbox_dead_letter_failed_at ON public.federation_outbox_dead_letter USING btree (failed_at, id);

CREATE INDEX federation_outbox_dead_letter_outbox_id_idx
    ON public.federation_outbox_dead_letter USING btree (outbox_id);

ALTER TABLE ONLY public.federation_outbox_dead_letter
    ADD CONSTRAINT federation_outbox_dead_letter_outbox_id_fkey FOREIGN KEY (outbox_id) REFERENCES public.federation_outbox(id) ON DELETE CASCADE;

CREATE TABLE public.federation_frontier_exchange (
    realm_id text NOT NULL,
    peer_service_id text NOT NULL,
    status text NOT NULL,
    consecutive_failures integer DEFAULT 0 NOT NULL,
    last_success_at bigint,
    last_failure_at bigint,
    last_frontier_root text,
    last_error text,
    updated_at bigint NOT NULL,
    CONSTRAINT federation_frontier_exchange_pkey PRIMARY KEY (realm_id, peer_service_id)
);

CREATE INDEX federation_frontier_exchange_status_idx ON public.federation_frontier_exchange USING btree (status, updated_at);

CREATE TABLE public.invite_receive_policies (
    subject_id text PRIMARY KEY,
    policy_payload jsonb NOT NULL,
    denied_subjects text[] DEFAULT '{}'::text[] NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.invite_locators (
    locator_id text PRIMARY KEY,
    token_digest text NOT NULL UNIQUE,
    subject_id text NOT NULL,
    recipient_service_id text NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    one_time_use boolean DEFAULT false NOT NULL,
    record_payload jsonb NOT NULL,
    revoked_at timestamp with time zone,
    consumed_at timestamp with time zone
);

CREATE INDEX invite_locators_subject_active_idx ON public.invite_locators USING btree (subject_id, expires_at) WHERE revoked_at IS NULL AND consumed_at IS NULL;

CREATE TABLE public.join_applications (
    realm_id text NOT NULL,
    application_ref text NOT NULL,
    record jsonb NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY (realm_id, application_ref)
);

CREATE INDEX join_applications_realm_updated_idx
    ON public.join_applications (realm_id, updated_at, application_ref);

CREATE TABLE public.join_application_idempotency (
    principal_id text NOT NULL,
    idempotency_key text NOT NULL,
    request_hash text NOT NULL,
    response_body jsonb NOT NULL,
    realm_id text NOT NULL,
    application_ref text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    PRIMARY KEY (principal_id, idempotency_key),
    FOREIGN KEY (realm_id, application_ref)
        REFERENCES public.join_applications (realm_id, application_ref)
        ON DELETE CASCADE
);

CREATE INDEX join_application_idempotency_expiry_idx
    ON public.join_application_idempotency (expires_at);

CREATE INDEX join_application_idempotency_application_idx
    ON public.join_application_idempotency (realm_id, application_ref);

-- Deployment-wide dynamic operational settings (rate limits, admin
-- allowlist, federation peers, feature toggles). One row PER setting key:
-- `value` is the JSON for that key only. This is an OVERLAY — env/boot config
-- provides the defaults and only explicitly-overridden keys have a row here,
-- so changing an env default still takes effect for keys never overridden.
-- Per-key rows also mean independent updates, per-key audit, and no
-- lost-update when two keys change concurrently. Tier-1 bootstrap/secret
-- config (bind, DATABASE_URL, service DID, signing seeds) deliberately stays
-- in env and is NOT stored here.
CREATE TABLE public.server_settings (
    key text NOT NULL,
    value jsonb NOT NULL,
    updated_by text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT server_settings_pkey PRIMARY KEY (key)
);

CREATE TABLE public.key_backups (
    id uuid PRIMARY KEY,
    actor_id text,
    device_id text,
    backup_kind text,
    backup_version text,
    payload jsonb NOT NULL,
    last_accessed_at timestamp with time zone,
    account_id text,
    scheme text,
    version integer DEFAULT 0 NOT NULL,
    key_material_encrypted bytea,
    -- SOL-02-004: identity of the backup series this envelope belongs to,
    -- projected out of the JSONB payload as stored generated columns. They
    -- back the UNIQUE(series_actor_id, series_id, series_seq) constraint below
    -- which makes the §7.6 series-monotonicity check race-free: two concurrent
    -- successor PUTs that both compute the same series_seq can no longer both
    -- land — the second insert is rejected by the unique violation rather than
    -- relying on a read-then-write (TOCTOU) snapshot check.
    series_actor_id text GENERATED ALWAYS AS ((payload ->> 'actor_id')) STORED,
    series_id text GENERATED ALWAYS AS ((payload ->> 'series_id')) STORED,
    series_seq bigint GENERATED ALWAYS AS (((payload ->> 'series_seq'))::bigint) STORED,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- SOL-02-004: enforce series_seq monotonicity at the storage layer. A given
-- (actor, series) may hold at most one envelope per sequence number; the
-- receive path depends on this constraint so concurrent successor PUTs cannot
-- double-write the same seq (TOCTOU). NULLs (non-series backups) are exempt
-- because Postgres treats NULL as distinct in a UNIQUE index.
ALTER TABLE ONLY public.key_backups
    ADD CONSTRAINT key_backups_series_seq_key UNIQUE (series_actor_id, series_id, series_seq);

CREATE INDEX key_backups_account_idx ON public.key_backups USING btree (account_id);

CREATE INDEX key_backups_actor_idx ON public.key_backups USING btree (actor_id);

CREATE INDEX key_backups_device_idx ON public.key_backups USING btree (device_id);

-- key-management.md 7.8.1: the server-issued, durable, single-use delete
-- challenge a high-risk key-backup DELETE must consume. The whole challenge is
-- kept in `challenge` so the wire shape has one definition (the SDK type); the
-- columns beside it back the only two lookups -- by `challenge_id` when
-- verifying a DELETE, and by (principal_id, backup_id, request_id) when
-- re-issuing. That triple is UNIQUE because 7.8.1 requires the same request_id
-- to receive the same challenge while it is still valid, so a client retrying
-- the issue call cannot invalidate the challenge it is already signing.
-- `consumed_at` is the single-use flag: it is set under
-- `WHERE consumed_at IS NULL`, so two concurrent DELETEs consume exactly once.
CREATE TABLE public.key_backup_delete_challenges (
    challenge_id text NOT NULL,
    principal_id text NOT NULL,
    backup_id text NOT NULL,
    request_id text NOT NULL,
    challenge jsonb NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone,
    PRIMARY KEY (challenge_id),
    CONSTRAINT key_backup_delete_challenges_request_key
        UNIQUE (principal_id, backup_id, request_id)
);

CREATE INDEX key_backup_delete_challenges_expiry_idx
    ON public.key_backup_delete_challenges (expires_at);

CREATE TABLE public.mls_commits (
    id uuid PRIMARY KEY,
    effective_scope_kind text NOT NULL,
    realm_id text NOT NULL,
    circle_id text,
    effective_scope jsonb NOT NULL,
    mls_group_id text NOT NULL,
    epoch bigint NOT NULL,
    leader_actor_id text NOT NULL,
    creator_device_id text NOT NULL,
    -- Same blocker as `notifications.source_event_id`: `reducer/mls.rs` and
    -- `routing/events/projection/apply.rs` fall back to the Operation id when
    -- the genesis payload carries no `event_id`, so this is not yet an Event
    -- identity column.
    genesis_event_ref text NOT NULL,
    governance_binding jsonb DEFAULT '{}'::jsonb NOT NULL,
    accepted_commit_ref text,
    committed_at bigint NOT NULL,
    frontier_contested boolean DEFAULT false NOT NULL,
    CONSTRAINT mls_commits_effective_scope_check CHECK ((((effective_scope_kind = 'realm'::text) AND (circle_id IS NULL)) OR ((effective_scope_kind = 'circle'::text) AND (circle_id IS NOT NULL))))
);

CREATE UNIQUE INDEX mls_commits_circle_scope_key ON public.mls_commits USING btree (realm_id, circle_id, mls_group_id) WHERE ((effective_scope_kind = 'circle'::text) AND (circle_id IS NOT NULL));

CREATE UNIQUE INDEX mls_commits_realm_scope_key ON public.mls_commits USING btree (realm_id, mls_group_id) WHERE ((effective_scope_kind = 'realm'::text) AND (circle_id IS NULL));

CREATE TABLE public.mls_key_packages (
    id text PRIMARY KEY,
    keypackage_ref text NOT NULL,
    keypackage_digest text NOT NULL,
    actor_id text NOT NULL,
    device_id text NOT NULL,
    key_package_bytes bytea NOT NULL,
    capabilities jsonb DEFAULT '[]'::jsonb NOT NULL,
    capabilities_digest text NOT NULL,
    device_signature jsonb DEFAULT '{}'::jsonb NOT NULL,
    last_resort boolean DEFAULT false NOT NULL,
    last_resort_realm_id text,
    lifetime_not_before bigint NOT NULL,
    lifetime_not_after bigint NOT NULL,
    claimed_by_mls_group_id text,
    ssk_generation bigint,
    -- Not `event_pk` keys: the trust binding is asserted by the uploading
    -- client, and a federated actor's device/agent-key authorization Event
    -- lives in its home service's log, not this one. Stored in the same
    -- 33-octet form `canonical_events.id` uses.
    device_authorize_event_id bytea CHECK (octet_length(device_authorize_event_id) = 33),
    agent_key_authorize_event_id bytea CHECK (octet_length(agent_key_authorize_event_id) = 33),
    claimed_at bigint,
    claim_expires_at_unix_ms bigint,
    consumed_at bigint,
    created_at bigint NOT NULL,
    CONSTRAINT mls_key_packages_trust_binding_check CHECK (
        num_nonnulls(ssk_generation, device_authorize_event_id, agent_key_authorize_event_id) = 1
        AND (ssk_generation IS NULL OR ssk_generation >= 1)
    )
);

ALTER TABLE ONLY public.mls_key_packages
    ADD CONSTRAINT mls_key_packages_keypackage_ref_key UNIQUE (keypackage_ref);

CREATE INDEX mls_key_packages_by_actor_device ON public.mls_key_packages USING btree (actor_id, device_id, claimed_by_mls_group_id);

CREATE TABLE public.peer_keypackage_claims (
    source_service_id text NOT NULL,
    claim_request_id text NOT NULL,
    request_digest text NOT NULL,
    keypackage_id text,
    outcome jsonb,
    terminal_receipt jsonb,
    consume_receipt jsonb,
    claim_expires_at_unix_ms bigint,
    expires_at bigint NOT NULL,
    state text NOT NULL,
    updated_at bigint NOT NULL,
    CONSTRAINT peer_keypackage_claims_state_check CHECK (state IN ('claimed', 'consumed', 'claim_failed', 'expired', 'revoked', 'last_resort_claimed')),
    PRIMARY KEY (source_service_id, claim_request_id)
);

CREATE TABLE public.mls_welcomes (
    id text PRIMARY KEY,
    mls_group_id text NOT NULL,
    recipient_actor_id text NOT NULL,
    recipient_device_id text NOT NULL,
    welcome_bytes bytea NOT NULL,
    key_package_id text NOT NULL,
    epoch bigint NOT NULL,
    commit_ref text,
    governance_binding jsonb NOT NULL,
    enqueued_at bigint NOT NULL,
    delivered_at bigint
);

CREATE INDEX mls_welcomes_recipient_pending ON public.mls_welcomes USING btree (recipient_actor_id, recipient_device_id, delivered_at, enqueued_at);

CREATE TABLE public.moderation_actions (
    id uuid PRIMARY KEY,
    moderator_id text,
    target_actor_id text,
    action_kind text,
    realm_id text,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX moderation_actions_target_idx ON public.moderation_actions USING btree (target_actor_id);

-- `report` is an Event-derived kind: `id` is the create Event's 33-byte token
-- behind a local sequential `pk`. `target_event_id` is the protocol identity of
-- the reported Event.
CREATE TABLE public.moderation_reports (
    pk bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id bytea NOT NULL CHECK (octet_length(id) = 33),
    reporter_id text,
    target_actor_id text,
    target_event_id bytea CHECK (octet_length(target_event_id) = 33),
    realm_id text,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT moderation_reports_id_key UNIQUE (id)
);

CREATE INDEX moderation_reports_space_idx ON public.moderation_reports USING btree (realm_id);

CREATE INDEX moderation_reports_target_idx ON public.moderation_reports USING btree (target_actor_id);

CREATE TABLE public.organizations (
    organization_id text PRIMARY KEY,
    organization_did text NOT NULL,
    handle text,
    display_name text NOT NULL,
    source_refs jsonb DEFAULT '[]'::jsonb NOT NULL,
    policy_revision text DEFAULT 'local'::text NOT NULL,
    verified boolean DEFAULT true NOT NULL,
    members jsonb DEFAULT '[]'::jsonb NOT NULL,
    member_count bigint DEFAULT 0 NOT NULL,
    created_by text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE INDEX organizations_handle_idx ON public.organizations USING btree (handle) WHERE (handle IS NOT NULL);

CREATE INDEX organizations_did_idx ON public.organizations USING btree (organization_did);

CREATE TABLE public.organization_registration_challenges (
    challenge_id text PRIMARY KEY,
    organization_id text NOT NULL,
    record jsonb NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed_request_digest text,
    consumed_outcome_id text,
    consumed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT organization_registration_challenge_consumption_complete CHECK (
        (consumed_request_digest IS NULL
            AND consumed_outcome_id IS NULL
            AND consumed_at IS NULL)
        OR
        (consumed_request_digest IS NOT NULL
            AND consumed_outcome_id IS NOT NULL
            AND consumed_at IS NOT NULL)
    )
);

CREATE INDEX organization_registration_challenges_organization_idx
    ON public.organization_registration_challenges (organization_id, created_at DESC);

CREATE TABLE public.organization_registration_outcomes (
    outcome_id text PRIMARY KEY,
    organization_id text NOT NULL,
    registration_generation bigint NOT NULL CHECK (registration_generation > 0),
    outcome jsonb NOT NULL,
    committed_at timestamp with time zone NOT NULL
);

CREATE INDEX organization_registration_outcomes_generation_idx
    ON public.organization_registration_outcomes (
        organization_id,
        registration_generation,
        committed_at
    );

ALTER TABLE public.organization_registration_challenges
    ADD CONSTRAINT organization_registration_challenge_consumed_outcome_fk
    FOREIGN KEY (consumed_outcome_id)
    REFERENCES public.organization_registration_outcomes(outcome_id);

CREATE FUNCTION public.reject_organization_registration_outcome_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'organization registration outcomes are immutable'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER organization_registration_outcomes_immutable_update
BEFORE UPDATE OR DELETE ON public.organization_registration_outcomes
FOR EACH ROW
EXECUTE FUNCTION public.reject_organization_registration_outcome_mutation();

CREATE TABLE public.organization_registration_states (
    organization_id text PRIMARY KEY,
    current_generation bigint NOT NULL CHECK (current_generation > 0),
    current_outcome_id text NOT NULL
        REFERENCES public.organization_registration_outcomes(outcome_id),
    state jsonb NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE INDEX organization_registration_states_generation_idx
    ON public.organization_registration_states (organization_id, current_generation);

CREATE TABLE public.organization_policies (
    organization_id text PRIMARY KEY,
    policy_id text NOT NULL,
    payload jsonb NOT NULL,
    version bigint NOT NULL,
    updated_by text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT organization_policies_version_check CHECK ((version >= 0))
);

-- SOL-ORG-04 — verified `ak.realm.organization` relationship statements.
-- Primary key `(realm_id, organization_id, relationship)` so owner /
-- governance / sponsor / directory_certifier relationships for the same Realm
-- coexist as independent rows. Column order mirrors the spec
-- `realm_organization_payload`. Only the proof / delegation audit digests are
-- stored, never raw signature bytes.
CREATE TABLE public.realm_organizations (
    realm_id text NOT NULL,
    organization_id text NOT NULL,
    relationship text NOT NULL,
    statement_id text NOT NULL,
    status text NOT NULL,
    control_scopes jsonb DEFAULT '[]'::jsonb NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    not_before timestamp with time zone,
    expires_at timestamp with time zone,
    supersedes_statement_id text,
    revokes_statement_id text,
    realm_frontier_digest text,
    proof_digest text,
    delegation_ref text,
    issuer_role text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT realm_organizations_pkey PRIMARY KEY (realm_id, organization_id, relationship)
);

CREATE INDEX realm_organizations_organization_idx ON public.realm_organizations USING btree (organization_id);

CREATE INDEX realm_organizations_relationship_idx ON public.realm_organizations USING btree (realm_id, relationship, status);

-- SOL-ORG-05 — `owning_organizations` declared hints. These NO LONGER drive
-- governance / durability / delivery / directory policy inheritance (only a
-- verified `ak.realm.organization` statement does); the table is retained as a
-- discovery / display hint surface.
CREATE TABLE public.realm_owning_organizations (
    realm_id text NOT NULL,
    organization_id text NOT NULL,
    linked_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT realm_owning_organizations_pkey PRIMARY KEY (realm_id, organization_id)
);

CREATE INDEX realm_owning_organizations_organization_idx ON public.realm_owning_organizations USING btree (organization_id);

CREATE TABLE public.realm_moderation_policies (
    realm_id text PRIMARY KEY,
    payload jsonb NOT NULL,
    updated_by text NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.retention_policies (
    realm_id text PRIMARY KEY,
    ttl_seconds bigint NOT NULL,
    updated_by text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT retention_policies_ttl_seconds_check CHECK ((ttl_seconds >= 0))
);

-- Records that retention expired an Event. Deliberately NOT an `event_pk`
-- foreign key: this table exists to survive the erasure of the very row such a
-- key would pin, and `ON DELETE RESTRICT` would block it. The Event identity is
-- therefore stored directly, in the same 33-octet form `canonical_events.id`
-- uses, so the two can be compared without a representation change.
CREATE TABLE public.retention_tombstones (
    event_id bytea CHECK (octet_length(event_id) = 33) PRIMARY KEY,
    realm_id text NOT NULL,
    reason text NOT NULL,
    policy_ttl_seconds bigint NOT NULL,
    expired_at timestamp with time zone NOT NULL,
    tombstoned_at timestamp with time zone NOT NULL,
    sealed boolean DEFAULT false NOT NULL,
    CONSTRAINT retention_tombstones_policy_ttl_seconds_check CHECK ((policy_ttl_seconds >= 0))
);

CREATE INDEX retention_tombstones_realm_idx ON public.retention_tombstones USING btree (realm_id);

CREATE TABLE public.multisig_pending (
    seal_id text PRIMARY KEY,
    realm_id text NOT NULL,
    threshold_k integer NOT NULL,
    threshold_n integer NOT NULL,
    members text[] NOT NULL,
    canonical_b64 text DEFAULT ''::text NOT NULL,
    partials jsonb DEFAULT '{}'::jsonb NOT NULL,
    claimed_by_node_id text,
    claimed_until timestamp with time zone,
    claim_seq bigint DEFAULT 0 NOT NULL,
    expires_at timestamp with time zone DEFAULT (now() + '01:00:00'::interval) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX multisig_pending_claim_seq_idx ON public.multisig_pending USING btree (claim_seq);

CREATE INDEX multisig_pending_claimed_idx ON public.multisig_pending USING btree (claimed_until);

CREATE INDEX multisig_pending_expires_idx ON public.multisig_pending USING btree (expires_at);

CREATE INDEX multisig_pending_space_idx ON public.multisig_pending USING btree (realm_id);

CREATE SEQUENCE public.notification_projection_position_seq AS bigint;

CREATE TABLE public.notifications (
    id uuid PRIMARY KEY,
    recipient_id text NOT NULL,
    realm_id text,
    -- Still `text`, and deliberately not yet an Event identity column: the
    -- producers in `routing/events/notify.rs` and `reducer/apply_messages.rs`
    -- fall back to the Operation id when the payload carries no `event_id`, so
    -- this column holds an `ak:event:` id OR an `ak:operation:` id. It also
    -- backs a UNIQUE dedup key, so the fallback has to be removed before the
    -- column can become a 33-octet Event identity.
    source_event_id text,
    controller_account_id uuid,
    recipient_service_id text,
    source_account_artifact_kind text,
    source_account_artifact_id text,
    source_ref text,
    strand_id text,
    track_name text,
    notification_kind text NOT NULL,
    event_kind text,
    source_actor_id text,
    priority text DEFAULT 'normal'::text NOT NULL,
    state text DEFAULT 'unread'::text NOT NULL,
    preview jsonb,
    projection_action text,
    projection_data jsonb,
    projection_position bigint DEFAULT nextval('public.notification_projection_position_seq'::regclass) NOT NULL,
    read_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT notifications_source_boundary_check CHECK (((source_event_id IS NOT NULL) AND (realm_id IS NOT NULL) AND (controller_account_id IS NULL) AND (recipient_service_id IS NULL) AND (source_account_artifact_kind IS NULL) AND (source_account_artifact_id IS NULL)) OR ((source_event_id IS NULL) AND (realm_id IS NULL) AND (controller_account_id IS NOT NULL) AND (recipient_service_id IS NOT NULL) AND (source_account_artifact_kind = 'agent_runtime_approval'::text) AND (source_account_artifact_id IS NOT NULL))),
    CONSTRAINT notifications_projection_action_check CHECK ((projection_action IS NULL) OR (projection_action = ANY (ARRAY['add'::text, 'update'::text, 'remove'::text])))
);

CREATE INDEX notifications_recipient_idx ON public.notifications USING btree (recipient_id, created_at DESC);

CREATE UNIQUE INDEX notifications_event_source_key ON public.notifications USING btree (recipient_id, source_event_id, notification_kind) WHERE (source_event_id IS NOT NULL);

CREATE UNIQUE INDEX notifications_account_artifact_key ON public.notifications USING btree (controller_account_id, recipient_service_id, source_account_artifact_kind, source_account_artifact_id) WHERE (controller_account_id IS NOT NULL);

CREATE INDEX notifications_account_position_idx ON public.notifications USING btree (controller_account_id, recipient_service_id, projection_position) WHERE (controller_account_id IS NOT NULL);

CREATE INDEX notifications_source_idx ON public.notifications USING btree (source_event_id);

CREATE INDEX notifications_strand_idx ON public.notifications USING btree (strand_id);

CREATE FUNCTION public.project_agent_runtime_approval_notification() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    delta_action text;
    terminal_reason text;
    notification_id uuid;
    account_id uuid;
    service_id text;
    recipient_id text;
    artifact_id text;
    notification_data jsonb;
BEGIN
    IF NEW.approval_request_id IS NOT NULL
       AND NEW.approval_notification_id IS NOT NULL
       AND NEW.controller_account_id IS NOT NULL
       AND NEW.recipient_service_id IS NOT NULL THEN
        delta_action := CASE
            WHEN TG_OP = 'INSERT' OR OLD.approval_request_id IS NULL THEN 'add'
            ELSE 'update'
        END;
        notification_id := NEW.approval_notification_id;
        account_id := NEW.controller_account_id;
        service_id := NEW.recipient_service_id;
        recipient_id := NEW.controller_id;
        artifact_id := NEW.approval_request_id;
        notification_data := jsonb_build_object(
            'kind', 'agent_runtime_approval',
            'approval_request_id', NEW.approval_request_id,
            'agent_id', NEW.id,
            'requested_at', to_char(NEW.approval_requested_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
            'expires_at', to_char(NEW.pairing_expires_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
        );
    ELSIF TG_OP = 'UPDATE'
          AND OLD.approval_request_id IS NOT NULL
          AND NEW.approval_request_id IS NULL THEN
        terminal_reason := CASE
            WHEN NEW.state = 'deactivated' THEN 'deactivated'
            WHEN NEW.authorized_event_ref IS DISTINCT FROM OLD.authorized_event_ref
                 AND NEW.authorized_event_ref IS NOT NULL THEN 'approved'
            WHEN NEW.pairing_request_id IS DISTINCT FROM OLD.pairing_request_id THEN 'renewed'
            WHEN NEW.pairing_expires_at IS NOT NULL
                 AND NEW.pairing_expires_at <= NEW.updated_at THEN 'expired'
            ELSE 'superseded'
        END;
        delta_action := 'remove';
        notification_id := OLD.approval_notification_id;
        account_id := OLD.controller_account_id;
        service_id := OLD.recipient_service_id;
        recipient_id := OLD.controller_id;
        artifact_id := OLD.approval_request_id;
        notification_data := jsonb_build_object(
            'kind', 'agent_runtime_approval',
            'reason', terminal_reason
        );
    ELSE
        RETURN NEW;
    END IF;

    INSERT INTO public.notifications (
        id, recipient_id, controller_account_id, recipient_service_id,
        source_account_artifact_kind, source_account_artifact_id,
        notification_kind, priority, state, projection_action,
        projection_data, created_at, updated_at
    ) VALUES (
        notification_id, recipient_id, account_id, service_id,
        'agent_runtime_approval', artifact_id,
        'agent', 'normal', 'unread', delta_action,
        notification_data, now(), now()
    )
    ON CONFLICT (controller_account_id, recipient_service_id,
                 source_account_artifact_kind, source_account_artifact_id)
        WHERE controller_account_id IS NOT NULL
    DO UPDATE SET
        projection_action = EXCLUDED.projection_action,
        projection_data = EXCLUDED.projection_data,
        projection_position = CASE
            WHEN notifications.projection_action IS DISTINCT FROM EXCLUDED.projection_action
              OR notifications.projection_data IS DISTINCT FROM EXCLUDED.projection_data
            THEN nextval('public.notification_projection_position_seq')
            ELSE notifications.projection_position
        END,
        updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER agent_runtime_approval_notification_projection
AFTER INSERT OR UPDATE ON public.agent_principals
FOR EACH ROW EXECUTE FUNCTION public.project_agent_runtime_approval_notification();

CREATE TABLE public.pending_agent_drafts (
    id uuid PRIMARY KEY,
    agent_id text NOT NULL,
    controller_id text NOT NULL,
    draft_payload jsonb NOT NULL,
    state text DEFAULT 'pending'::text NOT NULL,
    proposed_at timestamp with time zone NOT NULL,
    decided_at timestamp with time zone,
    decided_by_id text,
    CONSTRAINT pending_agent_drafts_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'expired'::text])))
);

CREATE INDEX pending_agent_drafts_controller_idx ON public.pending_agent_drafts USING btree (controller_id);

CREATE INDEX pending_agent_drafts_principal_idx ON public.pending_agent_drafts USING btree (agent_id);

CREATE INDEX pending_agent_drafts_state_idx ON public.pending_agent_drafts USING btree (state);

ALTER TABLE ONLY public.pending_agent_drafts
    ADD CONSTRAINT pending_agent_drafts_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent_principals(id) ON DELETE CASCADE;

CREATE TABLE public.policy_documents (
    id uuid PRIMARY KEY,
    owner_id text NOT NULL,
    scope text NOT NULL,
    subject_ref text NOT NULL,
    policy_kind text NOT NULL,
    document jsonb NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    signed_by_id text,
    active boolean DEFAULT true NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX policy_documents_owner_idx ON public.policy_documents USING btree (owner_id);

CREATE INDEX policy_documents_scope_subject_idx ON public.policy_documents USING btree (scope, subject_ref, policy_kind);

CREATE TABLE public.projection_circle_members (
    pk bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    circle_pk bigint NOT NULL,
    actor_id text NOT NULL,
    state text DEFAULT 'active'::text NOT NULL,
    invited_at timestamp with time zone,
    joined_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT projection_circle_members_state_check CHECK ((state = ANY (ARRAY['invited'::text, 'active'::text, 'removed'::text, 'banned'::text, 'left'::text])))
);

ALTER TABLE ONLY public.projection_circle_members
    ADD CONSTRAINT projection_circle_members_circle_pk_actor_id_key UNIQUE (circle_pk, actor_id);

CREATE INDEX projection_circle_members_actor_idx ON public.projection_circle_members USING btree (actor_id);

CREATE TABLE public.projection_circles (
    pk bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id bytea NOT NULL CHECK (octet_length(id) = 33),
    realm_id text NOT NULL,
    profile_ref text,
    title text NOT NULL,
    summary text,
    display jsonb NOT NULL,
    directory_visibility text DEFAULT 'members'::text NOT NULL,
    join_rule text DEFAULT 'invite'::text NOT NULL,
    history_visibility text DEFAULT 'joined'::text NOT NULL,
    content_encryption_floor text,
    metadata_encryption_floor text,
    encryption_profile text DEFAULT 'mls_rfc9420'::text NOT NULL,
    mls_group_ref text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by_id text NOT NULL,
    updated_by_id text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT projection_circles_content_encryption_floor_check CHECK ((content_encryption_floor = ANY (ARRAY['allow_plaintext'::text, 'e2ee_required'::text]))),
    CONSTRAINT projection_circles_directory_visibility_check CHECK ((directory_visibility = ANY (ARRAY['members'::text, 'realm_members'::text]))),
    CONSTRAINT projection_circles_join_rule_check CHECK ((join_rule = ANY (ARRAY['invite'::text, 'request'::text, 'open'::text]))),
    CONSTRAINT projection_circles_metadata_encryption_floor_check CHECK ((metadata_encryption_floor = ANY (ARRAY['allow_plaintext'::text, 'e2ee_required'::text]))),
    CONSTRAINT projection_circles_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'tombstoned'::text])))
);

ALTER TABLE ONLY public.projection_circles
    ADD CONSTRAINT projection_circles_id_key UNIQUE (id);

CREATE INDEX projection_circles_realm_idx ON public.projection_circles USING btree (realm_id);

CREATE INDEX projection_circles_state_idx ON public.projection_circles USING btree (state);

ALTER TABLE ONLY public.projection_circle_members
    ADD CONSTRAINT projection_circle_members_circle_pk_fkey FOREIGN KEY (circle_pk) REFERENCES public.projection_circles(pk) ON DELETE CASCADE;

-- Materialized projection of an admitted canonical Event. The Event identity
-- lives in exactly one place -- `canonical_events.id` -- and is reached from
-- here through `event_pk`; the row does not carry a second copy of the
-- 33-octet id, because two identity columns in the same row cannot be kept
-- coherent by any constraint. `UNIQUE (event_pk)` is the projection identity:
-- one projected row per admitted Event. The surrogate `pk` is only a local
-- stream position.
CREATE TABLE public.projection_events (
    pk bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_pk bigint NOT NULL REFERENCES public.canonical_events(pk) ON DELETE RESTRICT,
    realm_pk bigint NOT NULL REFERENCES public.canonical_realms(pk) ON DELETE RESTRICT,
    realm_id text NOT NULL,
    event_kind text NOT NULL,
    operation_kind text NOT NULL,
    operation_id uuid,
    sender_id text,
    payload jsonb NOT NULL,
    received_at timestamp with time zone NOT NULL DEFAULT now(),
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT projection_events_event_pk_key UNIQUE (event_pk)
);

CREATE INDEX projection_events_created_at_idx ON public.projection_events USING btree (created_at);

CREATE INDEX projection_events_received_at_idx ON public.projection_events USING btree (received_at);

CREATE INDEX projection_events_stream_order_idx ON public.projection_events USING btree (received_at, pk);

CREATE INDEX projection_events_space_idx ON public.projection_events USING btree (realm_id);

CREATE INDEX projection_events_realm_pk_idx ON public.projection_events USING btree (realm_pk, pk);

CREATE TABLE public.projection_strand_watches (
    pk bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    strand_pk bigint NOT NULL,
    actor_id text NOT NULL,
    level text,
    level_public boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT projection_strand_watches_level_check CHECK (((level IS NULL) OR (level = ANY (ARRAY['mentions_only'::text, 'participating'::text, 'all'::text, 'muted'::text]))))
);

ALTER TABLE ONLY public.projection_strand_watches
    ADD CONSTRAINT projection_strand_watches_strand_pk_actor_id_key UNIQUE (strand_pk, actor_id);

CREATE INDEX projection_strand_watches_actor_idx ON public.projection_strand_watches USING btree (actor_id) WHERE ((level IS NOT NULL) AND (level <> 'mentions_only'::text));

CREATE INDEX projection_strand_watches_strand_idx ON public.projection_strand_watches USING btree (strand_pk) WHERE ((level IS NOT NULL) AND (level <> 'mentions_only'::text));

CREATE TABLE public.projection_strands (
    pk bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id bytea NOT NULL CHECK (octet_length(id) = 33),
    realm_id text NOT NULL,
    scope_circle_id bytea CHECK (octet_length(scope_circle_id) = 33),
    tracks jsonb DEFAULT '{"synthesis": {}}'::jsonb NOT NULL,
    title text NOT NULL,
    summary text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by_id text NOT NULL,
    history_basis_seals jsonb DEFAULT '[]'::jsonb NOT NULL,
    updated_by_id text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT projection_strands_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'redacted'::text])))
);

ALTER TABLE ONLY public.projection_strands
    ADD CONSTRAINT projection_strands_id_key UNIQUE (id);

CREATE INDEX projection_strands_realm_idx ON public.projection_strands USING btree (realm_id);

CREATE INDEX projection_strands_scope_circle_id_idx ON public.projection_strands USING btree (scope_circle_id);

CREATE INDEX projection_strands_state_idx ON public.projection_strands USING btree (state);

ALTER TABLE ONLY public.projection_strand_watches
    ADD CONSTRAINT projection_strand_watches_strand_pk_fkey FOREIGN KEY (strand_pk) REFERENCES public.projection_strands(pk) ON DELETE CASCADE;

CREATE TABLE public.projection_morphs (
    pk bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id bytea NOT NULL CHECK (octet_length(id) = 33),
    realm_id text NOT NULL,
    morph_kind text NOT NULL,
    title text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by_id text NOT NULL,
    history_basis_seals jsonb DEFAULT '[]'::jsonb NOT NULL,
    updated_by_id text,
    fields jsonb DEFAULT '{}'::jsonb NOT NULL,
    schema_refs jsonb DEFAULT '[]'::jsonb NOT NULL,
    facets jsonb DEFAULT '[]'::jsonb NOT NULL,
    versions jsonb DEFAULT '[]'::jsonb NOT NULL,
    scope_circle_id bytea CHECK (octet_length(scope_circle_id) = 33),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT projection_morphs_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'redacted'::text])))
);

ALTER TABLE ONLY public.projection_morphs
    ADD CONSTRAINT projection_morphs_id_key UNIQUE (id);

CREATE INDEX projection_morphs_realm_idx ON public.projection_morphs USING btree (realm_id);

CREATE INDEX projection_morphs_scope_circle_id_idx ON public.projection_morphs USING btree (scope_circle_id);

CREATE INDEX projection_morphs_state_idx ON public.projection_morphs USING btree (state);

CREATE INDEX projection_morphs_type_idx ON public.projection_morphs USING btree (morph_kind);

CREATE TABLE public.projection_spaces (
    pk bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id bytea NOT NULL CHECK (octet_length(id) = 33),
    realm_id text NOT NULL,
    scope_circle_id bytea CHECK (octet_length(scope_circle_id) = 33),
    child_scope_policy text,
    child_scope_policy_scope_circle_id bytea CHECK (octet_length(child_scope_policy_scope_circle_id) = 33),
    kind text NOT NULL,
    title text NOT NULL,
    fields jsonb DEFAULT '{}'::jsonb NOT NULL,
    parent_ref bytea CHECK (octet_length(parent_ref) = 33),
    rank text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by_id text NOT NULL,
    history_basis_seals jsonb DEFAULT '[]'::jsonb NOT NULL,
    updated_by_id text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT projection_spaces_child_scope_policy_check CHECK ((child_scope_policy = ANY (ARRAY['allow_any'::text, 'require_e2ee'::text, 'require_same_scope'::text, 'require_scope_circle_id'::text]))),
    CONSTRAINT projection_spaces_child_scope_policy_scope_check CHECK (((child_scope_policy <> 'require_scope_circle_id'::text) OR (child_scope_policy_scope_circle_id IS NOT NULL))),
    CONSTRAINT projection_spaces_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'tombstoned'::text])))
);

ALTER TABLE ONLY public.projection_spaces
    ADD CONSTRAINT projection_spaces_id_key UNIQUE (id);

CREATE INDEX projection_spaces_parent_idx ON public.projection_spaces USING btree (parent_ref) WHERE (parent_ref IS NOT NULL);

CREATE INDEX projection_spaces_realm_idx ON public.projection_spaces USING btree (realm_id);

CREATE INDEX projection_spaces_scope_circle_id_idx ON public.projection_spaces USING btree (scope_circle_id);

CREATE INDEX projection_spaces_state_idx ON public.projection_spaces USING btree (state);

-- Keyed by `bridge_describe_url`: the describe endpoint IS the cache key, so
-- the row does not also carry it under a second `id` alias.
CREATE TABLE public.push_bridge_cache (
    push_gateway_url text NOT NULL,
    service_base_url text NOT NULL,
    bridge_describe_url text PRIMARY KEY,
    fetch_state text NOT NULL,
    cache_state text NOT NULL,
    contract_digest text NOT NULL,
    fetched_at timestamp with time zone NOT NULL,
    remote_contract jsonb NOT NULL,
    trust_level text DEFAULT 'pending'::text NOT NULL,
    freshness_at timestamp with time zone DEFAULT now() NOT NULL,
    etag text DEFAULT ''::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX push_bridge_cache_fetched_at_idx ON public.push_bridge_cache USING btree (fetched_at);

CREATE INDEX push_bridge_cache_trust_freshness_idx ON public.push_bridge_cache USING btree (trust_level, freshness_at);

CREATE TABLE public.push_devices (
    id text PRIMARY KEY,
    actor_id text,
    device_id text NOT NULL,
    push_gateway text NOT NULL,
    push_key text NOT NULL,
    platform text,
    app_id text,
    payload jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.realm_invites (
    pk bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id bytea NOT NULL CHECK (octet_length(id) = 33),
    realm_id text NOT NULL,
    inviter_id text NOT NULL,
    invitee_id text,
    invite_delivery_target jsonb,
    introduction_evidence_digest text,
    third_party_id jsonb,
    join_rule_snapshot jsonb,
    invite_token text NOT NULL,
    status text NOT NULL,
    claim_nonces jsonb DEFAULT '{}'::jsonb NOT NULL,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone
);

ALTER TABLE ONLY public.realm_invites
    ADD CONSTRAINT realm_invites_id_key UNIQUE (id);

CREATE INDEX realm_invites_invitee_idx ON public.realm_invites USING btree (invitee_id);

CREATE UNIQUE INDEX realm_invites_live_direct_unique_idx ON public.realm_invites USING btree (realm_id, invitee_id) WHERE ((invitee_id IS NOT NULL) AND (third_party_id IS NULL) AND (status = ANY (ARRAY['pending'::text, 'claimed'::text, 'send_failed'::text])));

CREATE INDEX realm_invites_realm_idx ON public.realm_invites USING btree (realm_id);

CREATE TABLE public.recovery_policies (
    id uuid PRIMARY KEY,
    principal_id text NOT NULL,
    version integer NOT NULL,
    acceptance_basis jsonb NOT NULL,
    trust_domain text NOT NULL,
    allowed_proof_kinds text[] NOT NULL,
    supersedes uuid,
    expires_at timestamp with time zone,
    issued_at timestamp with time zone NOT NULL,
    verification_method text NOT NULL,
    raw_payload jsonb NOT NULL,
    accepted_at timestamp with time zone NOT NULL,
    CONSTRAINT recovery_policies_version_check CHECK ((version >= 1))
);

ALTER TABLE ONLY public.recovery_policies
    ADD CONSTRAINT recovery_policies_principal_id_version_key UNIQUE (principal_id, version);

CREATE INDEX recovery_policies_principal_active_idx ON public.recovery_policies USING btree (principal_id, version DESC);

ALTER TABLE ONLY public.recovery_policies
    ADD CONSTRAINT recovery_policies_supersedes_fkey FOREIGN KEY (supersedes) REFERENCES public.recovery_policies(id);

CREATE TABLE public.recovery_sessions (
    id uuid PRIMARY KEY,
    principal_id text NOT NULL,
    requesting_device_id text NOT NULL,
    trust_domain text NOT NULL,
    policy_id uuid NOT NULL,
    policy_version integer NOT NULL,
    identity_model text NOT NULL,
    ssk_generation bigint,
    current_device_generation_ref text,
    device_generation_status text,
    registry_head text,
    accepted_seal_frontier jsonb,
    policy_payload jsonb NOT NULL,
    publication_authority_context jsonb NOT NULL,
    publication_authority_context_digest text NOT NULL,
    challenge text NOT NULL,
    state text DEFAULT 'pending'::text NOT NULL,
    proof_payload jsonb,
    transaction_id uuid,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT recovery_sessions_policy_version_check CHECK ((policy_version >= 1)),
    CONSTRAINT recovery_sessions_identity_model_check CHECK ((identity_model = ANY (ARRAY['cross_signing'::text, 'enrollment_authority'::text]))),
    CONSTRAINT recovery_sessions_generation_shape_check CHECK ((((identity_model = 'cross_signing'::text) AND (ssk_generation >= 1) AND (current_device_generation_ref IS NULL) AND (device_generation_status IS NULL) AND (registry_head IS NULL) AND (accepted_seal_frontier IS NULL)) OR ((identity_model = 'enrollment_authority'::text) AND (ssk_generation IS NULL) AND (current_device_generation_ref IS NOT NULL) AND (device_generation_status = ANY (ARRAY['active'::text, 'conflicted'::text])) AND (registry_head IS NOT NULL)))),
    CONSTRAINT recovery_sessions_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'verified'::text, 'completed'::text, 'rejected'::text, 'expired'::text]))),
    CONSTRAINT recovery_sessions_transaction_id_key UNIQUE (transaction_id)
);

CREATE INDEX recovery_sessions_principal_idx ON public.recovery_sessions USING btree (principal_id);

CREATE TABLE public.security_transactions (
    id uuid NOT NULL,
    kind text NOT NULL,
    principal_id text NOT NULL,
    coordinator_service_id text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    request_digest text NOT NULL,
    binding jsonb NOT NULL,
    prepared_plan jsonb NOT NULL,
    prepared_plan_digest text NOT NULL,
    state text NOT NULL,
    accepted_steps jsonb NOT NULL,
    next_required_step text,
    terminal_result jsonb,
    canonical_request bytea NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT security_transactions_pkey PRIMARY KEY (id),
    CONSTRAINT security_transactions_kind_check CHECK ((kind = ANY (ARRAY['recovery'::text, 'security_rotation'::text]))),
    CONSTRAINT security_transactions_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'running'::text, 'awaiting_device_attestation'::text, 'completed'::text, 'aborted'::text, 'expired'::text])))
);

ALTER TABLE ONLY public.recovery_sessions
    ADD CONSTRAINT recovery_sessions_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.security_transactions(id);

CREATE INDEX security_transactions_principal_state_idx ON public.security_transactions USING btree (principal_id, state, created_at DESC);

CREATE TABLE public.security_transaction_backup_erase_progress (
    transaction_id uuid NOT NULL,
    canonical_request bytea NOT NULL,
    outcome jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT security_transaction_backup_erase_progress_pkey PRIMARY KEY (transaction_id),
    CONSTRAINT security_transaction_backup_erase_progress_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.security_transactions(id) ON DELETE CASCADE
);

CREATE TABLE public.security_transaction_step_outcomes (
    transaction_id uuid NOT NULL,
    step text NOT NULL,
    canonical_request bytea NOT NULL,
    response jsonb NOT NULL,
    participant_outcome jsonb,
    CONSTRAINT security_transaction_step_outcomes_pkey PRIMARY KEY (transaction_id, step),
    CONSTRAINT security_transaction_step_outcomes_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.security_transactions(id) ON DELETE CASCADE
);

CREATE TABLE public.security_transaction_step_attempts (
    transaction_id uuid NOT NULL,
    step text NOT NULL,
    canonical_request bytea NOT NULL,
    CONSTRAINT security_transaction_step_attempts_pkey PRIMARY KEY (transaction_id, step),
    CONSTRAINT security_transaction_step_attempts_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.security_transactions(id) ON DELETE CASCADE
);

CREATE TABLE public.sessions (
    id text PRIMARY KEY,
    actor_id text NOT NULL,
    device_id text NOT NULL,
    audience text NOT NULL,
    session_public_key text,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX sessions_actor_device_idx ON public.sessions USING btree (actor_id, device_id, expires_at) WHERE (revoked_at IS NULL);

CREATE TABLE public.space_members (
    id uuid PRIMARY KEY,
    realm_id text NOT NULL,
    actor_id text NOT NULL,
    membership text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    joined_at timestamp with time zone,
    left_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.space_members
    ADD CONSTRAINT space_members_realm_id_actor_key UNIQUE (realm_id, actor_id);

CREATE INDEX space_members_actor_idx ON public.space_members USING btree (actor_id, membership, realm_id);

CREATE TABLE public.space_state_events (
    id uuid PRIMARY KEY,
    realm_id text NOT NULL,
    event_type text NOT NULL,
    subject text DEFAULT ''::text NOT NULL,
    sender_id text,
    operation_id uuid,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX space_state_events_lookup_idx ON public.space_state_events USING btree (realm_id, event_type, subject, created_at);

CREATE TABLE public.spaces (
    pk bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    realm_pk bigint NOT NULL REFERENCES public.canonical_realms(pk) ON DELETE RESTRICT,
    realm_id text NOT NULL,
    title text NOT NULL,
    summary text,
    owner_id text,
    discoverability text DEFAULT 'invite_only'::text NOT NULL,
    payload jsonb NOT NULL,
    history_visibility text DEFAULT 'joined'::text NOT NULL,
    history_sharing_policy jsonb,
    history_sharing_policy_digest text,
    preview_policy jsonb,
    preview_policy_digest text,
    encryption_profile text DEFAULT 'mls_rfc9420'::text NOT NULL,
    plaintext_visible_services jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT spaces_encryption_profile_check CHECK ((encryption_profile = ANY (ARRAY['none'::text, 'plaintext'::text, 'mls_rfc9420'::text]))),
    CONSTRAINT spaces_history_visibility_check CHECK ((history_visibility = ANY (ARRAY['world_readable'::text, 'shared'::text, 'invited'::text, 'joined'::text, 'restricted'::text]))),
    CONSTRAINT spaces_realm_pk_key UNIQUE (realm_pk),
    CONSTRAINT spaces_realm_id_key UNIQUE (realm_id)
);

CREATE INDEX spaces_discoverability_updated_idx ON public.spaces USING btree (discoverability, updated_at, pk);

CREATE INDEX spaces_history_sharing_policy_digest_idx ON public.spaces USING btree (history_sharing_policy_digest) WHERE (history_sharing_policy_digest IS NOT NULL);

CREATE INDEX spaces_history_visibility_updated_idx ON public.spaces USING btree (history_visibility, updated_at, pk);

CREATE INDEX spaces_preview_policy_digest_idx ON public.spaces USING btree (preview_policy_digest) WHERE (preview_policy_digest IS NOT NULL);

CREATE TABLE public.sync_cursor_handles (
    id text PRIMARY KEY,
    principal_id text,
    device_id text,
    service_id text NOT NULL,
    filter_digest text,
    purpose text NOT NULL,
    positions jsonb,
    target jsonb,
    issued_at_ms bigint NOT NULL,
    expires_at_ms bigint NOT NULL,
    CONSTRAINT sync_cursor_handles_purpose_check CHECK ((purpose = ANY (ARRAY['stream'::text, 'barrier'::text])))
);

CREATE INDEX sync_cursor_handles_expiry_idx ON public.sync_cursor_handles USING btree (expires_at_ms);

CREATE INDEX sync_cursor_handles_stream_idx ON public.sync_cursor_handles USING btree (principal_id, device_id, filter_digest);

CREATE TABLE public.sync_cursor_revocations (
    id uuid PRIMARY KEY,
    cursor_digest text NOT NULL,
    principal_id text NOT NULL,
    device_id text,
    scope text NOT NULL,
    reason_code text NOT NULL,
    revoked_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT sync_cursor_revocations_scope_check CHECK ((scope = ANY (ARRAY['this_cursor'::text, 'same_device'::text, 'same_session'::text])))
);

CREATE INDEX sync_cursor_revocations_expiry_idx ON public.sync_cursor_revocations USING btree (expires_at);

CREATE TABLE public.websocket_auth_challenges (
    connection_id text NOT NULL,
    nonce text NOT NULL,
    canonical_origin text NOT NULL,
    canonical_base_url text NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed boolean NOT NULL DEFAULT false,
    retain_until timestamp with time zone NOT NULL,
    CONSTRAINT websocket_auth_challenges_pkey PRIMARY KEY (connection_id, nonce)
);

CREATE INDEX websocket_auth_challenges_retain_until_idx ON public.websocket_auth_challenges (retain_until);

CREATE TABLE public.websocket_auth_replay_ledger (
    cnf_jkt text NOT NULL,
    jti text NOT NULL,
    proof_context text NOT NULL,
    consumed_at timestamp with time zone NOT NULL,
    retain_until timestamp with time zone NOT NULL,
    CONSTRAINT websocket_auth_replay_ledger_pkey PRIMARY KEY (cnf_jkt, jti, proof_context)
);

CREATE INDEX websocket_auth_replay_ledger_retain_until_idx ON public.websocket_auth_replay_ledger (retain_until);

CREATE TABLE public.idempotency_keys (
    principal_id text NOT NULL,
    idempotency_key text NOT NULL,
    service_id text NOT NULL,
    request_hash text NOT NULL,
    response_status integer NOT NULL,
    response_body jsonb NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT idempotency_keys_pkey PRIMARY KEY (principal_id, idempotency_key)
);

CREATE INDEX idempotency_keys_expiry_idx ON public.idempotency_keys USING btree (expires_at);

CREATE TABLE public.control_proposal_authority_acks (
    ack_key text PRIMARY KEY,
    request_hash text NOT NULL,
    response_body jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.webrtc_sessions (
    id uuid PRIMARY KEY,
    realm_id text NOT NULL,
    initiator_id text NOT NULL,
    ice_config jsonb DEFAULT '{}'::jsonb NOT NULL,
    signaling_state jsonb NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX webrtc_sessions_expires_idx ON public.webrtc_sessions USING btree (expires_at);

CREATE INDEX webrtc_sessions_space_idx ON public.webrtc_sessions USING btree (realm_id);

CREATE TABLE public.webvh_documents (
    id text PRIMARY KEY,
    did_document jsonb NOT NULL,
    key_log_head text,
    seq bigint DEFAULT 0 NOT NULL,
    method_evidence jsonb DEFAULT '{}'::jsonb NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone DEFAULT (now() + '00:15:00'::interval) NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX webvh_documents_expires_at_idx ON public.webvh_documents USING btree (expires_at);

CREATE TABLE public.webvh_log_events (
    id text PRIMARY KEY,
    did text NOT NULL,
    seq bigint NOT NULL,
    operation jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.webvh_log_events
    ADD CONSTRAINT webvh_log_events_did_seq_key UNIQUE (did, seq);

CREATE INDEX webvh_log_events_did_seq_idx ON public.webvh_log_events USING btree (did, seq);

-- The deployment's own authoritative service identity (identity-did.md §3.7).
-- Singleton: at most one row keyed by the fixed id 'self'. `identity` is the
-- SDK StoredServiceIdentity document: public DID/receipt evidence plus opaque
-- KeyRefs. Private signing and WebVH control seeds MUST remain in the selected
-- Secrets/KeyStore backend and MUST NOT be copied into PostgreSQL.
CREATE TABLE public.service_identity (
    id text PRIMARY KEY,
    identity jsonb NOT NULL
);

CREATE TABLE public.service_identity_registrations (
    service_kind text NOT NULL,
    public_base text NOT NULL,
    service_id text NOT NULL,
    version_id text NOT NULL,
    inception_digest text NOT NULL,
    outcome jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT service_identity_registrations_pkey PRIMARY KEY (service_kind, public_base),
    CONSTRAINT service_identity_registrations_service_id_key UNIQUE (service_id)
);

CREATE TABLE public.event_federation_outbox (
    event_pk bigint NOT NULL REFERENCES public.canonical_events(pk) ON DELETE RESTRICT,
    outbox_id text NOT NULL REFERENCES public.federation_outbox(id) ON DELETE CASCADE,
    PRIMARY KEY (event_pk, outbox_id)
);

-- `event_pk` is already the primary key prefix; `outbox_id` is the CASCADE side
-- and needs its own index or every outbox delete scans this table.
CREATE INDEX event_federation_outbox_outbox_id_idx
    ON public.event_federation_outbox USING btree (outbox_id);
CREATE TABLE public.direct_conversation_founding_slots (
    founder_id text NOT NULL,
    trust_domain_id text NOT NULL,
    pair_key text NOT NULL,
    founding_unit_digest text NOT NULL,
    realm_id text NOT NULL,
    main_strand_id text NOT NULL,
    event_ids jsonb NOT NULL,
    idempotency_key text NOT NULL,
    receipt_bytes bytea NOT NULL,
    accepted_at timestamptz NOT NULL,
    PRIMARY KEY (founder_id, trust_domain_id, pair_key),
    UNIQUE (founder_id, idempotency_key)
);

CREATE TABLE public.direct_conversation_founding_equivocations (
    id bigserial PRIMARY KEY,
    founder_id text NOT NULL,
    trust_domain_id text NOT NULL,
    pair_key text NOT NULL,
    committed_unit_digest text NOT NULL,
    conflicting_unit_digest text NOT NULL,
    idempotency_key text NOT NULL,
    observed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.device_bootstrap_decisions (
    account_authority_id text NOT NULL,
    transaction_id text NOT NULL,
    decision text NOT NULL CHECK (decision IN ('accepted', 'cancelled', 'expired')),
    binding_digest text NOT NULL,
    canonical_outcome_bytes text NOT NULL,
    receipt jsonb NOT NULL,
    decided_at timestamptz NOT NULL,
    PRIMARY KEY (account_authority_id, transaction_id)
);

-- v1 terminal decision rows are retention tombstones. Deliberately no expiry
-- column and no cascading foreign key: cleanup must never make a terminal
-- founding transaction appear undecided again.
