-- Squashed initial migration (soland).
-- Final schema as of 2026-06-10, consolidated from the previous migration chain
-- (generated by applying all historical migrations and dumping the resulting schema).

CREATE TABLE public.account_datas (
    id uuid NOT NULL,
    actor_id text NOT NULL,
    data_type text NOT NULL,
    payload jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.accounts (
    id uuid NOT NULL,
    principal_id text NOT NULL,
    display_name text,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    disabled_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.account_localparts (
    id uuid NOT NULL,
    account_id uuid NOT NULL,
    localpart text NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.account_lifecycle (
    principal_id text NOT NULL,
    state text NOT NULL,
    reason text,
    changed_by text,
    changed_at timestamp with time zone NOT NULL,
    CONSTRAINT account_lifecycle_state_check CHECK ((state = ANY (ARRAY['active'::text, 'locked'::text, 'suspended'::text, 'deactivated'::text, 'erasure_pending'::text])))
);

CREATE TABLE public.handle_releases (
    localpart text NOT NULL,
    released_at timestamp with time zone NOT NULL
);

CREATE TABLE public.agent_keys (
    id uuid NOT NULL,
    agent_id text NOT NULL,
    verification_method text NOT NULL,
    state text DEFAULT 'authorized'::text NOT NULL,
    authorized_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    revocation_reason text,
    CONSTRAINT agent_keys_state_check CHECK ((state = ANY (ARRAY['authorized'::text, 'revoked'::text])))
);

CREATE TABLE public.agent_participation (
    id uuid NOT NULL,
    agent_id text NOT NULL,
    scope_kind text NOT NULL,
    scope_key text NOT NULL,
    realm_id uuid NOT NULL,
    scope jsonb NOT NULL,
    reply boolean DEFAULT false NOT NULL,
    accept_third_party_mention boolean DEFAULT false NOT NULL,
    act_on_behalf boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT agent_participation_scope_kind_check CHECK ((scope_kind = ANY (ARRAY['realm'::text, 'circle'::text, 'strand'::text])))
);

CREATE TABLE public.agent_participation_ceiling (
    scope_kind text NOT NULL,
    id text NOT NULL,
    realm_id uuid NOT NULL,
    reply boolean DEFAULT false NOT NULL,
    accept_third_party_mention boolean DEFAULT false NOT NULL,
    act_on_behalf boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT agent_participation_ceiling_scope_kind_check CHECK ((scope_kind = ANY (ARRAY['realm'::text, 'circle'::text, 'strand'::text])))
);

CREATE TABLE public.agent_principals (
    id text NOT NULL,
    controller_id text NOT NULL,
    principal_control_realm_id text NOT NULL,
    controller_authorization_ref text NOT NULL,
    display_name text,
    agent_slug text,
    avatar_blob_ref text,
    state text DEFAULT 'active'::text NOT NULL,
    requested_scope jsonb,
    accountability jsonb,
    provision_event_refs jsonb,
    pairing_request_id text,
    paired_pairing_request_id text,
    paired_request_digest text,
    pairing_code text,
    pairing_expires_at timestamp with time zone,
    approval_request_id text,
    controller_account_id uuid,
    recipient_service_id text,
    runtime_key_binding_digest text,
    runtime_public_key_digest text,
    runtime_attestation_digest text,
    approval_notification_id uuid,
    runtime_key_request jsonb,
    approval_requested_at timestamp with time zone,
    authorized_event_ref text,
    authorized_verification_method text,
    authorized_public_key_digest text,
    state_changed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT agent_principals_id_check CHECK (((id ~~ 'did:%'::text) AND (id !~ '[[:space:]#?]'::text))),
    CONSTRAINT agent_principals_pcr_id_check CHECK ((principal_control_realm_id ~ '^ak:realm:[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'::text)),
    CONSTRAINT agent_principals_controller_authorization_ref_check CHECK ((controller_authorization_ref ~~ (id || '#%'::text))),
    CONSTRAINT agent_principals_agent_slug_check CHECK ((agent_slug IS NULL) OR ((char_length(agent_slug) BETWEEN 1 AND 64) AND (octet_length(agent_slug) <= 256) AND (agent_slug !~ '[[:space:][:cntrl:]]'::text) AND (strpos(agent_slug, ':'::text) = 0) AND (strpos(agent_slug, '@'::text) = 0) AND (strpos(agent_slug, '/'::text) = 0) AND (strpos(agent_slug, '#'::text) = 0) AND (strpos(agent_slug, '?'::text) = 0) AND (strpos(agent_slug, E'\\') = 0))),
    CONSTRAINT agent_principals_state_check CHECK ((state = ANY (ARRAY['pending_runtime_key'::text, 'active'::text, 'paused'::text, 'deactivated'::text, 'pairing_expired'::text])))
);

CREATE TABLE public.agent_sidecars (
    id uuid PRIMARY KEY,
    realm_id uuid NOT NULL,
    controller_id text NOT NULL,
    backing_circle_id uuid NOT NULL UNIQUE,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT agent_sidecars_realm_controller_key UNIQUE (realm_id, controller_id),
    CONSTRAINT agent_sidecars_state_check CHECK ((state = ANY (ARRAY['active'::text, 'suspended'::text, 'tombstoned'::text])))
);

CREATE TABLE public.agent_sidecar_contexts (
    sidecar_id uuid NOT NULL REFERENCES public.agent_sidecars(id) ON DELETE CASCADE,
    normalized_context_ref_digest text NOT NULL,
    normalized_context_ref jsonb NOT NULL,
    private_strand_id uuid NOT NULL UNIQUE,
    private_relation_id uuid NOT NULL UNIQUE,
    created_at timestamp with time zone NOT NULL,
    PRIMARY KEY (sidecar_id, normalized_context_ref_digest)
);

CREATE INDEX agent_sidecars_controller_idx ON public.agent_sidecars USING btree (controller_id, created_at, id);

CREATE TABLE public.agent_sessions (
    id uuid NOT NULL,
    agent_id text NOT NULL,
    verification_method text NOT NULL,
    runtime_attestation jsonb,
    state text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone,
    revoked_at timestamp with time zone,
    CONSTRAINT agent_sessions_state_check CHECK ((state = ANY (ARRAY['active'::text, 'revoked'::text, 'expired'::text])))
);

CREATE TABLE public.applet_registrations (
    id text NOT NULL,
    namespace text NOT NULL,
    owner_actor_id text NOT NULL,
    registry_did text NOT NULL,
    bot_actor_id text NOT NULL,
    portal_realm_id text NOT NULL,
    capabilities jsonb DEFAULT '[]'::jsonb NOT NULL,
    manifest jsonb NOT NULL,
    package jsonb,
    namespaces jsonb,
    allow_ghost_actors boolean DEFAULT false NOT NULL,
    status text NOT NULL,
    registered_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    idempotency_key text,
    install_body_digest text,
    install_id text,
    install_response jsonb,
    install_execution jsonb,
    ghosts jsonb DEFAULT '[]'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT applet_registrations_status_check CHECK ((status = ANY (ARRAY['registered'::text, 'installed'::text, 'partially_installed'::text, 'rejected'::text, 'revoked'::text])))
);

CREATE TABLE public.applet_transactions (
    source_service_id text NOT NULL,
    idempotency_key text NOT NULL,
    source_signature_anchor text NOT NULL,
    request_digest text NOT NULL,
    outcome jsonb,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone
);

CREATE TABLE public.audit_logs (
    id uuid NOT NULL,
    actor_id text,
    request_id uuid,
    action text NOT NULL,
    outcome text NOT NULL,
    realm_id uuid,
    operation_id uuid,
    device_id text,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.backup_series (
    id uuid NOT NULL,
    actor_id text NOT NULL,
    backup_class text NOT NULL,
    head_backup_id uuid,
    head_seq bigint DEFAULT 0 NOT NULL,
    frontier_ref text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    retired_at timestamp with time zone,
    CONSTRAINT backup_series_backup_class_check CHECK ((backup_class = ANY (ARRAY['did_recovery'::text, 'secret_storage'::text, 'mls_history'::text, 'external'::text]))),
    CONSTRAINT backup_series_head_seq_check CHECK ((head_seq >= 0))
);

CREATE TABLE public.blobs (
    id text NOT NULL,
    sha256 text NOT NULL,
    media_type text NOT NULL,
    filename text,
    uploaded_by_id text NOT NULL,
    realm_id uuid,
    size_bytes bigint NOT NULL,
    storage_backend text NOT NULL,
    storage_key text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    retention_expires_at timestamp with time zone,
    legal_hold boolean DEFAULT false NOT NULL,
    redacted boolean DEFAULT false NOT NULL,
    visibility text DEFAULT 'realm_bound'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT blobs_visibility_check CHECK ((visibility = ANY (ARRAY['public'::text, 'realm_bound'::text, 'actor_private'::text, 'device_bound'::text])))
);

-- Realm-broadcast relay for `ak.call.signal` ephemeral envelopes
-- (`webrtc-signaling.md` §5). One row per relayed signed envelope, retained
-- until `expires_at`; receivers pick it up from the subscribe Realm
-- `ephemeral.events` container and verify the carried `proof`. `position`
-- is a monotonic per-Realm deliver-once cursor sourced from
-- `call_signal_relay_position`.
CREATE TABLE public.call_signal_relay (
    id uuid NOT NULL,
    realm_id text NOT NULL,
    position bigint NOT NULL,
    sender_actor text NOT NULL,
    sender_device text NOT NULL,
    call_id text NOT NULL,
    envelope jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

-- Per-Realm monotonic position counter for `call_signal_relay`. Held in a
-- dedicated table (not `MAX(position)` of live rows) so positions keep
-- increasing even after the relay log is pruned, and a deliver-once watermark
-- can never be re-crossed by a recycled position.
CREATE TABLE public.call_signal_relay_position (
    realm_id text NOT NULL,
    next_position bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Per-subscriber-device deliver-once watermark for `call_signal_relay`
-- (`webrtc-signaling.md` §5). Records the highest per-Realm `position` already
-- delivered to a `(actor, device, realm)` triple so an incremental
-- re-subscribe inside the TTL window does not re-emit a signal the device
-- already saw, while a full sync still recovers all non-expired pending
-- signals. Durable so a restart / replica failover preserves the cursor.
CREATE TABLE public.call_signal_relay_watermark (
    actor_id text NOT NULL,
    device_id text NOT NULL,
    realm_id text NOT NULL,
    delivered_through bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Realm-scoped relay for `ak.receipt.read` ephemeral receipt objects. The
-- normalized `receipt` follows `ak.schema.read_receipt.v1`; relay metadata
-- (`position`, `visibility`, `target_actor`, `expires_at`) gates short-TTL
-- fanout through account sync and is not durable Event history.
CREATE TABLE public.read_receipt_relay (
    id uuid NOT NULL,
    realm_id text NOT NULL,
    position bigint NOT NULL,
    actor_id text NOT NULL,
    sender_device text,
    event_id text NOT NULL,
    read_scope jsonb NOT NULL,
    target_actor text,
    visibility text NOT NULL,
    receipt jsonb NOT NULL,
    envelope jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

-- Per-Realm monotonic position counter for `read_receipt_relay`. Kept
-- separate from live rows so pruned positions are never recycled across a
-- deliver-once watermark.
CREATE TABLE public.read_receipt_relay_position (
    realm_id text NOT NULL,
    next_position bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Per-subscriber-device deliver-once watermark for read receipt relay rows.
CREATE TABLE public.read_receipt_relay_watermark (
    actor_id text NOT NULL,
    device_id text NOT NULL,
    realm_id text NOT NULL,
    delivered_through bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.canonical_events (
    id uuid NOT NULL,
    actor_id text NOT NULL,
    actor_seq bigint NOT NULL,
    realm_id uuid,
    kind text NOT NULL,
    schema_id text NOT NULL,
    canonical_digest text NOT NULL,
    canonical_bytes bytea NOT NULL,
    envelope jsonb NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.event_batch_receipts (
    schema text NOT NULL,
    id uuid NOT NULL PRIMARY KEY,
    issuer text NOT NULL,
    scope jsonb NOT NULL,
    frontier jsonb NOT NULL,
    events jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    proofs jsonb NOT NULL,
    event_ids uuid[] NOT NULL
);

CREATE INDEX event_batch_receipts_event_ids_idx
    ON public.event_batch_receipts USING gin (event_ids);

CREATE TABLE public.state_moves (
    id text NOT NULL,
    realm_id text NOT NULL,
    move_json jsonb NOT NULL,
    sealed_by text,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    sealed_at timestamp with time zone
);

CREATE TABLE public.state_seals (
    id text NOT NULL,
    realm_id text NOT NULL,
    seal_json jsonb NOT NULL,
    predecessor_refs jsonb DEFAULT '[]'::jsonb NOT NULL,
    is_genesis boolean DEFAULT false NOT NULL,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.state_cell_ops (
    seq bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    realm_id text NOT NULL,
    seal_id text NOT NULL,
    op_index bigint NOT NULL,
    cell_id text NOT NULL,
    move_id text NOT NULL,
    op_json jsonb NOT NULL,
    appended_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.state_cell_cache (
    realm_id text NOT NULL,
    cell_id text NOT NULL,
    view_hash text NOT NULL,
    state_json jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.consent_cells (
    id uuid NOT NULL,
    holder_id text NOT NULL,
    peer_id text NOT NULL,
    scope text NOT NULL,
    cell_id text NOT NULL,
    requested_at timestamp with time zone,
    grant_dots jsonb DEFAULT '{}'::jsonb NOT NULL,
    revoked_dots jsonb DEFAULT '[]'::jsonb NOT NULL,
    revoked_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.contacts (
    id uuid NOT NULL,
    requester_id text NOT NULL,
    target_id text NOT NULL,
    scope text NOT NULL,
    status text NOT NULL,
    request_event_ref text,
    response_event_ref text,
    tombstone_event_ref text,
    message text,
    peer_service_id text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.devices (
    id uuid NOT NULL,
    actor_id text NOT NULL,
    device_id text NOT NULL,
    device_key text,
    verification_state text DEFAULT 'unverified'::text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.device_messages (
    id uuid NOT NULL,
    idempotency_key text NOT NULL,
    sender text NOT NULL,
    recipient text NOT NULL,
    device_id text NOT NULL,
    position bigint NOT NULL,
    content jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.device_message_txns (
    key text NOT NULL,
    request_digest text NOT NULL,
    outcome jsonb NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.device_message_idempotency (
    message_key text NOT NULL,
    intent_digest text NOT NULL,
    delivered boolean NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.device_message_ack_tokens (
    ack_token text NOT NULL,
    recipient text NOT NULL,
    device_id text NOT NULL,
    queue_position bigint NOT NULL,
    issued_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone
);

CREATE TABLE public.device_message_lost_watermarks (
    recipient text NOT NULL,
    device_id text NOT NULL,
    lost_through bigint NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (recipient, device_id)
);

CREATE TABLE public.direct_conversation_bindings (
    participants_key text NOT NULL,
    participants_unordered text[] NOT NULL,
    realm_id uuid NOT NULL,
    main_strand_id uuid NOT NULL,
    binding_event_ref text NOT NULL,
    state text NOT NULL,
    authoring_context jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.events (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    event_type text NOT NULL,
    sender_id text,
    thread_id text,
    operation_id uuid,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.federation_operations (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    object_type text NOT NULL,
    object_id text,
    operation_type text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.federation_outbox (
    id text NOT NULL,
    peer_id text NOT NULL,
    peer_url text NOT NULL,
    endpoint text NOT NULL,
    idempotency_key text NOT NULL,
    payload_json text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    next_attempt_at bigint NOT NULL,
    last_status integer,
    last_response_excerpt text,
    created_at bigint NOT NULL,
    delivered_at bigint
);

CREATE TABLE public.federation_outbox_dead_letter (
    id text NOT NULL,
    outbox_id text NOT NULL,
    peer_id text NOT NULL,
    endpoint text NOT NULL,
    idempotency_key text NOT NULL,
    terminal_status integer NOT NULL,
    attempts integer NOT NULL,
    response_excerpt text,
    failed_at bigint NOT NULL,
    reason text NOT NULL
);

CREATE TABLE public.federation_frontier_exchange (
    realm_id uuid NOT NULL,
    peer_service_id text NOT NULL,
    status text NOT NULL,
    consecutive_failures integer DEFAULT 0 NOT NULL,
    last_success_at bigint,
    last_failure_at bigint,
    last_frontier_root text,
    last_error text,
    updated_at bigint NOT NULL
);

CREATE TABLE public.federation_transactions (
    id uuid NOT NULL,
    source_service text NOT NULL,
    txn_id text NOT NULL,
    destination_service text NOT NULL,
    realm_id uuid,
    status text NOT NULL,
    content_digest text NOT NULL,
    origin_verification_method text,
    service_binding_ref text,
    origin_key_state_digest text,
    local_peer_policy_digest text,
    payload jsonb NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    processed_at timestamp with time zone
);

CREATE TABLE public.invite_receive_policies (
    id text NOT NULL,
    policy_payload jsonb NOT NULL,
    blocked_subjects text[] DEFAULT '{}'::text[] NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.invite_locators (
    locator_id text PRIMARY KEY,
    token_digest text NOT NULL UNIQUE,
    subject_id text NOT NULL,
    recipient_service_id text NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    one_time_use boolean DEFAULT false NOT NULL,
    record_payload jsonb NOT NULL,
    revoked_at timestamp with time zone,
    consumed_at timestamp with time zone
);

-- Deployment-wide dynamic operational settings (rate limits, admin
-- allowlist, federation peers, feature toggles). One row PER setting key:
-- `value` is the JSON for that key only. This is an OVERLAY — env/boot config
-- provides the defaults and only explicitly-overridden keys have a row here,
-- so changing an env default still takes effect for keys never overridden.
-- Per-key rows also mean independent updates, per-key audit, and no
-- lost-update when two keys change concurrently. Tier-1 bootstrap/secret
-- config (bind, DATABASE_URL, service DID, signing seeds) deliberately stays
-- in env and is NOT stored here.
CREATE TABLE public.server_settings (
    key text NOT NULL,
    value jsonb NOT NULL,
    updated_by text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT server_settings_pkey PRIMARY KEY (key)
);

CREATE TABLE public.key_backups (
    id uuid NOT NULL,
    actor_id text,
    device_id text,
    backup_class text,
    backup_version text,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_accessed_at timestamp with time zone,
    account_id text,
    scheme text,
    version integer DEFAULT 0 NOT NULL,
    key_material_encrypted bytea,
    -- SOL-02-004: identity of the backup series this envelope belongs to,
    -- projected out of the JSONB payload as stored generated columns. They
    -- back the UNIQUE(series_actor_id, series_id, series_seq) constraint below
    -- which makes the §7.6 series-monotonicity check race-free: two concurrent
    -- successor PUTs that both compute the same series_seq can no longer both
    -- land — the second insert is rejected by the unique violation rather than
    -- relying on a read-then-write (TOCTOU) snapshot check.
    series_actor_id text GENERATED ALWAYS AS ((payload ->> 'actor_id')) STORED,
    series_id text GENERATED ALWAYS AS ((payload ->> 'series_id')) STORED,
    series_seq bigint GENERATED ALWAYS AS (((payload ->> 'series_seq'))::bigint) STORED
);

CREATE TABLE public.mls_commits (
    id uuid NOT NULL,
    effective_scope_kind text NOT NULL,
    realm_id text NOT NULL,
    circle_id text,
    effective_scope jsonb NOT NULL,
    mls_group_id text NOT NULL,
    epoch bigint NOT NULL,
    leader_actor_id text NOT NULL,
    creator_device_id text NOT NULL,
    genesis_event_ref text NOT NULL,
    covered_seals jsonb DEFAULT '[]'::jsonb NOT NULL,
    governance_binding jsonb DEFAULT '{}'::jsonb NOT NULL,
    accepted_commit_ref text,
    committed_at bigint NOT NULL,
    frontier_contested boolean DEFAULT false NOT NULL,
    CONSTRAINT mls_commits_effective_scope_check CHECK ((((effective_scope_kind = 'realm'::text) AND (circle_id IS NULL)) OR ((effective_scope_kind = 'circle'::text) AND (circle_id IS NOT NULL))))
);

CREATE TABLE public.mls_key_packages (
    id text NOT NULL,
    keypackage_ref text NOT NULL,
    keypackage_digest text NOT NULL,
    actor_id text NOT NULL,
    device_id text NOT NULL,
    key_package_bytes bytea NOT NULL,
    capabilities jsonb DEFAULT '[]'::jsonb NOT NULL,
    capabilities_digest text NOT NULL,
    device_signature jsonb DEFAULT '{}'::jsonb NOT NULL,
    last_resort boolean DEFAULT false NOT NULL,
    last_resort_realm_id text,
    lifetime_not_before bigint NOT NULL,
    lifetime_not_after bigint NOT NULL,
    claimed_by_mls_group_id text,
    ssk_generation bigint,
    device_authorize_event_id text,
    claimed_at bigint,
    claim_expires_at_unix_ms bigint,
    consumed_at bigint,
    created_at bigint NOT NULL
);

CREATE TABLE public.peer_keypackage_claims (
    source_service_id text NOT NULL,
    claim_request_id text NOT NULL,
    request_digest text NOT NULL,
    state text NOT NULL,
    outcome jsonb,
    keypackage_id text,
    claim_expires_at_unix_ms bigint,
    expires_at bigint NOT NULL,
    updated_at bigint NOT NULL,
    CONSTRAINT peer_keypackage_claims_state_check CHECK (state IN ('claimed', 'claim_failed', 'expired', 'revoked')),
    PRIMARY KEY (source_service_id, claim_request_id)
);

CREATE TABLE public.mls_welcomes (
    id text NOT NULL,
    mls_group_id text NOT NULL,
    recipient_actor_id text NOT NULL,
    recipient_device_id text NOT NULL,
    welcome_bytes bytea NOT NULL,
    key_package_id text NOT NULL,
    epoch bigint NOT NULL,
    commit_ref text,
    governance_binding jsonb NOT NULL,
    enqueued_at bigint NOT NULL,
    delivered_at bigint
);

CREATE TABLE public.moderation_actions (
    id uuid NOT NULL,
    moderator_id text,
    target_actor_id text,
    action_kind text,
    realm_id uuid,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.moderation_reports (
    id uuid NOT NULL,
    reporter_id text,
    target_actor_id text,
    target_event_id uuid,
    realm_id uuid,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.organizations (
    organization_id text NOT NULL,
    organization_did text NOT NULL,
    handle text,
    display_name text NOT NULL,
    source_refs jsonb DEFAULT '[]'::jsonb NOT NULL,
    policy_revision text DEFAULT 'local'::text NOT NULL,
    verified boolean DEFAULT true NOT NULL,
    members jsonb DEFAULT '[]'::jsonb NOT NULL,
    member_count bigint DEFAULT 0 NOT NULL,
    created_by text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.organization_policies (
    organization_id text NOT NULL,
    policy_id text NOT NULL,
    payload jsonb NOT NULL,
    version bigint NOT NULL,
    updated_by text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT organization_policies_version_check CHECK ((version >= 0))
);

-- SOL-ORG-04 — verified `ak.realm.organization` relationship statements.
-- Primary key `(realm_id, organization_id, relationship)` so owner /
-- governance / sponsor / directory_certifier relationships for the same Realm
-- coexist as independent rows. Column order mirrors the spec
-- `realm_organization_payload`. Only the proof / delegation audit digests are
-- stored, never raw signature bytes.
CREATE TABLE public.realm_organizations (
    realm_id text NOT NULL,
    organization_id text NOT NULL,
    relationship text NOT NULL,
    statement_id text NOT NULL,
    status text NOT NULL,
    control_scopes jsonb DEFAULT '[]'::jsonb NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    not_before timestamp with time zone,
    expires_at timestamp with time zone,
    supersedes_statement_id text,
    revokes_statement_id text,
    realm_frontier_digest text,
    proof_digest text,
    delegation_ref text,
    issuer_role text NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

-- SOL-ORG-05 — `owning_organizations` declared hints. These NO LONGER drive
-- governance / durability / delivery / directory policy inheritance (only a
-- verified `ak.realm.organization` statement does); the table is retained as a
-- discovery / display hint surface.
CREATE TABLE public.realm_owning_organizations (
    realm_id text NOT NULL,
    organization_id text NOT NULL,
    linked_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.realm_moderation_policies (
    realm_id text NOT NULL,
    payload jsonb NOT NULL,
    updated_by text NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.retention_policies (
    realm_id text NOT NULL,
    ttl_seconds bigint NOT NULL,
    updated_by text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT retention_policies_ttl_seconds_check CHECK ((ttl_seconds >= 0))
);

CREATE TABLE public.retention_tombstones (
    event_id text NOT NULL,
    realm_id text NOT NULL,
    reason text NOT NULL,
    policy_ttl_seconds bigint NOT NULL,
    expired_at timestamp with time zone NOT NULL,
    tombstoned_at timestamp with time zone NOT NULL,
    sealed boolean DEFAULT false NOT NULL,
    CONSTRAINT retention_tombstones_policy_ttl_seconds_check CHECK ((policy_ttl_seconds >= 0))
);

CREATE TABLE public.multisig_pending (
    id text NOT NULL,
    realm_id uuid NOT NULL,
    threshold_k integer NOT NULL,
    threshold_n integer NOT NULL,
    members text[] NOT NULL,
    canonical_b64 text DEFAULT ''::text NOT NULL,
    partials jsonb DEFAULT '{}'::jsonb NOT NULL,
    claimed_by_node_id text,
    claimed_until timestamp with time zone,
    claim_seq bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone DEFAULT (now() + '01:00:00'::interval) NOT NULL
);

CREATE SEQUENCE public.notification_projection_position_seq AS bigint;

CREATE TABLE public.notifications (
    id uuid NOT NULL,
    recipient_id text NOT NULL,
    realm_id uuid,
    source_event_id text,
    controller_account_id uuid,
    recipient_service_id text,
    source_account_artifact_kind text,
    source_account_artifact_id text,
    source_ref text,
    strand_id text,
    track_name text,
    notification_type text NOT NULL,
    event_kind text,
    source_actor_id text,
    priority text DEFAULT 'normal'::text NOT NULL,
    state text DEFAULT 'unread'::text NOT NULL,
    preview jsonb,
    projection_action text,
    projection_data jsonb,
    projection_position bigint DEFAULT nextval('public.notification_projection_position_seq'::regclass) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    read_at timestamp with time zone,
    CONSTRAINT notifications_source_boundary_check CHECK (((source_event_id IS NOT NULL) AND (realm_id IS NOT NULL) AND (controller_account_id IS NULL) AND (recipient_service_id IS NULL) AND (source_account_artifact_kind IS NULL) AND (source_account_artifact_id IS NULL)) OR ((source_event_id IS NULL) AND (realm_id IS NULL) AND (controller_account_id IS NOT NULL) AND (recipient_service_id IS NOT NULL) AND (source_account_artifact_kind = 'agent_runtime_approval'::text) AND (source_account_artifact_id IS NOT NULL))),
    CONSTRAINT notifications_projection_action_check CHECK ((projection_action IS NULL) OR (projection_action = ANY (ARRAY['add'::text, 'update'::text, 'remove'::text])))
);

CREATE FUNCTION public.project_agent_runtime_approval_notification() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    delta_action text;
    terminal_reason text;
    notification_id uuid;
    account_id uuid;
    service_id text;
    recipient_id text;
    artifact_id text;
    notification_data jsonb;
BEGIN
    IF NEW.approval_request_id IS NOT NULL
       AND NEW.approval_notification_id IS NOT NULL
       AND NEW.controller_account_id IS NOT NULL
       AND NEW.recipient_service_id IS NOT NULL THEN
        delta_action := CASE
            WHEN TG_OP = 'INSERT' OR OLD.approval_request_id IS NULL THEN 'add'
            ELSE 'update'
        END;
        notification_id := NEW.approval_notification_id;
        account_id := NEW.controller_account_id;
        service_id := NEW.recipient_service_id;
        recipient_id := NEW.controller_id;
        artifact_id := NEW.approval_request_id;
        notification_data := jsonb_build_object(
            'kind', 'agent_runtime_approval',
            'approval_request_id', NEW.approval_request_id,
            'agent_id', NEW.id,
            'requested_at', to_char(NEW.approval_requested_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
            'expires_at', to_char(NEW.pairing_expires_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
        );
    ELSIF TG_OP = 'UPDATE'
          AND OLD.approval_request_id IS NOT NULL
          AND NEW.approval_request_id IS NULL THEN
        terminal_reason := CASE
            WHEN NEW.state = 'deactivated' THEN 'deactivated'
            WHEN NEW.state = 'pairing_expired' THEN 'expired'
            WHEN NEW.authorized_event_ref IS DISTINCT FROM OLD.authorized_event_ref
                 AND NEW.authorized_event_ref IS NOT NULL THEN 'approved'
            WHEN NEW.pairing_request_id IS DISTINCT FROM OLD.pairing_request_id THEN 'renewed'
            ELSE 'superseded'
        END;
        delta_action := 'remove';
        notification_id := OLD.approval_notification_id;
        account_id := OLD.controller_account_id;
        service_id := OLD.recipient_service_id;
        recipient_id := OLD.controller_id;
        artifact_id := OLD.approval_request_id;
        notification_data := jsonb_build_object(
            'kind', 'agent_runtime_approval',
            'reason', terminal_reason
        );
    ELSE
        RETURN NEW;
    END IF;

    INSERT INTO public.notifications (
        id, recipient_id, controller_account_id, recipient_service_id,
        source_account_artifact_kind, source_account_artifact_id,
        notification_type, priority, state, projection_action,
        projection_data, created_at, updated_at
    ) VALUES (
        notification_id, recipient_id, account_id, service_id,
        'agent_runtime_approval', artifact_id,
        'agent', 'normal', 'unread', delta_action,
        notification_data, now(), now()
    )
    ON CONFLICT (controller_account_id, recipient_service_id,
                 source_account_artifact_kind, source_account_artifact_id)
        WHERE controller_account_id IS NOT NULL
    DO UPDATE SET
        projection_action = EXCLUDED.projection_action,
        projection_data = EXCLUDED.projection_data,
        projection_position = CASE
            WHEN notifications.projection_action IS DISTINCT FROM EXCLUDED.projection_action
              OR notifications.projection_data IS DISTINCT FROM EXCLUDED.projection_data
            THEN nextval('public.notification_projection_position_seq')
            ELSE notifications.projection_position
        END,
        updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER agent_runtime_approval_notification_projection
AFTER INSERT OR UPDATE ON public.agent_principals
FOR EACH ROW EXECUTE FUNCTION public.project_agent_runtime_approval_notification();

CREATE TABLE public.pending_agent_drafts (
    id uuid NOT NULL,
    agent_id text NOT NULL,
    controller_id text NOT NULL,
    draft_payload jsonb NOT NULL,
    state text DEFAULT 'pending'::text NOT NULL,
    proposed_at timestamp with time zone NOT NULL,
    decided_at timestamp with time zone,
    decided_by_id text,
    CONSTRAINT pending_agent_drafts_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'expired'::text])))
);

CREATE TABLE public.policy_documents (
    id uuid NOT NULL,
    owner_id text NOT NULL,
    scope text NOT NULL,
    subject_ref text NOT NULL,
    policy_type text NOT NULL,
    document jsonb NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    signed_by_id text,
    active boolean DEFAULT true NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.presence (
    id text NOT NULL,
    device_id text NOT NULL,
    status text NOT NULL,
    status_message text,
    last_active_at text,
    envelope jsonb NOT NULL,
    expires_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.projection_circle_members (
    id uuid NOT NULL,
    circle_id uuid NOT NULL,
    actor_id text NOT NULL,
    state text DEFAULT 'active'::text NOT NULL,
    joined_at timestamp with time zone NOT NULL,
    removed_at timestamp with time zone,
    CONSTRAINT projection_circle_members_state_check CHECK ((state = ANY (ARRAY['invited'::text, 'active'::text, 'removed'::text, 'banned'::text, 'left'::text])))
);

CREATE TABLE public.projection_circles (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    profile_ref text,
    title text NOT NULL,
    summary text,
    display jsonb NOT NULL,
    directory_visibility text DEFAULT 'members'::text NOT NULL,
    join_rule text DEFAULT 'invite'::text NOT NULL,
    history_visibility text DEFAULT 'joined'::text NOT NULL,
    content_encryption_floor text,
    metadata_encryption_floor text,
    encryption_profile text DEFAULT 'mls_rfc9420'::text NOT NULL,
    mls_group_ref text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by_id text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_by_id text,
    updated_at timestamp with time zone,
    CONSTRAINT projection_circles_content_encryption_floor_check CHECK ((content_encryption_floor = ANY (ARRAY['allow_plaintext'::text, 'e2ee_required'::text]))),
    CONSTRAINT projection_circles_directory_visibility_check CHECK ((directory_visibility = ANY (ARRAY['members'::text, 'realm_members'::text]))),
    CONSTRAINT projection_circles_join_rule_check CHECK ((join_rule = ANY (ARRAY['invite'::text, 'request'::text, 'open'::text]))),
    CONSTRAINT projection_circles_metadata_encryption_floor_check CHECK ((metadata_encryption_floor = ANY (ARRAY['allow_plaintext'::text, 'e2ee_required'::text]))),
    CONSTRAINT projection_circles_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'tombstoned'::text])))
);

CREATE TABLE public.projection_events (
    id bigint NOT NULL,
    event_id uuid NOT NULL,
    realm_id uuid NOT NULL,
    event_kind text NOT NULL,
    operation_type text NOT NULL,
    operation_id uuid,
    sender_id text,
    payload jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    received_at timestamp with time zone NOT NULL DEFAULT now(),
    effective_scope text,
    CONSTRAINT projection_events_event_id_key UNIQUE (event_id)
);

CREATE SEQUENCE public.projection_events_ordinal_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.projection_events_ordinal_seq OWNED BY public.projection_events.id;

CREATE TABLE public.projection_strand_watches (
    id uuid NOT NULL,
    strand_id uuid NOT NULL,
    actor_id text NOT NULL,
    level text,
    level_public boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT projection_strand_watches_level_check CHECK (((level IS NULL) OR (level = ANY (ARRAY['mentions_only'::text, 'participating'::text, 'all'::text, 'muted'::text]))))
);

CREATE TABLE public.projection_strands (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    scope_circle_id uuid,
    tracks jsonb DEFAULT '{"synthesis": {}}'::jsonb NOT NULL,
    title text NOT NULL,
    summary text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by_id text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    history_basis_seals jsonb DEFAULT '[]'::jsonb NOT NULL,
    updated_by_id text,
    updated_at timestamp with time zone,
    CONSTRAINT projection_strands_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'redacted'::text])))
);

CREATE TABLE public.projection_morphs (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    morph_type text NOT NULL,
    title text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by_id text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    history_basis_seals jsonb DEFAULT '[]'::jsonb NOT NULL,
    updated_by_id text,
    updated_at timestamp with time zone,
    fields jsonb DEFAULT '{}'::jsonb NOT NULL,
    schema_refs jsonb DEFAULT '[]'::jsonb NOT NULL,
    facets jsonb DEFAULT '[]'::jsonb NOT NULL,
    versions jsonb DEFAULT '[]'::jsonb NOT NULL,
    scope_circle_id uuid,
    CONSTRAINT projection_morphs_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'redacted'::text])))
);

CREATE TABLE public.projection_spaces (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    scope_circle_id uuid,
    child_scope_policy text,
    child_scope_policy_scope_circle_id uuid,
    kind text NOT NULL,
    title text NOT NULL,
    fields jsonb DEFAULT '{}'::jsonb NOT NULL,
    parent_ref uuid,
    rank text,
    state text DEFAULT 'active'::text NOT NULL,
    state_changed_at timestamp with time zone,
    created_by_id text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    history_basis_seals jsonb DEFAULT '[]'::jsonb NOT NULL,
    updated_by_id text,
    updated_at timestamp with time zone,
    CONSTRAINT projection_spaces_child_scope_policy_check CHECK ((child_scope_policy = ANY (ARRAY['allow_any'::text, 'require_e2ee'::text, 'require_same_scope'::text, 'require_scope_circle_id'::text]))),
    CONSTRAINT projection_spaces_child_scope_policy_scope_check CHECK (((child_scope_policy <> 'require_scope_circle_id'::text) OR (child_scope_policy_scope_circle_id IS NOT NULL))),
    CONSTRAINT projection_spaces_state_check CHECK ((state = ANY (ARRAY['active'::text, 'archived'::text, 'tombstoned'::text])))
);

CREATE TABLE public.push_bridge_cache (
    id text NOT NULL,
    push_gateway_url text NOT NULL,
    service_base_url text NOT NULL,
    bridge_describe_url text NOT NULL,
    fetch_state text NOT NULL,
    cache_state text NOT NULL,
    contract_digest text NOT NULL,
    fetched_at timestamp with time zone NOT NULL,
    remote_contract jsonb NOT NULL,
    trust_level text DEFAULT 'pending'::text NOT NULL,
    freshness_at timestamp with time zone DEFAULT now() NOT NULL,
    etag text DEFAULT ''::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.push_devices (
    id text NOT NULL,
    actor_id text,
    device_id text NOT NULL,
    push_gateway text NOT NULL,
    push_key text NOT NULL,
    platform text,
    app_id text,
    payload jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.realm_invites (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    inviter_id text NOT NULL,
    invitee_id text,
    invite_delivery_target jsonb,
    introduction_evidence_digest text,
    third_party_id jsonb,
    join_rule_snapshot jsonb,
    invite_token text NOT NULL,
    status text NOT NULL,
    claim_nonces jsonb DEFAULT '{}'::jsonb NOT NULL,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone
);

CREATE TABLE public.recovery_policies (
    id uuid NOT NULL,
    principal_id text NOT NULL,
    version integer NOT NULL,
    trust_domain text NOT NULL,
    allowed_proof_kinds text[] NOT NULL,
    supersedes uuid,
    expires_at timestamp with time zone,
    issued_at timestamp with time zone NOT NULL,
    verification_method text NOT NULL,
    raw_payload jsonb NOT NULL,
    accepted_at timestamp with time zone NOT NULL,
    CONSTRAINT recovery_policies_version_check CHECK ((version >= 1))
);

CREATE TABLE public.recovery_receipts (
    id uuid NOT NULL,
    principal_id text NOT NULL,
    recovery_session_id uuid NOT NULL,
    policy_id uuid NOT NULL,
    policy_version integer NOT NULL,
    trust_domain text NOT NULL,
    new_device_id text NOT NULL,
    proof_digest text NOT NULL,
    outcome text NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone NOT NULL,
    verification_method text NOT NULL,
    raw_payload jsonb NOT NULL,
    accepted_at timestamp with time zone NOT NULL,
    CONSTRAINT recovery_receipts_policy_version_check CHECK ((policy_version >= 1))
);

CREATE TABLE public.recovery_sessions (
    id uuid NOT NULL,
    principal_id text NOT NULL,
    requesting_device_id text NOT NULL,
    trust_domain text NOT NULL,
    policy_id uuid NOT NULL,
    policy_version integer NOT NULL,
    identity_model text NOT NULL,
    ssk_generation bigint,
    current_device_generation_ref text,
    device_generation_status text,
    registry_head text,
    accepted_seal_frontier jsonb,
    policy_payload jsonb NOT NULL,
    challenge text NOT NULL,
    state text DEFAULT 'pending'::text NOT NULL,
    proof_payload jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT recovery_sessions_policy_version_check CHECK ((policy_version >= 1)),
    CONSTRAINT recovery_sessions_identity_model_check CHECK ((identity_model = ANY (ARRAY['cross_signing'::text, 'enrollment_authority'::text]))),
    CONSTRAINT recovery_sessions_generation_shape_check CHECK ((((identity_model = 'cross_signing'::text) AND (ssk_generation >= 1) AND (current_device_generation_ref IS NULL) AND (device_generation_status IS NULL) AND (registry_head IS NULL) AND (accepted_seal_frontier IS NULL)) OR ((identity_model = 'enrollment_authority'::text) AND (ssk_generation IS NULL) AND (current_device_generation_ref IS NOT NULL) AND (device_generation_status = ANY (ARRAY['active'::text, 'conflicted'::text])) AND (registry_head IS NOT NULL)))),
    CONSTRAINT recovery_sessions_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'verified'::text, 'completed'::text, 'rejected'::text, 'expired'::text])))
);

CREATE TABLE public.sessions (
    id text NOT NULL,
    actor_id text NOT NULL,
    device_id text NOT NULL,
    audience text NOT NULL,
    session_public_key text,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.space_members (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    actor_id text NOT NULL,
    membership text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    joined_at timestamp with time zone,
    left_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.space_state_events (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    event_type text NOT NULL,
    subject text DEFAULT ''::text NOT NULL,
    sender_id text,
    operation_id uuid,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.spaces (
    id uuid NOT NULL,
    title text NOT NULL,
    summary text,
    owner_id text,
    discoverability text DEFAULT 'invite_only'::text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    history_visibility text DEFAULT 'joined'::text NOT NULL,
    history_sharing_policy jsonb,
    history_sharing_policy_digest text,
    preview_policy jsonb,
    preview_policy_digest text,
    encryption_profile text DEFAULT 'mls_rfc9420'::text NOT NULL,
    plaintext_visible_services jsonb DEFAULT '[]'::jsonb NOT NULL,
    CONSTRAINT spaces_encryption_profile_check CHECK ((encryption_profile = ANY (ARRAY['none'::text, 'plaintext'::text, 'mls_rfc9420'::text]))),
    CONSTRAINT spaces_history_visibility_check CHECK ((history_visibility = ANY (ARRAY['world_readable'::text, 'shared'::text, 'invited'::text, 'joined'::text, 'restricted'::text])))
);

CREATE TABLE public.sync_cursor_handles (
    id text NOT NULL,
    principal_id text,
    device_id text,
    service_id text NOT NULL,
    filter_digest text,
    purpose text NOT NULL,
    positions jsonb,
    target jsonb,
    issued_at_ms bigint NOT NULL,
    expires_at_ms bigint NOT NULL,
    CONSTRAINT sync_cursor_handles_purpose_check CHECK ((purpose = ANY (ARRAY['stream'::text, 'barrier'::text])))
);

CREATE TABLE public.sync_cursor_revocations (
    id uuid NOT NULL,
    cursor_digest text NOT NULL,
    principal_id text NOT NULL,
    device_id text,
    scope text NOT NULL,
    reason_code text NOT NULL,
    revoked_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT sync_cursor_revocations_scope_check CHECK ((scope = ANY (ARRAY['this_cursor'::text, 'same_device'::text, 'same_session'::text])))
);

CREATE TABLE public.idempotency_keys (
    principal_id text NOT NULL,
    idempotency_key text NOT NULL,
    service_id text NOT NULL,
    request_hash text NOT NULL,
    response_status integer NOT NULL,
    response_body jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

CREATE TABLE public.webrtc_sessions (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    initiator_id text NOT NULL,
    ice_config jsonb DEFAULT '{}'::jsonb NOT NULL,
    signaling_state jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

CREATE TABLE public.webvh_documents (
    id text NOT NULL,
    did_document jsonb NOT NULL,
    key_log_head text,
    seq bigint DEFAULT 0 NOT NULL,
    method_evidence jsonb DEFAULT '{}'::jsonb NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone DEFAULT (now() + '00:15:00'::interval) NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.webvh_log_events (
    id text NOT NULL,
    did text NOT NULL,
    seq bigint NOT NULL,
    operation jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- The deployment's own authoritative service identity (identity-did.md §3.7).
-- Singleton: at most one row keyed by the fixed id 'self'. `identity` is the
-- SDK StoredServiceIdentity document: public DID/receipt evidence plus opaque
-- KeyRefs. Private signing and WebVH control seeds MUST remain in the selected
-- Secrets/KeyStore backend and MUST NOT be copied into PostgreSQL.
CREATE TABLE public.service_identity (
    id text NOT NULL,
    identity jsonb NOT NULL
);

CREATE TABLE public.service_identity_registrations (
    service_type text NOT NULL,
    public_base text NOT NULL,
    service_id text NOT NULL,
    version_id text NOT NULL,
    inception_digest text NOT NULL,
    outcome jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT service_identity_registrations_pkey PRIMARY KEY (service_type, public_base),
    CONSTRAINT service_identity_registrations_service_id_key UNIQUE (service_id)
);

ALTER TABLE ONLY public.projection_events ALTER COLUMN id SET DEFAULT nextval('public.projection_events_ordinal_seq'::regclass);

ALTER TABLE ONLY public.account_datas
    ADD CONSTRAINT account_datas_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.account_datas
    ADD CONSTRAINT account_datas_actor_data_type_key UNIQUE (actor_id, data_type);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_principal_id_key UNIQUE (principal_id);

ALTER TABLE ONLY public.account_localparts
    ADD CONSTRAINT account_localparts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.account_localparts
    ADD CONSTRAINT account_localparts_localpart_key UNIQUE (localpart);

ALTER TABLE ONLY public.account_lifecycle
    ADD CONSTRAINT account_lifecycle_pkey PRIMARY KEY (principal_id);

ALTER TABLE ONLY public.handle_releases
    ADD CONSTRAINT handle_releases_pkey PRIMARY KEY (localpart);

ALTER TABLE ONLY public.agent_keys
    ADD CONSTRAINT agent_keys_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.agent_participation_ceiling
    ADD CONSTRAINT agent_participation_ceiling_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.agent_participation
    ADD CONSTRAINT agent_participation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.agent_participation
    ADD CONSTRAINT agent_participation_agent_id_scope_key_key UNIQUE (agent_id, scope_key);

ALTER TABLE ONLY public.agent_principals
    ADD CONSTRAINT agent_principals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.agent_sessions
    ADD CONSTRAINT agent_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.applet_registrations
    ADD CONSTRAINT applet_registrations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.applet_transactions
    ADD CONSTRAINT applet_transactions_pkey PRIMARY KEY (source_service_id, idempotency_key);

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.backup_series
    ADD CONSTRAINT backup_series_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.blobs
    ADD CONSTRAINT blobs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.call_signal_relay
    ADD CONSTRAINT call_signal_relay_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.call_signal_relay
    ADD CONSTRAINT call_signal_relay_realm_position_key UNIQUE (realm_id, position);

ALTER TABLE ONLY public.call_signal_relay_position
    ADD CONSTRAINT call_signal_relay_position_pkey PRIMARY KEY (realm_id);

ALTER TABLE ONLY public.call_signal_relay_watermark
    ADD CONSTRAINT call_signal_relay_watermark_pkey PRIMARY KEY (actor_id, device_id, realm_id);

ALTER TABLE ONLY public.read_receipt_relay
    ADD CONSTRAINT read_receipt_relay_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.read_receipt_relay
    ADD CONSTRAINT read_receipt_relay_realm_position_key UNIQUE (realm_id, position);

ALTER TABLE ONLY public.read_receipt_relay_position
    ADD CONSTRAINT read_receipt_relay_position_pkey PRIMARY KEY (realm_id);

ALTER TABLE ONLY public.read_receipt_relay_watermark
    ADD CONSTRAINT read_receipt_relay_watermark_pkey PRIMARY KEY (actor_id, device_id, realm_id);

ALTER TABLE ONLY public.canonical_events
    ADD CONSTRAINT canonical_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.state_moves
    ADD CONSTRAINT state_moves_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.state_seals
    ADD CONSTRAINT state_seals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.state_cell_ops
    ADD CONSTRAINT state_cell_ops_pkey PRIMARY KEY (seq);

ALTER TABLE ONLY public.state_cell_ops
    ADD CONSTRAINT state_cell_ops_seal_op_index_key UNIQUE (seal_id, op_index);

ALTER TABLE ONLY public.state_cell_cache
    ADD CONSTRAINT state_cell_cache_pkey PRIMARY KEY (realm_id, cell_id, view_hash);

ALTER TABLE ONLY public.consent_cells
    ADD CONSTRAINT consent_cells_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.consent_cells
    ADD CONSTRAINT consent_cells_holder_peer_scope_key UNIQUE (holder_id, peer_id, scope);

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_requester_target_scope_key UNIQUE (requester_id, target_id, scope);

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_actor_device_id_key UNIQUE (actor_id, device_id);

ALTER TABLE ONLY public.device_messages
    ADD CONSTRAINT device_messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.device_messages
    ADD CONSTRAINT device_messages_recipient_device_position_key UNIQUE (recipient, device_id, position);

ALTER TABLE ONLY public.device_message_txns
    ADD CONSTRAINT device_message_txns_pkey PRIMARY KEY (key);

ALTER TABLE ONLY public.device_message_idempotency
    ADD CONSTRAINT device_message_idempotency_pkey PRIMARY KEY (message_key);

ALTER TABLE ONLY public.device_message_ack_tokens
    ADD CONSTRAINT device_message_ack_tokens_pkey PRIMARY KEY (ack_token);

ALTER TABLE ONLY public.direct_conversation_bindings
    ADD CONSTRAINT direct_conversation_bindings_pkey PRIMARY KEY (participants_key);

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.federation_operations
    ADD CONSTRAINT federation_operations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.federation_outbox_dead_letter
    ADD CONSTRAINT federation_outbox_dead_letter_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.federation_outbox
    ADD CONSTRAINT federation_outbox_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.federation_frontier_exchange
    ADD CONSTRAINT federation_frontier_exchange_pkey PRIMARY KEY (realm_id, peer_service_id);

ALTER TABLE ONLY public.federation_transactions
    ADD CONSTRAINT federation_transactions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.federation_transactions
    ADD CONSTRAINT federation_transactions_source_service_txn_id_key UNIQUE (source_service, txn_id);

ALTER TABLE ONLY public.invite_receive_policies
    ADD CONSTRAINT invite_receive_policies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.key_backups
    ADD CONSTRAINT key_backups_pkey PRIMARY KEY (id);

-- SOL-02-004: enforce series_seq monotonicity at the storage layer. A given
-- (actor, series) may hold at most one envelope per sequence number; the
-- receive path depends on this constraint so concurrent successor PUTs cannot
-- double-write the same seq (TOCTOU). NULLs (non-series backups) are exempt
-- because Postgres treats NULL as distinct in a UNIQUE index.
ALTER TABLE ONLY public.key_backups
    ADD CONSTRAINT key_backups_series_seq_key UNIQUE (series_actor_id, series_id, series_seq);

ALTER TABLE ONLY public.mls_commits
    ADD CONSTRAINT mls_commits_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mls_key_packages
    ADD CONSTRAINT mls_key_packages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mls_welcomes
    ADD CONSTRAINT mls_welcomes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.moderation_actions
    ADD CONSTRAINT moderation_actions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.moderation_reports
    ADD CONSTRAINT moderation_reports_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (organization_id);

ALTER TABLE ONLY public.organization_policies
    ADD CONSTRAINT organization_policies_pkey PRIMARY KEY (organization_id);

ALTER TABLE ONLY public.realm_organizations
    ADD CONSTRAINT realm_organizations_pkey PRIMARY KEY (realm_id, organization_id, relationship);

ALTER TABLE ONLY public.realm_owning_organizations
    ADD CONSTRAINT realm_owning_organizations_pkey PRIMARY KEY (realm_id, organization_id);

ALTER TABLE ONLY public.realm_moderation_policies
    ADD CONSTRAINT realm_moderation_policies_pkey PRIMARY KEY (realm_id);

ALTER TABLE ONLY public.retention_policies
    ADD CONSTRAINT retention_policies_pkey PRIMARY KEY (realm_id);

ALTER TABLE ONLY public.retention_tombstones
    ADD CONSTRAINT retention_tombstones_pkey PRIMARY KEY (event_id);

ALTER TABLE ONLY public.multisig_pending
    ADD CONSTRAINT multisig_pending_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pending_agent_drafts
    ADD CONSTRAINT pending_agent_drafts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.policy_documents
    ADD CONSTRAINT policy_documents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.presence
    ADD CONSTRAINT presence_pkey PRIMARY KEY (id, device_id);

ALTER TABLE ONLY public.projection_circle_members
    ADD CONSTRAINT projection_circle_members_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projection_circle_members
    ADD CONSTRAINT projection_circle_members_circle_id_actor_id_key UNIQUE (circle_id, actor_id);

ALTER TABLE ONLY public.projection_circles
    ADD CONSTRAINT projection_circles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projection_events
    ADD CONSTRAINT projection_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projection_strand_watches
    ADD CONSTRAINT projection_strand_watches_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projection_strand_watches
    ADD CONSTRAINT projection_strand_watches_strand_id_actor_id_key UNIQUE (strand_id, actor_id);

ALTER TABLE ONLY public.projection_strands
    ADD CONSTRAINT projection_strands_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projection_morphs
    ADD CONSTRAINT projection_morphs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projection_spaces
    ADD CONSTRAINT projection_spaces_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.push_bridge_cache
    ADD CONSTRAINT push_bridge_cache_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.push_devices
    ADD CONSTRAINT push_devices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.realm_invites
    ADD CONSTRAINT realm_invites_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.recovery_policies
    ADD CONSTRAINT recovery_policies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.recovery_policies
    ADD CONSTRAINT recovery_policies_principal_id_version_key UNIQUE (principal_id, version);

ALTER TABLE ONLY public.recovery_receipts
    ADD CONSTRAINT recovery_receipts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.recovery_receipts
    ADD CONSTRAINT recovery_receipts_recovery_session_id_key UNIQUE (recovery_session_id);

ALTER TABLE ONLY public.recovery_sessions
    ADD CONSTRAINT recovery_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.space_members
    ADD CONSTRAINT space_members_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.space_members
    ADD CONSTRAINT space_members_realm_id_actor_key UNIQUE (realm_id, actor_id);

ALTER TABLE ONLY public.space_state_events
    ADD CONSTRAINT space_state_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.spaces
    ADD CONSTRAINT spaces_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sync_cursor_handles
    ADD CONSTRAINT sync_cursor_handles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sync_cursor_revocations
    ADD CONSTRAINT sync_cursor_revocations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.idempotency_keys
    ADD CONSTRAINT idempotency_keys_pkey PRIMARY KEY (principal_id, idempotency_key);

ALTER TABLE ONLY public.webrtc_sessions
    ADD CONSTRAINT webrtc_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.webvh_documents
    ADD CONSTRAINT webvh_documents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.webvh_log_events
    ADD CONSTRAINT webvh_log_events_did_seq_key UNIQUE (did, seq);

ALTER TABLE ONLY public.webvh_log_events
    ADD CONSTRAINT webvh_log_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.service_identity
    ADD CONSTRAINT service_identity_pkey PRIMARY KEY (id);

CREATE INDEX account_localparts_account_idx ON public.account_localparts USING btree (account_id);

CREATE UNIQUE INDEX account_localparts_primary_account_idx ON public.account_localparts USING btree (account_id) WHERE (is_primary);

CREATE INDEX account_lifecycle_state_idx ON public.account_lifecycle USING btree (state, changed_at);

CREATE INDEX agent_keys_principal_idx ON public.agent_keys USING btree (agent_id);

CREATE INDEX agent_keys_state_idx ON public.agent_keys USING btree (state);

CREATE INDEX agent_participation_ceiling_realm_idx ON public.agent_participation_ceiling USING btree (realm_id);

CREATE INDEX agent_participation_realm_idx ON public.agent_participation USING btree (realm_id);

CREATE INDEX agent_principals_controller_idx ON public.agent_principals USING btree (controller_id);
CREATE UNIQUE INDEX agent_principals_pcr_idx ON public.agent_principals USING btree (principal_control_realm_id);
CREATE INDEX agent_principals_controller_agent_slug_idx ON public.agent_principals USING btree (controller_id, agent_slug) WHERE (agent_slug IS NOT NULL);

CREATE UNIQUE INDEX agent_principals_pairing_request_idx ON public.agent_principals USING btree (pairing_request_id) WHERE (pairing_request_id IS NOT NULL);
CREATE UNIQUE INDEX agent_principals_approval_request_idx ON public.agent_principals USING btree (approval_request_id) WHERE (approval_request_id IS NOT NULL);

CREATE INDEX agent_principals_state_idx ON public.agent_principals USING btree (state);

CREATE INDEX agent_sessions_principal_idx ON public.agent_sessions USING btree (agent_id);

CREATE INDEX agent_sessions_state_idx ON public.agent_sessions USING btree (state);

CREATE UNIQUE INDEX applet_registrations_active_namespace_idx ON public.applet_registrations USING btree (namespace) WHERE (revoked_at IS NULL);

CREATE INDEX applet_registrations_owner_idx ON public.applet_registrations USING btree (owner_actor_id);

CREATE INDEX applet_registrations_status_idx ON public.applet_registrations USING btree (status);

CREATE INDEX applet_transactions_received_idx ON public.applet_transactions USING btree (received_at);

CREATE INDEX audit_logs_action_idx ON public.audit_logs USING btree (action);

CREATE INDEX audit_logs_actor_idx ON public.audit_logs USING btree (actor_id, created_at);

CREATE INDEX audit_logs_space_idx ON public.audit_logs USING btree (realm_id);

CREATE UNIQUE INDEX backup_series_actor_class_uniq ON public.backup_series USING btree (actor_id, backup_class) WHERE (retired_at IS NULL);

CREATE INDEX backup_series_actor_idx ON public.backup_series USING btree (actor_id);

CREATE INDEX backup_series_class_idx ON public.backup_series USING btree (backup_class);

CREATE INDEX blobs_sha256_idx ON public.blobs USING btree (sha256);

CREATE INDEX blobs_space_created_idx ON public.blobs USING btree (realm_id, created_at);

CREATE INDEX call_signal_relay_realm_position_idx ON public.call_signal_relay USING btree (realm_id, position);

CREATE INDEX call_signal_relay_expires_idx ON public.call_signal_relay USING btree (expires_at);

CREATE INDEX read_receipt_relay_realm_position_idx ON public.read_receipt_relay USING btree (realm_id, position);

CREATE INDEX read_receipt_relay_event_idx ON public.read_receipt_relay USING btree (event_id);

CREATE INDEX read_receipt_relay_expires_idx ON public.read_receipt_relay USING btree (expires_at);

CREATE INDEX canonical_events_actor_idx ON public.canonical_events USING btree (actor_id, actor_seq DESC);

CREATE INDEX canonical_events_actor_received_idx ON public.canonical_events USING btree (actor_id, received_at, id);

CREATE INDEX canonical_events_kind_idx ON public.canonical_events USING btree (kind);

CREATE INDEX canonical_events_kind_received_idx ON public.canonical_events USING btree (kind, received_at, id);

CREATE INDEX canonical_events_peer_sync_endpoints_idx ON public.canonical_events USING btree (received_at, id) WHERE (((envelope #> '{payload,sync_endpoints}'::text[]) IS NOT NULL) OR ((envelope #> '{payload,object,sync_endpoints}'::text[]) IS NOT NULL) OR ((envelope #> '{payload,patch,sync_endpoints}'::text[]) IS NOT NULL));

CREATE INDEX canonical_events_received_idx ON public.canonical_events USING btree (received_at, id);

CREATE UNIQUE INDEX canonical_events_realm_create_unique_idx ON public.canonical_events USING btree (realm_id) WHERE (kind = 'ak.realm.create'::text);

CREATE INDEX canonical_events_space_idx ON public.canonical_events USING btree (realm_id);

CREATE INDEX canonical_events_space_received_idx ON public.canonical_events USING btree (realm_id, received_at, id);

CREATE INDEX state_moves_pending_idx ON public.state_moves USING btree (realm_id, inserted_at, id) WHERE (sealed_by IS NULL);

CREATE INDEX state_moves_sealed_idx ON public.state_moves USING btree (realm_id, inserted_at, id) WHERE (sealed_by IS NOT NULL);

CREATE INDEX state_seals_realm_idx ON public.state_seals USING btree (realm_id, inserted_at, id);

CREATE INDEX state_seals_predecessor_refs_idx ON public.state_seals USING gin (predecessor_refs);

CREATE INDEX state_cell_ops_cell_idx ON public.state_cell_ops USING btree (realm_id, cell_id, seq);

CREATE INDEX state_cell_ops_seal_idx ON public.state_cell_ops USING btree (realm_id, seal_id);

CREATE INDEX contacts_target_idx ON public.contacts USING btree (target_id, scope);

CREATE INDEX devices_actor_updated_idx ON public.devices USING btree (actor_id, updated_at DESC);

CREATE INDEX device_message_ack_tokens_device_idx ON public.device_message_ack_tokens USING btree (recipient, device_id, expires_at);

CREATE INDEX device_messages_recipient_device_position_idx ON public.device_messages USING btree (recipient, device_id, position);

CREATE INDEX device_messages_sender_idempotency_idx ON public.device_messages USING btree (sender, idempotency_key);

CREATE INDEX events_space_created_idx ON public.events USING btree (realm_id, created_at, id);

CREATE INDEX events_thread_created_idx ON public.events USING btree (thread_id, created_at, id) WHERE (thread_id IS NOT NULL);

CREATE INDEX federation_operations_object_type_idx ON public.federation_operations USING btree (object_type);

CREATE INDEX federation_operations_space_idx ON public.federation_operations USING btree (realm_id, created_at);

CREATE INDEX federation_outbox_dead_letter_failed_at ON public.federation_outbox_dead_letter USING btree (failed_at, id);

CREATE UNIQUE INDEX federation_outbox_peer_idem ON public.federation_outbox USING btree (peer_id, idempotency_key);

CREATE INDEX federation_outbox_pending ON public.federation_outbox USING btree (delivered_at, next_attempt_at);

CREATE INDEX federation_frontier_exchange_status_idx ON public.federation_frontier_exchange USING btree (status, updated_at);

CREATE INDEX federation_transactions_destination_received_idx ON public.federation_transactions USING btree (destination_service, received_at);

CREATE INDEX federation_transactions_space_received_idx ON public.federation_transactions USING btree (realm_id, received_at);

CREATE INDEX key_backups_account_idx ON public.key_backups USING btree (account_id);

CREATE INDEX key_backups_actor_idx ON public.key_backups USING btree (actor_id);

CREATE INDEX key_backups_device_idx ON public.key_backups USING btree (device_id);

CREATE UNIQUE INDEX mls_commits_circle_scope_key ON public.mls_commits USING btree (realm_id, circle_id, mls_group_id) WHERE ((effective_scope_kind = 'circle'::text) AND (circle_id IS NOT NULL));

CREATE UNIQUE INDEX mls_commits_realm_scope_key ON public.mls_commits USING btree (realm_id, mls_group_id) WHERE ((effective_scope_kind = 'realm'::text) AND (circle_id IS NULL));

CREATE INDEX mls_key_packages_by_actor_device ON public.mls_key_packages USING btree (actor_id, device_id, claimed_by_mls_group_id);

CREATE INDEX mls_welcomes_recipient_pending ON public.mls_welcomes USING btree (recipient_actor_id, recipient_device_id, delivered_at, enqueued_at);

CREATE INDEX moderation_actions_target_idx ON public.moderation_actions USING btree (target_actor_id);

CREATE INDEX moderation_reports_space_idx ON public.moderation_reports USING btree (realm_id);

CREATE INDEX moderation_reports_target_idx ON public.moderation_reports USING btree (target_actor_id);

CREATE INDEX organizations_handle_idx ON public.organizations USING btree (handle) WHERE (handle IS NOT NULL);

CREATE INDEX organizations_did_idx ON public.organizations USING btree (organization_did);

CREATE INDEX realm_organizations_organization_idx ON public.realm_organizations USING btree (organization_id);

CREATE INDEX realm_organizations_relationship_idx ON public.realm_organizations USING btree (realm_id, relationship, status);

CREATE INDEX realm_owning_organizations_organization_idx ON public.realm_owning_organizations USING btree (organization_id);

CREATE INDEX retention_tombstones_realm_idx ON public.retention_tombstones USING btree (realm_id);

CREATE INDEX multisig_pending_claim_seq_idx ON public.multisig_pending USING btree (claim_seq);

CREATE INDEX multisig_pending_claimed_idx ON public.multisig_pending USING btree (claimed_until);

CREATE INDEX multisig_pending_expires_idx ON public.multisig_pending USING btree (expires_at);

CREATE INDEX multisig_pending_space_idx ON public.multisig_pending USING btree (realm_id);

CREATE INDEX notifications_recipient_idx ON public.notifications USING btree (recipient_id, created_at DESC);

CREATE UNIQUE INDEX notifications_event_source_key ON public.notifications USING btree (recipient_id, source_event_id, notification_type) WHERE (source_event_id IS NOT NULL);

CREATE UNIQUE INDEX notifications_account_artifact_key ON public.notifications USING btree (controller_account_id, recipient_service_id, source_account_artifact_kind, source_account_artifact_id) WHERE (controller_account_id IS NOT NULL);

CREATE INDEX notifications_account_position_idx ON public.notifications USING btree (controller_account_id, recipient_service_id, projection_position) WHERE (controller_account_id IS NOT NULL);

CREATE INDEX notifications_source_idx ON public.notifications USING btree (source_event_id);

CREATE INDEX notifications_strand_idx ON public.notifications USING btree (strand_id);

CREATE INDEX pending_agent_drafts_controller_idx ON public.pending_agent_drafts USING btree (controller_id);

CREATE INDEX pending_agent_drafts_principal_idx ON public.pending_agent_drafts USING btree (agent_id);

CREATE INDEX pending_agent_drafts_state_idx ON public.pending_agent_drafts USING btree (state);

CREATE INDEX policy_documents_owner_idx ON public.policy_documents USING btree (owner_id);

CREATE INDEX policy_documents_scope_subject_idx ON public.policy_documents USING btree (scope, subject_ref, policy_type);

CREATE INDEX projection_circle_members_actor_idx ON public.projection_circle_members USING btree (actor_id);

CREATE INDEX projection_circles_realm_idx ON public.projection_circles USING btree (realm_id);

CREATE INDEX projection_circles_state_idx ON public.projection_circles USING btree (state);

CREATE INDEX projection_events_created_at_idx ON public.projection_events USING btree (created_at);

CREATE INDEX projection_events_effective_scope_idx ON public.projection_events USING btree (effective_scope);

CREATE INDEX projection_events_received_at_idx ON public.projection_events USING btree (received_at);

CREATE INDEX projection_events_stream_order_idx ON public.projection_events USING btree (received_at, event_id);

CREATE INDEX projection_events_space_idx ON public.projection_events USING btree (realm_id);

CREATE INDEX projection_strand_watches_actor_idx ON public.projection_strand_watches USING btree (actor_id) WHERE ((level IS NOT NULL) AND (level <> 'mentions_only'::text));

CREATE INDEX projection_strand_watches_strand_idx ON public.projection_strand_watches USING btree (strand_id) WHERE ((level IS NOT NULL) AND (level <> 'mentions_only'::text));

CREATE INDEX projection_strands_realm_idx ON public.projection_strands USING btree (realm_id);

CREATE INDEX projection_strands_scope_circle_id_idx ON public.projection_strands USING btree (scope_circle_id);

CREATE INDEX projection_strands_state_idx ON public.projection_strands USING btree (state);

CREATE INDEX projection_morphs_realm_idx ON public.projection_morphs USING btree (realm_id);

CREATE INDEX projection_morphs_scope_circle_id_idx ON public.projection_morphs USING btree (scope_circle_id);

CREATE INDEX projection_morphs_state_idx ON public.projection_morphs USING btree (state);

CREATE INDEX projection_morphs_type_idx ON public.projection_morphs USING btree (morph_type);

CREATE INDEX projection_spaces_parent_idx ON public.projection_spaces USING btree (parent_ref) WHERE (parent_ref IS NOT NULL);

CREATE INDEX projection_spaces_realm_idx ON public.projection_spaces USING btree (realm_id);

CREATE INDEX projection_spaces_scope_circle_id_idx ON public.projection_spaces USING btree (scope_circle_id);

CREATE INDEX projection_spaces_state_idx ON public.projection_spaces USING btree (state);

CREATE INDEX push_bridge_cache_fetched_at_idx ON public.push_bridge_cache USING btree (fetched_at);

CREATE INDEX push_bridge_cache_trust_freshness_idx ON public.push_bridge_cache USING btree (trust_level, freshness_at);

CREATE INDEX realm_invites_invitee_idx ON public.realm_invites USING btree (invitee_id);

CREATE UNIQUE INDEX realm_invites_live_direct_unique_idx ON public.realm_invites USING btree (realm_id, invitee_id) WHERE ((invitee_id IS NOT NULL) AND (third_party_id IS NULL) AND (status = ANY (ARRAY['pending'::text, 'claimed'::text, 'send_failed'::text])));

CREATE INDEX realm_invites_realm_idx ON public.realm_invites USING btree (realm_id);

CREATE INDEX recovery_policies_principal_active_idx ON public.recovery_policies USING btree (principal_id, version DESC);

CREATE INDEX recovery_receipts_policy_idx ON public.recovery_receipts USING btree (policy_id, policy_version);

CREATE INDEX recovery_receipts_principal_idx ON public.recovery_receipts USING btree (principal_id);

CREATE INDEX recovery_sessions_principal_idx ON public.recovery_sessions USING btree (principal_id);

CREATE INDEX sessions_actor_device_idx ON public.sessions USING btree (actor_id, device_id, expires_at) WHERE (revoked_at IS NULL);

CREATE INDEX space_members_actor_idx ON public.space_members USING btree (actor_id, membership, realm_id);

CREATE INDEX space_state_events_lookup_idx ON public.space_state_events USING btree (realm_id, event_type, subject, created_at);

CREATE INDEX spaces_discoverability_updated_idx ON public.spaces USING btree (discoverability, updated_at, id);

CREATE INDEX spaces_history_sharing_policy_digest_idx ON public.spaces USING btree (history_sharing_policy_digest) WHERE (history_sharing_policy_digest IS NOT NULL);

CREATE INDEX spaces_history_visibility_updated_idx ON public.spaces USING btree (history_visibility, updated_at, id);

CREATE INDEX spaces_preview_policy_digest_idx ON public.spaces USING btree (preview_policy_digest) WHERE (preview_policy_digest IS NOT NULL);

CREATE INDEX sync_cursor_handles_expiry_idx ON public.sync_cursor_handles USING btree (expires_at_ms);

CREATE INDEX sync_cursor_handles_stream_idx ON public.sync_cursor_handles USING btree (principal_id, device_id, filter_digest);

CREATE INDEX sync_cursor_revocations_expiry_idx ON public.sync_cursor_revocations USING btree (expires_at);

CREATE INDEX idempotency_keys_expiry_idx ON public.idempotency_keys USING btree (expires_at);

CREATE INDEX invite_locators_subject_active_idx ON public.invite_locators USING btree (subject_id, expires_at) WHERE revoked_at IS NULL AND consumed_at IS NULL;

CREATE INDEX webrtc_sessions_expires_idx ON public.webrtc_sessions USING btree (expires_at);

CREATE INDEX webrtc_sessions_space_idx ON public.webrtc_sessions USING btree (realm_id);

CREATE INDEX webvh_documents_expires_at_idx ON public.webvh_documents USING btree (expires_at);

CREATE INDEX webvh_log_events_did_seq_idx ON public.webvh_log_events USING btree (did, seq);

ALTER TABLE ONLY public.account_localparts
    ADD CONSTRAINT account_localparts_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.agent_keys
    ADD CONSTRAINT agent_keys_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent_principals(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.agent_participation
    ADD CONSTRAINT agent_participation_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent_principals(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.agent_sessions
    ADD CONSTRAINT agent_sessions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent_principals(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.federation_outbox_dead_letter
    ADD CONSTRAINT federation_outbox_dead_letter_outbox_id_fkey FOREIGN KEY (outbox_id) REFERENCES public.federation_outbox(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.pending_agent_drafts
    ADD CONSTRAINT pending_agent_drafts_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent_principals(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.projection_circle_members
    ADD CONSTRAINT projection_circle_members_circle_id_fkey FOREIGN KEY (circle_id) REFERENCES public.projection_circles(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.recovery_policies
    ADD CONSTRAINT recovery_policies_supersedes_fkey FOREIGN KEY (supersedes) REFERENCES public.recovery_policies(id);

ALTER TABLE ONLY public.recovery_receipts
    ADD CONSTRAINT recovery_receipts_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.recovery_policies(id);
